<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="InnhenteDNummer" targetNamespace="http://oppgave-poc/AvklareIdentitet" xmlns:bons0="http://oppgave-poc/InnhenteDNummer" xmlns:tns="http://oppgave-poc/AvklareIdentitet" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://oppgave-poc/AvklareIdentitet" xmlns:bons0="http://oppgave-poc/AvklareIdentitet">
      <xsd:element name="avklarIdentitet">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="sedId" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="avklarIdentitetRequestMsg">
    <wsdl:part element="tns:avklarIdentitet" name="avklarIdentitetParameters"/>
  </wsdl:message>
    <wsdl:portType name="AvklareIdentitet">
    <wsdl:operation name="avklarIdentitet">
      <wsdl:input message="tns:avklarIdentitetRequestMsg" name="avklarIdentitetRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>