<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AvklareIdentitet" targetNamespace="http://oppgave-poc/AvklareIdentitetArtifacts" xmlns:ns="http://nav.no/virksomhet/tjenester/person/v1" xmlns:ns0="http://oppgave-poc/SED" xmlns:ns1="http://nav.no/virksomhet/tjenester/oppgave/v1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://oppgave-poc/AvklareIdentitetArtifacts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl0="http://oppgave-poc/AvklareIdentitet" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="AvklareIdentitetPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:AvklareIdentitet"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="SEDPartnerPLT">
    <plnk:role name="Reference">
      <plnk:portType name="ns0:SED"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="OppgavePartnerPLT">
    <plnk:role name="Reference">
      <plnk:portType name="ns1:Oppgave"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="AvklareIdentitet.wsdl" namespace="http://oppgave-poc/AvklareIdentitet"/>
    <wsdl:import location="SED.wsdl" namespace="http://oppgave-poc/SED"/>
    <wsdl:import location="no/nav/virksomhet/tjenester/oppgave/oppgave.wsdl" namespace="http://nav.no/virksomhet/tjenester/oppgave/v1"/>
</wsdl:definitions>