<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AvklareIdentitet" targetNamespace="http://oppgave-poc/AvklareIdentitetArtifacts" xmlns:ns="http://oppgave-poc/MottaHenvendelse" xmlns:ns0="http://oppgave-poc/SED" xmlns:ns1="http://nav.no/virksomhet/tjenester/oppgave/v1" xmlns:ns2="http://oppgave-poc/Person" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plnk:partnerLinkType name="AvklareIdentitetPLT">
    <plnk:role name="Interface">
      <plnk:portType name="ns:MottaHenvendelse"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="SEDPartnerPLT">
    <plnk:role name="Reference">
      <plnk:portType name="ns2:IdentitetAvklaring"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="OppgavePartnerPLT">
    <plnk:role name="Reference">
      <plnk:portType name="ns1:Oppgave"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="MottaHenvendelse.wsdl" namespace="http://oppgave-poc/MottaHenvendelse"/>
    <wsdl:import location="IdentitetAvklaring.wsdl" namespace="http://oppgave-poc/Person"/>
    <wsdl:import location="no/nav/virksomhet/tjenester/oppgave/oppgave.wsdl" namespace="http://nav.no/virksomhet/tjenester/oppgave/v1"/>
</wsdl:definitions>