<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="JOARKOppgaveWSEXP_JOARKOppgaveHttp_Service" targetNamespace="http://nav-cons-dok-joark-oppgave/no/nav/inf/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:Port_0="http://nav-cons-dok-joark-oppgave/no/nav/inf" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://nav-cons-dok-joark-oppgave/no/nav/inf/Binding" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://nav-cons-dok-joark-oppgave/no/nav/inf" location="no/nav/inf/JOARKOppgave.wsdl"/>
  <wsdl:binding name="JOARKOppgaveWSEXP_JOARKOppgaveHttpBinding" type="Port_0:JOARKOppgave">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentOppgaveListe">
      <soap:operation/>
      <wsdl:input name="hentOppgaveListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentOppgaveListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultDokGenerisk">
        <soap:fault name="faultDokGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettOppgave">
      <soap:operation/>
      <wsdl:input name="opprettOppgaveRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettOppgaveResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultDokGenerisk">
        <soap:fault name="faultDokGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="JOARKOppgaveWSEXP_JOARKOppgaveHttpService">
    <wsdl:port name="JOARKOppgaveWSEXP_JOARKOppgaveHttpPort" binding="this:JOARKOppgaveWSEXP_JOARKOppgaveHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-dok-joark-oppgaveWeb/sca/JOARKOppgaveWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
