package no.stelvio.common.util;

import java.io.PrintWriter;
import java.io.StringWriter;

public class ExceptionUtils {
	/**
	 * Convert exception stacktrace to string
	 * 
	 * @param throwable
	 *            the Throwable to be examined
	 * @return the stack trace as generated by the exception's printStackTrace(PrintWriter) method
	 */
	public static String getStackTrace(Throwable throwable) {
		StringWriter sw = new StringWriter();
		throwable.printStackTrace(new PrintWriter(sw));
		return sw.toString();
	}
}
