//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package stelvio;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;

@WebService(name = "Metronome", targetNamespace = "http://stelvio")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Metronome {


    /**
     * 
     * @param time
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "tick", targetNamespace = "http://stelvio", className = "stelvio.Tick")
    public void tick(
        @WebParam(name = "time", targetNamespace = "")
        XMLGregorianCalendar time);

}
