//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package stelvio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "MetronomeWSEXP_MetronomeHttpService", targetNamespace = "http://stelvio", wsdlLocation = "WEB-INF/wsdl/stelvio-example-metronome-static-broker_MetronomeWSEXP.wsdl")
public class MetronomeWSEXPMetronomeHttpService
    extends Service
{

    private final static URL METRONOMEWSEXPMETRONOMEHTTPSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = stelvio.MetronomeWSEXPMetronomeHttpService.class.getResource("/WEB-INF/wsdl/stelvio-example-metronome-static-broker_MetronomeWSEXP.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/stelvio-example-metronome-static-broker_MetronomeWSEXP.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        METRONOMEWSEXPMETRONOMEHTTPSERVICE_WSDL_LOCATION = url;
    }

    public MetronomeWSEXPMetronomeHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MetronomeWSEXPMetronomeHttpService() {
        super(METRONOMEWSEXPMETRONOMEHTTPSERVICE_WSDL_LOCATION, new QName("http://stelvio", "MetronomeWSEXP_MetronomeHttpService"));
    }

    /**
     * 
     * @return
     *     returns Metronome
     */
    @WebEndpoint(name = "MetronomeWSEXP_MetronomeHttpPort")
    public Metronome getMetronomeWSEXPMetronomeHttpPort() {
        return (Metronome)super.getPort(new QName("http://stelvio", "MetronomeWSEXP_MetronomeHttpPort"), Metronome.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Metronome
     */
    @WebEndpoint(name = "MetronomeWSEXP_MetronomeHttpPort")
    public Metronome getMetronomeWSEXPMetronomeHttpPort(WebServiceFeature... features) {
        return (Metronome)super.getPort(new QName("http://stelvio", "MetronomeWSEXP_MetronomeHttpPort"), Metronome.class, features);
    }

}
