//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/wsn/br-2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oasis_open.docs.wsn.br_2;
