<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="EchoServiceWSEXP_EchoServiceHttp_Service" targetNamespace="http://www.stelvio.no/example/services/V1/EchoService/Binding2" xmlns:Port_0="http://www.stelvio.no/example/services/V1/EchoService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://www.stelvio.no/example/services/V1/EchoService/Binding2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="EchoService.wsdl" namespace="http://www.stelvio.no/example/services/V1/EchoService"/>
  <wsdl:binding name="EchoServiceWSEXP_EchoServiceHttpBinding" type="Port_0:EchoService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="echo">
      <soap:operation soapAction="test"/>
      <wsdl:input name="echoRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="echoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="echoFault1">
        <soap:fault name="echoFault1" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EchoServiceWSEXP_EchoServiceHttpService">
    <wsdl:port binding="this:EchoServiceWSEXP_EchoServiceHttpBinding" name="EchoServiceWSEXP_EchoServiceHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-echo-serviceWeb/sca/EchoServiceWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>