<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bpws="http://schemas.xmlsoap.org/ws/2004/03/business-process/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://nav-bproc-pen-testProc/no/nav/bpel/TestBPELArtifacts" xmlns:wsdl0="http://nav-bproc-pen-testProc/no/nav/inf/TestProc" xmlns:wsdl1="http://nav-lib-pen/no/nav/lib/pen/inf/Vedtak" xmlns:wsdl2="http://nav-lib-pen/no/nav/lib/pen/inf/Pensjonssak" xmlns:wsdl3="http://nav-bproc-pen-testproc/no/nav/inf/AsynkPensjonssak" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TestBPEL" targetNamespace="http://nav-bproc-pen-testProc/no/nav/bpel/TestBPELArtifacts">
  <plnk:partnerLinkType name="TestProcPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:TestProc"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="VedtakPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl1:Vedtak"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <bpws:property name="vedtakId" type="xsd:string"/>
    <bpws:propertyAlias messageType="wsdl0:invokeTestProcRequestMsg" part="invokeTestProcParameters" propertyName="tns:vedtakId">
    <bpws:query><![CDATA[/testProcRequest/vedtakId]]></bpws:query>
  </bpws:propertyAlias>
    <bpws:propertyAlias messageType="wsdl0:avsluttProsessRequestMsg" part="avsluttProsessParameters" propertyName="tns:vedtakId">
    <bpws:query><![CDATA[/vedtakId]]></bpws:query>
  </bpws:propertyAlias>
    <plnk:partnerLinkType name="AsynkPensjonssakPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl3:AsynkPensjonssak"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="../lib/test/inf/TestProc.wsdl" namespace="http://nav-bproc-pen-testProc/no/nav/inf/TestProc"/>
    <wsdl:import location="../lib/test/inf/Vedtak.wsdl" namespace="http://nav-lib-pen/no/nav/lib/pen/inf/Vedtak"/>
    <wsdl:import location="../inf/AsynkPensjonssak.wsdl" namespace="http://nav-bproc-pen-testproc/no/nav/inf/AsynkPensjonssak"/>
</wsdl:definitions>
