<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ContextHandlerVerifierWSEXP_ContextHandlerVerifierHttp_Service" targetNamespace="http://stelvio-example-contexthandler-service/no/nav/inf/ContextHandlerVerifier/Binding" xmlns:Port_0="http://stelvio-example-contexthandler-service/no/nav/inf/ContextHandlerVerifier" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://stelvio-example-contexthandler-service/no/nav/inf/ContextHandlerVerifier/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ContextHandlerVerifier.wsdl" namespace="http://stelvio-example-contexthandler-service/no/nav/inf/ContextHandlerVerifier"/>
  <wsdl:binding name="ContextHandlerVerifierWSEXP_ContextHandlerVerifierHttpBinding" type="Port_0:ContextHandlerVerifier">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="callNoWSChain">
      <soap:operation soapAction=""/>
      <wsdl:input name="callNoWSChainRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="callNoWSChainResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="callWSChain">
      <soap:operation soapAction=""/>
      <wsdl:input name="callWSChainRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="callWSChainResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ContextHandlerVerifierWSEXP_ContextHandlerVerifierHttpService">
    <wsdl:port binding="this:ContextHandlerVerifierWSEXP_ContextHandlerVerifierHttpBinding" name="ContextHandlerVerifierWSEXP_ContextHandlerVerifierHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-contexthandler-serviceWeb/sca/ContextHandlerVerifierWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>