<#macro LoadBalancerGroup name hostname1 hostname2>
	<LoadBalancerGroup name="${name}" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Algorithm>round-robin</Algorithm>
		<Damp>120</Damp>
		<NeverReturnSickMember>off</NeverReturnSickMember>
		<LBGroupMembers>
			<Server>${hostname1}</Server>
			<Weight>1</Weight>
			<MappedPort>0</MappedPort>
			<Activity/>
			<HealthPort/>
			<LBMemberState>enabled</LBMemberState>
		</LBGroupMembers>
		<LBGroupMembers>
			<Server>${hostname2}</Server>
			<Weight>1</Weight>
			<MappedPort>0</MappedPort>
			<Activity/>
			<HealthPort/>
			<LBMemberState>enabled</LBMemberState>
		</LBGroupMembers>
		<TryEveryServerBeforeFailing>off</TryEveryServerBeforeFailing>
		<LBGroupChecks>
			<Active>off</Active>
			<URI>/</URI>
			<Port>80</Port>
			<SSL>Standard</SSL>
			<Post>on</Post>
			<Input>store:///healthcheck.xml</Input>
			<Timeout>10</Timeout>
			<Frequency>180</Frequency>
			<XPath>/</XPath>
			<Filter>store:///healthcheck.xsl</Filter>
			<SSLProxyProfile/>
		</LBGroupChecks>
		<MasqueradeMember>off</MasqueradeMember>
	</LoadBalancerGroup>
</#macro>