<#macro MultiProtocolGateway name httpsSourceProtocolHandler SSLProxyProfile stylePolicy>
	<MultiProtocolGateway name="${name}" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Priority>normal</Priority>
		<FrontProtocol class="HTTPSSourceProtocolHandler">${httpsSourceProtocolHandler}</FrontProtocol>
		<XMLManager class="XMLManager">default</XMLManager>
		<SSLProxy class="SSLProxyProfile">${SSLProxyProfile}</SSLProxy>
		<DefaultParamNamespace>http://www.datapower.com/param/config</DefaultParamNamespace>
		<QueryParamNamespace>http://www.datapower.com/param/query</QueryParamNamespace>
		<BackendUrl>http://dynamic-backend</BackendUrl>
		<PropagateURI>off</PropagateURI>
		<MonitorProcessingPolicy>terminate-at-first-throttle</MonitorProcessingPolicy>
		<RequestAttachments>strip</RequestAttachments>
		<ResponseAttachments>strip</ResponseAttachments>
		<RootPartNotFirstAction>process-in-order</RootPartNotFirstAction>
		<FrontAttachmentFormat>dynamic</FrontAttachmentFormat>
		<BackAttachmentFormat>dynamic</BackAttachmentFormat>
		<MIMEFrontHeaders>on</MIMEFrontHeaders>
		<MIMEBackHeaders>on</MIMEBackHeaders>
		<StreamOutputToBack>buffer-until-verification</StreamOutputToBack>
		<StreamOutputToFront>buffer-until-verification</StreamOutputToFront>
		<MaxMessageSize>0</MaxMessageSize>
		<GatewayParserLimits>off</GatewayParserLimits>
		<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
		<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
		<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
		<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
		<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
		<ParserLimitsMaxPrefixes>0</ParserLimitsMaxPrefixes>
		<ParserLimitsMaxNamespaces>0</ParserLimitsMaxNamespaces>
		<ParserLimitsMaxLocalNames>0</ParserLimitsMaxLocalNames>
		<ParserLimitsAttachmentByteCount>2000000000</ParserLimitsAttachmentByteCount>
		<ParserLimitsAttachmentPackageByteCount>0</ParserLimitsAttachmentPackageByteCount>
		<DebugMode persisted="false">off</DebugMode>
		<DebuggerType>internal</DebuggerType>
		<DebugHistory>25</DebugHistory>
		<RequestType>soap</RequestType>
		<ResponseType>soap</ResponseType>
		<FlowControl>off</FlowControl>
		<SOAPSchemaURL>store:///schemas/soap-envelope.xsd</SOAPSchemaURL>
		<FrontTimeout>120</FrontTimeout>
		<BackTimeout>120</BackTimeout>
		<FrontPersistentTimeout>180</FrontPersistentTimeout>
		<BackPersistentTimeout>180</BackPersistentTimeout>
		<IncludeResponseTypeEncoding>off</IncludeResponseTypeEncoding>
		<BackHTTPVersion>HTTP/1.1</BackHTTPVersion>
		<AllowCompression>off</AllowCompression>
		<PersistentConnections>on</PersistentConnections>
		<LoopDetection>off</LoopDetection>
		<FollowRedirects>on</FollowRedirects>
		<DoHostRewriting>on</DoHostRewriting>
		<DoChunkedUpload>off</DoChunkedUpload>
		<ProcessHTTPErrors>on</ProcessHTTPErrors>
		<HTTPClientIPLabel>X-Client-IP</HTTPClientIPLabel>
		<InOrderMode>
			<Request>off</Request>
			<Backend>off</Backend>
			<Response>off</Response>
		</InOrderMode>
		<WSAMode>sync2sync</WSAMode>
		<WSARequireAAA>off</WSARequireAAA>
		<WSAStrip>on</WSAStrip>
		<WSADefaultReplyTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultReplyTo>
		<WSADefaultFaultTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultFaultTo>
		<WSAForce>off</WSAForce>
		<WSAGenStyle>sync</WSAGenStyle>
		<WSAHTTPAsyncResponseCode>204</WSAHTTPAsyncResponseCode>
		<WSATimeout>120</WSATimeout>
		<WSRMEnabled>off</WSRMEnabled>
		<WSRMSequenceExpiration>3600</WSRMSequenceExpiration>
		<WSRMDestinationAcceptCreateSequence>on</WSRMDestinationAcceptCreateSequence>
		<WSRMDestinationMaximumSequences>400</WSRMDestinationMaximumSequences>
		<WSRMDestinationInOrder>off</WSRMDestinationInOrder>
		<WSRMDestinationMaximumInOrderQueueLength>10</WSRMDestinationMaximumInOrderQueueLength>
		<WSRMDestinationAcceptOffers>off</WSRMDestinationAcceptOffers>
		<WSRMFrontForce>off</WSRMFrontForce>
		<WSRMBackForce>off</WSRMBackForce>
		<WSRMBackCreateSequence>off</WSRMBackCreateSequence>
		<WSRMFrontCreateSequence>off</WSRMFrontCreateSequence>
		<WSRMSourceMakeOffer>off</WSRMSourceMakeOffer>
		<WSRMUsesSequenceSSL>off</WSRMUsesSequenceSSL>
		<WSRMSourceMaximumSequences>400</WSRMSourceMaximumSequences>
		<WSRMSourceRetransmissionInterval>10</WSRMSourceRetransmissionInterval>
		<WSRMSourceExponentialBackoff>on</WSRMSourceExponentialBackoff>
		<WSRMSourceMaximumRetransmissions>4</WSRMSourceMaximumRetransmissions>
		<WSRMSourceMaximumQueueLength>30</WSRMSourceMaximumQueueLength>
		<WSRMSourceRequestAckCount>1</WSRMSourceRequestAckCount>
		<WSRMSourceInactivityClose>360</WSRMSourceInactivityClose>
		<ForcePolicyExec>off</ForcePolicyExec>
		<RewriteErrors>on</RewriteErrors>
		<StylePolicy class="StylePolicy">${stylePolicy}</StylePolicy>
		<Type>dynamic-backend</Type>
	</MultiProtocolGateway>
</#macro>