<#macro STSProxy name port loopbackPort cfgHost ldapHost ldapPort ldapBindDN ldapBindPw ldapBaseDN ldapCheckGroup ADHost>
	<URLMap name="default-attempt-stream-all" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<URLMapRule>
			<Pattern>*</Pattern>
		</URLMapRule>
	</URLMap>
	<CompileOptionsPolicy name="default-attempt-stream" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<XSLTVersion>XSLT10</XSLTVersion>
		<Strict>off</Strict>
		<TryStream class="URLMap">default-attempt-stream-all</TryStream>
		<StackSize>524288</StackSize>
		<WSIValidation>ignore</WSIValidation>
		<WSDLValidateBody>strict</WSDLValidateBody>
		<WSDLValidateHeaders>lax</WSDLValidateHeaders>
		<WSDLValidateFaults>strict</WSDLValidateFaults>
		<WSDLWrappedFaults>off</WSDLWrappedFaults>
		<WSDLStrictSOAPVersion>off</WSDLStrictSOAPVersion>
		<XACMLDebug>off</XACMLDebug>
	</CompileOptionsPolicy>
	<XMLManager name="default-attempt-stream" intrinsic="true" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<UserSummary>Default Streaming XML-Manager</UserSummary>
		<CompileOptionsPolicy class="CompileOptionsPolicy">default-attempt-stream</CompileOptionsPolicy>
		<CacheSize>256</CacheSize>
		<SHA1Caching>on</SHA1Caching>
		<StaticDocumentCalls>on</StaticDocumentCalls>
		<SearchResults>on</SearchResults>
		<SupportTxWarn>off</SupportTxWarn>
		<Memoization>on</Memoization>
		<ParserLimitsBytesScanned>268435456</ParserLimitsBytesScanned>
		<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
		<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
		<ParserLimitsMaxNodeSize>268435456</ParserLimitsMaxNodeSize>
		<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
		<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
		<ParserLimitsMaxPrefixes>0</ParserLimitsMaxPrefixes>
		<ParserLimitsMaxNamespaces>0</ParserLimitsMaxNamespaces>
		<ParserLimitsMaxLocalNames>0</ParserLimitsMaxLocalNames>
		<DocCacheMaxDocs>5000</DocCacheMaxDocs>
		<DocCacheSize>0</DocCacheSize>
		<UserAgent class="HTTPUserAgent">default</UserAgent>
	</XMLManager>
	<HTTPSSourceProtocolHandler name="sts-HttpsFrontsideHandler" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
			<mAdminState>enabled</mAdminState>
			<LocalAddress>${cfgHost}</LocalAddress>
			<LocalPort>${port}</LocalPort>
			<HTTPVersion>HTTP/1.1</HTTPVersion>
			<AllowedFeatures>
				<HTTP-1.0>on</HTTP-1.0>
				<HTTP-1.1>on</HTTP-1.1>
				<POST>on</POST>
				<GET>off</GET>
				<PUT>on</PUT>
				<HEAD>off</HEAD>
				<OPTIONS>off</OPTIONS>
				<TRACE>off</TRACE>
				<DELETE>off</DELETE>
				<CONNECT>off</CONNECT>
				<QueryString>on</QueryString>
				<FragmentIdentifiers>on</FragmentIdentifiers>
				<DotDot>off</DotDot>
				<CmdExe>off</CmdExe>
			</AllowedFeatures>
			<PersistentConnections>on</PersistentConnections>
			<AllowCompression>off</AllowCompression>
			<MaxURLLen>16384</MaxURLLen>
			<MaxTotalHdrLen>128000</MaxTotalHdrLen>
			<MaxHdrCount>0</MaxHdrCount>
			<MaxNameHdrLen>0</MaxNameHdrLen>
			<MaxValueHdrLen>0</MaxValueHdrLen>
			<MaxQueryStringLen>0</MaxQueryStringLen>
			<SSLProxy class="SSLProxyProfile">${cfgHost}_SSLProxyProfile</SSLProxy>
			<CredentialCharset>protocol</CredentialCharset>
		</HTTPSSourceProtocolHandler>
	<WSEndpointRewritePolicy name="SecurityTokenService" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<WSEndpointLocalRewriteRule>
			<ServicePortMatchRegexp>^{http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl}SecurityTokenServiceSOAP$</ServicePortMatchRegexp>
			<LocalEndpointProtocol>default</LocalEndpointProtocol>
			<LocalEndpointHostname>0.0.0.0</LocalEndpointHostname>
			<LocalEndpointPort>0</LocalEndpointPort>
			<LocalEndpointURI>/SecurityTokenServiceProvider/</LocalEndpointURI>
			<FrontProtocol class="HTTPSourceProtocolHandler">sts-HttpsFrontsideHandler</FrontProtocol>
			<UseFrontProtocol>on</UseFrontProtocol>
			<WSDLBindingProtocol>soap-11</WSDLBindingProtocol>
			<FrontsidePortSuffix/>
		</WSEndpointLocalRewriteRule>
		<WSEndpointRemoteRewriteRule>
			<ServicePortMatchRegexp>^{http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl}SecurityTokenServiceSOAP$</ServicePortMatchRegexp>
			<RemoteEndpointProtocol>http</RemoteEndpointProtocol>
			<RemoteEndpointHostname>${cfgHost}</RemoteEndpointHostname>
			<RemoteEndpointPort>${loopbackPort}</RemoteEndpointPort>
			<RemoteEndpointURI>/SecurityTokenServiceProvider/</RemoteEndpointURI>
			<RemoteMQQM/>
			<RemoteTibcoEMS/>
			<RemoteWebSphereJMS/>
		</WSEndpointRemoteRewriteRule>
	</WSEndpointRewritePolicy>
	<Matching name="action_negative_match" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<MatchRules>
			<Type>xpath</Type>
			<HttpTag/>
			<HttpValue/>
			<Url/>
			<ErrorCode/>
			<XPATHExpression>//*[local-name()='Action' and not(node()='http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue')]</XPATHExpression>
			<Method>default</Method>
		</MatchRules>
		<MatchWithPCRE>off</MatchWithPCRE>
		<CombineWithOr>off</CombineWithOr>
	</Matching>
	<StylePolicyAction name="SecurityTokenService_action_negative_match_rule_xform_4" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>xform</Type>
		<Input>INPUT</Input>
		<Transform>local:///xslt/wrongAction_fault_handler.xsl</Transform>
		<Output>OUTPUT</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<WSStylePolicyRule name="SecurityTokenService_action_negative_match_rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>request-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_action_negative_match_rule_xform_4</Actions>
	</WSStylePolicyRule>
	<Matching name="Match-SAMLV2-OpenAMClaim" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<MatchRules>
			<Type>xpath</Type>
			<HttpTag/>
			<HttpValue/>
			<Url/>
			<ErrorCode/>
			<XPATHExpression>//*[local-name()='KeyType' and node()='http://docs.oasis-open.org/ws-sx/ws-trust/200512/Bearer']</XPATHExpression>
			<Method>default</Method>
		</MatchRules>
		<MatchRules>
			<Type>xpath</Type>
			<HttpTag/>
			<HttpValue/>
			<Url/>
			<ErrorCode/>
			<XPATHExpression>//*[local-name()='RequestType' and node()='http://docs.oasis-open.org/ws-sx/ws-trust/200512/Issue']</XPATHExpression>
			<Method>default</Method>
		</MatchRules>
		<MatchRules>
			<Type>xpath</Type>
			<HttpTag/>
			<HttpValue/>
			<Url/>
			<ErrorCode/>
			<XPATHExpression>//*[local-name()='TokenType' and node()='http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0']</XPATHExpression>
			<Method>default</Method>
		</MatchRules>
		<MatchWithPCRE>off</MatchWithPCRE>
		<CombineWithOr>off</CombineWithOr>
	</Matching>
	<LDAPSearchParameters name="LDAPSearch_sAMActtionName" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<LDAPBaseDN>${ldapBaseDN}</LDAPBaseDN>
		<LDAPReturnedAttribute>dn</LDAPReturnedAttribute>
		<LDAPFilterPrefix>sAMAccountName=</LDAPFilterPrefix>
		<LDAPScope>subtree</LDAPScope>
	</LDAPSearchParameters>
	<AAAPolicy name="ConsumerAAA" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<ExtractIdentity>
			<EIBitmap>
				<http-basic-auth>off</http-basic-auth>
				<wssec-username>on</wssec-username>
				<wssec-derived-key>off</wssec-derived-key>
				<wssec-binary-token>off</wssec-binary-token>
				<ws-secure-conversation>off</ws-secure-conversation>
				<ws-trust>off</ws-trust>
				<kerberos>off</kerberos>
				<kerberos-spnego>off</kerberos-spnego>
				<client-ssl>off</client-ssl>
				<saml-attr-name>off</saml-attr-name>
				<saml-authen-name>off</saml-authen-name>
				<saml-artifact>off</saml-artifact>
				<client-ip-address>off</client-ip-address>
				<signer-dn>off</signer-dn>
				<token>off</token>
				<cookie-token>off</cookie-token>
				<ltpa>off</ltpa>
				<metadata>off</metadata>
				<custom>off</custom>
				<html-forms-auth>off</html-forms-auth>
				<oauth>off</oauth>
			</EIBitmap>
			<EICustomURL/>
			<EIXPath/>
			<EISignerDNValcred/>
			<EICookieName/>
			<EIBasicAuthRealm>login</EIBasicAuthRealm>
			<EIUseWSSec>off</EIUseWSSec>
			<EIMetadata/>
			<EIAllowRemoteTokenReference>off</EIAllowRemoteTokenReference>
			<EIRemoteTokenProcessService/>
			<EIPasswordRetrievalMechanism>xmlfile</EIPasswordRetrievalMechanism>
			<EIPasswordRetrievalCustomURL/>
			<EIPasswordRetrievalAAAInfoURL/>
			<EISSLProxyProfile/>
			<EIFormsLoginPolicy/>
			<EIOAuthClientGroup/>
		</ExtractIdentity>
		<Authenticate>
			<AUMethod>ldap</AUMethod>
			<AUCustomURL/>
			<AUMapURL/>
			<AUHost>${ldapHost}</AUHost>
			<AUPort>${ldapPort}</AUPort>
			<AUSSLValcred/>
			<AUCacheAllow>absolute</AUCacheAllow>
			<AUCacheTTL>3</AUCacheTTL>
			<AUKerberosPrincipal/>
			<AUKerberosPassword/>
			<AUClearTrustServerURL/>
			<AUClearTrustApplication/>
			<AUSAMLArtifactResponder/>
			<AUKerberosVerifySignature>on</AUKerberosVerifySignature>
			<AUNetegrityBaseURI/>
			<AUSAMLAuthQueryServer/>
			<AUSAMLVersion>1.1</AUSAMLVersion>
			<AULDAPPrefix>cn=</AULDAPPrefix>
			<AULDAPSuffix/>
			<AULDAPLoadBalanceGroup/>
			<AUKerberosKeytab/>
			<AUWSTrustURL/>
			<AUSAML2Issuer/>
			<AUSignerValcred/>
			<AUSignedXPath/>
			<AUSSLProxyProfile/>
			<AUNetegrityConfig/>
			<AULDAPBindDN>${ldapBindDN}</AULDAPBindDN>
			<AULDAPBindPassword>${ldapBindPw}</AULDAPBindPassword>
			<AULDAPSearchAttribute>userPassword</AULDAPSearchAttribute>
			<AULTPATokenVersionsBitmap>
				<LTPA>off</LTPA>
				<LTPA2>on</LTPA2>
				<LTPADomino>off</LTPADomino>
			</AULTPATokenVersionsBitmap>
			<AULTPAKeyFile/>
			<AULTPAKeyFilePassword/>
			<AULTPAStashFile/>
			<AUBinaryTokenX509Valcred/>
			<AUTAMServer/>
			<AUAllowRemoteTokenReference>off</AUAllowRemoteTokenReference>
			<AURemoteTokenProcessService/>
			<AUWSTrustVersion>1.2</AUWSTrustVersion>
			<AULDAPSearchForDN>on</AULDAPSearchForDN>
			<AULDAPSearchParameters class="LDAPSearchParameters">LDAPSearch_sAMActtionName</AULDAPSearchParameters>
			<AUWSTrustRequireClientEntropy>off</AUWSTrustRequireClientEntropy>
			<AUWSTrustClientEntropySize>32</AUWSTrustClientEntropySize>
			<AUWSTrustRequireServerEntropy>off</AUWSTrustRequireServerEntropy>
			<AUWSTrustServerEntropySize>32</AUWSTrustServerEntropySize>
			<AUWSTrustRequireRSTC>off</AUWSTrustRequireRSTC>
			<AUWSTrustRequireAppliesToHeader>off</AUWSTrustRequireAppliesToHeader>
			<AUWSTrustAppliesToHeader/>
			<AUWSTrustEncryptionCertificate/>
			<AUZOSNSSConfig/>
			<AULDAPAttributes/>
			<AUSkewTime>0</AUSkewTime>
			<AUTAMPACReturn>off</AUTAMPACReturn>
		</Authenticate>
		<MapCredentials>
			<MCMethod>none</MCMethod>
			<MCCustomURL/>
			<MCMapURL/>
			<MCMapXPath/>
			<MCTFIMEndpoint/>
		</MapCredentials>
		<ExtractResource>
			<ERBitmap>
				<target-url>off</target-url>
				<original-url>on</original-url>
				<request-uri>off</request-uri>
				<request-opname>off</request-opname>
				<http-method>off</http-method>
				<XPath>off</XPath>
				<metadata>off</metadata>
			</ERBitmap>
			<ERXPath/>
			<ERMetadata/>
		</ExtractResource>
		<MapResource>
			<MRMethod>none</MRMethod>
			<MRCustomURL/>
			<MRMapURL/>
			<MRMapXPath/>
			<MRTAMMap>WebSEAL</MRTAMMap>
			<MRTAMInstancePrefix/>
			<MRTAMWebSEALDynURLFile/>
		</MapResource>
		<Authorize>
			<AZMethod>ldap</AZMethod>
			<AZCustomURL/>
			<AZMapURL/>
			<AZHost>${ldapHost}</AZHost>
			<AZPort>${ldapPort}</AZPort>
			<AZLDAPGroup>${ldapCheckGroup}</AZLDAPGroup>
			<AZValcred/>
			<AZSAMLURL/>
			<AZSAMLType>any</AZSAMLType>
			<AZSAMLXPath/>
			<AZSAMLNameQualifier/>
			<AZCacheAllow>absolute</AZCacheAllow>
			<AZCacheTTL>3</AZCacheTTL>
			<AZNetegrityBaseURI/>
			<AZNetegrityOpNameExtension/>
			<AZClearTrustServerURL/>
			<AZSAMLVersion>1.1</AZSAMLVersion>
			<AZLDAPLoadBalanceGroup/>
			<AZLDAPBindDN>${ldapBindDN}</AZLDAPBindDN>
			<AZLDAPBindPassword>${ldapBindPw}</AZLDAPBindPassword>
			<AZLDAPGroupAttribute>member</AZLDAPGroupAttribute>
			<AZSSLProxyProfile/>
			<AZNetegrityConfig/>
			<AZLDAPSearchScope>subtree</AZLDAPSearchScope>
			<AZLDAPSearchFilter>(objectClass=*)</AZLDAPSearchFilter>
			<AZXACMLVersion>2.0</AZXACMLVersion>
			<AZXACMLPEPType>deny-biased</AZXACMLPEPType>
			<AZXACMLUseOnBoxPDP>on</AZXACMLUseOnBoxPDP>
			<AZXACMLPDP/>
			<AZXACMLExternalPDPUrl/>
			<AZXACMLBindingMethod>custom</AZXACMLBindingMethod>
			<AZXACMLBindingObject/>
			<AZXACMLBindingXSL/>
			<AZXACMLCustomObligation/>
			<AZXACMLUseSAML2>off</AZXACMLUseSAML2>
			<AZTAMServer/>
			<AZTAMDefaultAction>T</AZTAMDefaultAction>
			<AZTAMActionResourceMap/>
			<AZXACMLUseSOAP>off</AZXACMLUseSOAP>
			<AZZOSNSSConfig/>
			<AZSAFDefaultAction>r</AZSAFDefaultAction>
			<AZLDAPAttributes/>
			<AZSkewTime>0</AZSkewTime>
			<AZOAuthValidationEndpointType>tfim</AZOAuthValidationEndpointType>
			<AZTFIMEndpoint/>
			<AZOAuthEnforceScope>off</AZOAuthEnforceScope>
			<AZOAuthExportHeaders>on</AZOAuthExportHeaders>
			<AZTAMPACReturn>off</AZTAMPACReturn>
			<AZTAMPACUse>off</AZTAMPACUse>
		</Authorize>
		<PostProcess>
			<PPEnabled>off</PPEnabled>
			<PPCustomURL/>
			<PPSAMLAuthAssertion>off</PPSAMLAuthAssertion>
			<PPSAMLServerName>XS</PPSAMLServerName>
			<PPSAMLNameQualifier/>
			<PPKerberosTicket>off</PPKerberosTicket>
			<PPKerberosClient/>
			<PPKerberosClientPassword/>
			<PPKerberosServer/>
			<PPWSTrust>off</PPWSTrust>
			<PPTimestamp>on</PPTimestamp>
			<PPTimestampExpiry>0</PPTimestampExpiry>
			<PPAllowRenewal>off</PPAllowRenewal>
			<PPSAMLVersion>2.0</PPSAMLVersion>
			<PPSAMLSendSLO>off</PPSAMLSendSLO>
			<PPSAMLSLOEndpoint/>
			<PPSSLProxyProfile/>
			<PPWSUsernameToken>off</PPWSUsernameToken>
			<PPWSUsernameTokenPasswordType>Digest</PPWSUsernameTokenPasswordType>
			<PPSAMLValidity>0</PPSAMLValidity>
			<PPSAMLSkew>0</PPSAMLSkew>
			<PPWSUsernameTokenIncludePwd>on</PPWSUsernameTokenIncludePwd>
			<PPLTPA>off</PPLTPA>
			<PPLTPAVersion>LTPA2</PPLTPAVersion>
			<PPLTPAExpiry>600</PPLTPAExpiry>
			<PPLTPAKeyFile/>
			<PPLTPAKeyFilePassword/>
			<PPLTPAStashFile/>
			<PPKerberosSPNEGOToken>off</PPKerberosSPNEGOToken>
			<PPKerberosBstValueType>http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ</PPKerberosBstValueType>
			<PPSAMLUseWSSec>off</PPSAMLUseWSSec>
			<PPKerberosClientKeytab/>
			<PPUseWSSec>off</PPUseWSSec>
			<PPActorRoleID/>
			<PPTFIMTokenMapping>off</PPTFIMTokenMapping>
			<PPTFIMEndpoint/>
			<PPWSDerivedKeyUsernameToken>off</PPWSDerivedKeyUsernameToken>
			<PPWSDerivedKeyUsernameTokenIterations>1000</PPWSDerivedKeyUsernameTokenIterations>
			<PPWSUsernameTokenAllowReplacement>off</PPWSUsernameTokenAllowReplacement>
			<PPTFIMReplaceMethod>all</PPTFIMReplaceMethod>
			<PPTFIMRetrieveMode>CallTFIM</PPTFIMRetrieveMode>
			<PPHMACSigningAlg>hmac-sha1</PPHMACSigningAlg>
			<PPSigningHashAlg>sha1</PPSigningHashAlg>
			<PPWSTrustHeader>off</PPWSTrustHeader>
			<PPWSSCKeySource>random</PPWSSCKeySource>
			<PPSharedSecretKey/>
			<PPWSTrustRenewalWait>0</PPWSTrustRenewalWait>
			<PPWSTrustNewInstance>off</PPWSTrustNewInstance>
			<PPWSTrustNewKey>off</PPWSTrustNewKey>
			<PPWSTrustNeverExpire>off</PPWSTrustNeverExpire>
			<PPICRXToken>off</PPICRXToken>
			<PPICRXUserRealm/>
			<PPSAMLIdentityProvider>off</PPSAMLIdentityProvider>
			<PPSAMLProtocol>assertion</PPSAMLProtocol>
			<PPSAMLResponseDestination/>
			<PPResultWrapup>wssec-replace</PPResultWrapup>
			<PPSAMLAssertionType>
				<authentication>on</authentication>
				<attribute>on</attribute>
				<authorization>off</authorization>
			</PPSAMLAssertionType>
			<PPSAMLSubjectConfirm>bearer</PPSAMLSubjectConfirm>
			<PPSAMLNameID>on</PPSAMLNameID>
			<PPSAMLNameIDFormat/>
			<PPSAMLRecipient/>
			<PPSAMLAudience/>
			<PPSAMLOmitNotBefore>off</PPSAMLOmitNotBefore>
			<PPOneTimeUse>off</PPOneTimeUse>
			<PPSAMLProxy>off</PPSAMLProxy>
			<PPSAMLProxyAudience/>
			<PPSAMLProxyCount>0</PPSAMLProxyCount>
			<PPSAMLAuthzAction>AllHTTP</PPSAMLAuthzAction>
			<PPSAMLAttributes/>
			<PPLTPAInsertCookie>on</PPLTPAInsertCookie>
			<PPTAMPACPropagate>off</PPTAMPACPropagate>
			<PPTAMHeader>iv-creds</PPTAMHeader>
			<PPTAMHeaderSize>0</PPTAMHeaderSize>
		</PostProcess>
		<SAMLSigningHashAlg>sha1</SAMLSigningHashAlg>
		<SAMLSigningAlg>rsa</SAMLSigningAlg>
		<LDAPsuffix/>
		<LogAllowed>on</LogAllowed>
		<LogAllowedLevel>info</LogAllowedLevel>
		<LogRejected>on</LogRejected>
		<LogRejectedLevel>warn</LogRejectedLevel>
		<PingIdentityCompatibility>off</PingIdentityCompatibility>
		<DoSValve>3</DoSValve>
		<LDAPVersion>v2</LDAPVersion>
		<EnforceSOAPActor>on</EnforceSOAPActor>
		<WSSecActorRoleID/>
	</AAAPolicy>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_aaa_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>aaa</Type>
		<Input>INPUT</Input>
		<Output>dpvar_1</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<AAA class="AAAPolicy">ConsumerAAA</AAA>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_setvar_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>setvar</Type>
		<Input>INPUT</Input>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<Variable>var://context/sts/attribute-provider-url</Variable>
		<Value>${ADHost}</Value>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<SAMLAttributes name="OpenAM-SAMLAttributes" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<SAMLAttribute>
			<SourceType>static</SourceType>
			<Name>identType</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath/>
			<ValueData>EksternBruker</ValueData>
			<SubValueData/>
			<FriendlyName/>
		</SAMLAttribute>
		<SAMLAttribute>
			<SourceType>var</SourceType>
			<Name>authenticationLevel</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath/>
			<ValueData>var://context/ldap/auxiliary-attributes</ValueData>
			<SubValueData>authenticationLevel</SubValueData>
			<FriendlyName/>
		</SAMLAttribute>
		<SAMLAttribute>
			<SourceType>var</SourceType>
			<Name>consumerId</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath/>
			<ValueData>var://context/ldap/auxiliary-attributes</ValueData>
			<SubValueData>consumerId</SubValueData>
			<FriendlyName/>
		</SAMLAttribute>
	</SAMLAttributes>
	<AAAPolicy name="SecurityTokenServiceAAA" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<ExtractIdentity>
			<EIBitmap>
				<http-basic-auth>off</http-basic-auth>
				<wssec-username>on</wssec-username>
				<wssec-derived-key>off</wssec-derived-key>
				<wssec-binary-token>off</wssec-binary-token>
				<ws-secure-conversation>off</ws-secure-conversation>
				<ws-trust>off</ws-trust>
				<kerberos>off</kerberos>
				<kerberos-spnego>off</kerberos-spnego>
				<client-ssl>off</client-ssl>
				<saml-attr-name>off</saml-attr-name>
				<saml-authen-name>off</saml-authen-name>
				<saml-artifact>off</saml-artifact>
				<client-ip-address>off</client-ip-address>
				<signer-dn>off</signer-dn>
				<token>on</token>
				<cookie-token>off</cookie-token>
				<ltpa>off</ltpa>
				<metadata>off</metadata>
				<custom>off</custom>
				<html-forms-auth>off</html-forms-auth>
				<oauth>off</oauth>
			</EIBitmap>
			<EICustomURL/>
			<EIXPath>//*[local-name()='RequestSecurityToken']/*[local-name()='Claims']</EIXPath>
			<EISignerDNValcred/>
			<EICookieName/>
			<EIBasicAuthRealm>login</EIBasicAuthRealm>
			<EIUseWSSec>off</EIUseWSSec>
			<EIMetadata/>
			<EIAllowRemoteTokenReference>off</EIAllowRemoteTokenReference>
			<EIRemoteTokenProcessService/>
			<EIPasswordRetrievalMechanism>xmlfile</EIPasswordRetrievalMechanism>
			<EIPasswordRetrievalCustomURL/>
			<EIPasswordRetrievalAAAInfoURL/>
			<EISSLProxyProfile/>
			<EIFormsLoginPolicy/>
			<EIOAuthClientGroup/>
		</ExtractIdentity>
		<Authenticate>
			<AUMethod>custom</AUMethod>
			<AUCustomURL>local:///xslt/authenticate-token.xsl</AUCustomURL>
			<AUMapURL/>
			<AUHost/>
			<AUPort/>
			<AUSSLValcred/>
			<AUCacheAllow>disabled</AUCacheAllow>
			<AUCacheTTL>3</AUCacheTTL>
			<AUKerberosPrincipal/>
			<AUKerberosPassword/>
			<AUClearTrustServerURL/>
			<AUClearTrustApplication/>
			<AUSAMLArtifactResponder/>
			<AUKerberosVerifySignature>on</AUKerberosVerifySignature>
			<AUNetegrityBaseURI/>
			<AUSAMLAuthQueryServer/>
			<AUSAMLVersion>1.1</AUSAMLVersion>
			<AULDAPPrefix>cn=</AULDAPPrefix>
			<AULDAPSuffix/>
			<AULDAPLoadBalanceGroup/>
			<AUKerberosKeytab/>
			<AUWSTrustURL/>
			<AUSAML2Issuer/>
			<AUSignerValcred/>
			<AUSignedXPath/>
			<AUSSLProxyProfile/>
			<AUNetegrityConfig/>
			<AULDAPBindDN/>
			<AULDAPBindPassword/>
			<AULDAPSearchAttribute>userPassword</AULDAPSearchAttribute>
			<AULTPATokenVersionsBitmap>
				<LTPA>off</LTPA>
				<LTPA2>on</LTPA2>
				<LTPADomino>off</LTPADomino>
			</AULTPATokenVersionsBitmap>
			<AULTPAKeyFile/>
			<AULTPAKeyFilePassword/>
			<AULTPAStashFile/>
			<AUBinaryTokenX509Valcred/>
			<AUTAMServer/>
			<AUAllowRemoteTokenReference>off</AUAllowRemoteTokenReference>
			<AURemoteTokenProcessService/>
			<AUWSTrustVersion>1.2</AUWSTrustVersion>
			<AULDAPSearchForDN>off</AULDAPSearchForDN>
			<AULDAPSearchParameters/>
			<AUWSTrustRequireClientEntropy>off</AUWSTrustRequireClientEntropy>
			<AUWSTrustClientEntropySize>32</AUWSTrustClientEntropySize>
			<AUWSTrustRequireServerEntropy>off</AUWSTrustRequireServerEntropy>
			<AUWSTrustServerEntropySize>32</AUWSTrustServerEntropySize>
			<AUWSTrustRequireRSTC>off</AUWSTrustRequireRSTC>
			<AUWSTrustRequireAppliesToHeader>off</AUWSTrustRequireAppliesToHeader>
			<AUWSTrustAppliesToHeader/>
			<AUWSTrustEncryptionCertificate/>
			<AUZOSNSSConfig/>
			<AULDAPAttributes/>
			<AUSkewTime>0</AUSkewTime>
			<AUTAMPACReturn>off</AUTAMPACReturn>
		</Authenticate>
		<MapCredentials>
			<MCMethod>none</MCMethod>
			<MCCustomURL/>
			<MCMapURL/>
			<MCMapXPath/>
			<MCTFIMEndpoint/>
		</MapCredentials>
		<ExtractResource>
			<ERBitmap>
				<target-url>on</target-url>
				<original-url>on</original-url>
				<request-uri>off</request-uri>
				<request-opname>on</request-opname>
				<http-method>off</http-method>
				<XPath>off</XPath>
				<metadata>off</metadata>
			</ERBitmap>
			<ERXPath/>
			<ERMetadata/>
		</ExtractResource>
		<MapResource>
			<MRMethod>none</MRMethod>
			<MRCustomURL/>
			<MRMapURL/>
			<MRMapXPath/>
			<MRTAMMap>WebSEAL</MRTAMMap>
			<MRTAMInstancePrefix/>
			<MRTAMWebSEALDynURLFile/>
		</MapResource>
		<Authorize>
			<AZMethod>anyauthenticated</AZMethod>
			<AZCustomURL/>
			<AZMapURL/>
			<AZHost/>
			<AZPort/>
			<AZLDAPGroup/>
			<AZValcred/>
			<AZSAMLURL/>
			<AZSAMLType>any</AZSAMLType>
			<AZSAMLXPath/>
			<AZSAMLNameQualifier/>
			<AZCacheAllow>absolute</AZCacheAllow>
			<AZCacheTTL>3</AZCacheTTL>
			<AZNetegrityBaseURI/>
			<AZNetegrityOpNameExtension/>
			<AZClearTrustServerURL/>
			<AZSAMLVersion>1.1</AZSAMLVersion>
			<AZLDAPLoadBalanceGroup/>
			<AZLDAPBindDN/>
			<AZLDAPBindPassword/>
			<AZLDAPGroupAttribute>member</AZLDAPGroupAttribute>
			<AZSSLProxyProfile/>
			<AZNetegrityConfig/>
			<AZLDAPSearchScope>subtree</AZLDAPSearchScope>
			<AZLDAPSearchFilter>(objectClass=*)</AZLDAPSearchFilter>
			<AZXACMLVersion>2.0</AZXACMLVersion>
			<AZXACMLPEPType>deny-biased</AZXACMLPEPType>
			<AZXACMLUseOnBoxPDP>on</AZXACMLUseOnBoxPDP>
			<AZXACMLPDP/>
			<AZXACMLExternalPDPUrl/>
			<AZXACMLBindingMethod>custom</AZXACMLBindingMethod>
			<AZXACMLBindingObject/>
			<AZXACMLBindingXSL/>
			<AZXACMLCustomObligation/>
			<AZXACMLUseSAML2>off</AZXACMLUseSAML2>
			<AZTAMServer/>
			<AZTAMDefaultAction>T</AZTAMDefaultAction>
			<AZTAMActionResourceMap/>
			<AZXACMLUseSOAP>off</AZXACMLUseSOAP>
			<AZZOSNSSConfig/>
			<AZSAFDefaultAction>r</AZSAFDefaultAction>
			<AZLDAPAttributes/>
			<AZSkewTime>0</AZSkewTime>
			<AZOAuthValidationEndpointType>tfim</AZOAuthValidationEndpointType>
			<AZTFIMEndpoint/>
			<AZOAuthEnforceScope>off</AZOAuthEnforceScope>
			<AZOAuthExportHeaders>on</AZOAuthExportHeaders>
			<AZTAMPACReturn>off</AZTAMPACReturn>
			<AZTAMPACUse>off</AZTAMPACUse>
		</Authorize>
		<PostProcess>
			<PPEnabled>off</PPEnabled>
			<PPCustomURL/>
			<PPSAMLAuthAssertion>off</PPSAMLAuthAssertion>
			<PPSAMLServerName>sts-datapower</PPSAMLServerName>
			<PPSAMLNameQualifier/>
			<PPKerberosTicket>off</PPKerberosTicket>
			<PPKerberosClient/>
			<PPKerberosClientPassword/>
			<PPKerberosServer/>
			<PPWSTrust>off</PPWSTrust>
			<PPTimestamp>on</PPTimestamp>
			<PPTimestampExpiry>0</PPTimestampExpiry>
			<PPAllowRenewal>off</PPAllowRenewal>
			<PPSAMLVersion>2.0</PPSAMLVersion>
			<PPSAMLSendSLO>off</PPSAMLSendSLO>
			<PPSAMLSLOEndpoint/>
			<PPSSLProxyProfile/>
			<PPWSUsernameToken>off</PPWSUsernameToken>
			<PPWSUsernameTokenPasswordType>Digest</PPWSUsernameTokenPasswordType>
			<PPSAMLValidity>3600</PPSAMLValidity>
			<PPSAMLSkew>0</PPSAMLSkew>
			<PPWSUsernameTokenIncludePwd>on</PPWSUsernameTokenIncludePwd>
			<PPLTPA>off</PPLTPA>
			<PPLTPAVersion>LTPA2</PPLTPAVersion>
			<PPLTPAExpiry>600</PPLTPAExpiry>
			<PPLTPAKeyFile/>
			<PPLTPAKeyFilePassword/>
			<PPLTPAStashFile/>
			<PPKerberosSPNEGOToken>off</PPKerberosSPNEGOToken>
			<PPKerberosBstValueType>http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ</PPKerberosBstValueType>
			<PPSAMLUseWSSec>off</PPSAMLUseWSSec>
			<PPKerberosClientKeytab/>
			<PPUseWSSec>off</PPUseWSSec>
			<PPActorRoleID/>
			<PPTFIMTokenMapping>off</PPTFIMTokenMapping>
			<PPTFIMEndpoint/>
			<PPWSDerivedKeyUsernameToken>off</PPWSDerivedKeyUsernameToken>
			<PPWSDerivedKeyUsernameTokenIterations>1000</PPWSDerivedKeyUsernameTokenIterations>
			<PPWSUsernameTokenAllowReplacement>off</PPWSUsernameTokenAllowReplacement>
			<PPTFIMReplaceMethod>all</PPTFIMReplaceMethod>
			<PPTFIMRetrieveMode>CallTFIM</PPTFIMRetrieveMode>
			<PPHMACSigningAlg>hmac-sha1</PPHMACSigningAlg>
			<PPSigningHashAlg>sha1</PPSigningHashAlg>
			<PPWSTrustHeader>off</PPWSTrustHeader>
			<PPWSSCKeySource>random</PPWSSCKeySource>
			<PPSharedSecretKey/>
			<PPWSTrustRenewalWait>0</PPWSTrustRenewalWait>
			<PPWSTrustNewInstance>off</PPWSTrustNewInstance>
			<PPWSTrustNewKey>off</PPWSTrustNewKey>
			<PPWSTrustNeverExpire>off</PPWSTrustNeverExpire>
			<PPICRXToken>off</PPICRXToken>
			<PPICRXUserRealm/>
			<PPSAMLIdentityProvider>on</PPSAMLIdentityProvider>
			<PPSAMLProtocol>assertion</PPSAMLProtocol>
			<PPSAMLResponseDestination/>
			<PPResultWrapup>none</PPResultWrapup>
			<PPSAMLAssertionType>
				<authentication>off</authentication>
				<attribute>on</attribute>
				<authorization>off</authorization>
			</PPSAMLAssertionType>
			<PPSAMLSubjectConfirm>bearer</PPSAMLSubjectConfirm>
			<PPSAMLNameID>on</PPSAMLNameID>
			<PPSAMLNameIDFormat/>
			<PPSAMLRecipient/>
			<PPSAMLAudience/>
			<PPSAMLOmitNotBefore>off</PPSAMLOmitNotBefore>
			<PPOneTimeUse>off</PPOneTimeUse>
			<PPSAMLProxy>off</PPSAMLProxy>
			<PPSAMLProxyAudience/>
			<PPSAMLProxyCount>0</PPSAMLProxyCount>
			<PPSAMLAuthzAction>AllHTTP</PPSAMLAuthzAction>
			<PPSAMLAttributes class="SAMLAttributes">OpenAM-SAMLAttributes</PPSAMLAttributes>
			<PPLTPAInsertCookie>on</PPLTPAInsertCookie>
			<PPTAMPACPropagate>off</PPTAMPACPropagate>
			<PPTAMHeader>iv-creds</PPTAMHeader>
			<PPTAMHeaderSize>0</PPTAMHeaderSize>
		</PostProcess>
		<SAMLSigningHashAlg>sha1</SAMLSigningHashAlg>
		<SAMLSigningAlg>rsa</SAMLSigningAlg>
		<LDAPsuffix/>
		<LogAllowed>on</LogAllowed>
		<LogAllowedLevel>info</LogAllowedLevel>
		<LogRejected>on</LogRejected>
		<LogRejectedLevel>warn</LogRejectedLevel>
		<PingIdentityCompatibility>off</PingIdentityCompatibility>
		<DoSValve>1</DoSValve>
		<LDAPVersion>v2</LDAPVersion>
		<EnforceSOAPActor>on</EnforceSOAPActor>
		<WSSecActorRoleID/>
	</AAAPolicy>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_aaa_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>aaa</Type>
		<Input>INPUT</Input>
		<Output>samltoken</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<AAA class="AAAPolicy">SecurityTokenServiceAAA</AAA>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyRule name="SecurityTokenService_create_external_user_SAML_rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>request-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_setvar_0</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_aaa_0</Actions>
	</StylePolicyRule>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_conditional_0_refaction_call_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>call</Type>
		<Input>dpvar_1</Input>
		<Output>dpvar_2</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<Rule>SecurityTokenService_create_external_user_SAML_rule</Rule>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<SAMLAttributes name="SystemUser_SAMLAttributes" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<SAMLAttribute>
			<SourceType>static</SourceType>
			<Name>identType</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath/>
			<ValueData>SystemRessurs</ValueData>
			<SubValueData/>
			<FriendlyName/>
		</SAMLAttribute>
		<SAMLAttribute>
			<SourceType>static</SourceType>
			<Name>authenticationLevel</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath/>
			<ValueData>0</ValueData>
			<SubValueData/>
			<FriendlyName/>
		</SAMLAttribute>
		<SAMLAttribute>
			<SourceType>xpath</SourceType>
			<Name>consumerId</Name>
			<Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
			<XPath>//*[local-name()='Username']/text()</XPath>
			<ValueData/>
			<SubValueData>Username</SubValueData>
			<FriendlyName/>
		</SAMLAttribute>
	</SAMLAttributes>
	<AAAPolicy name="SecurityTokenService_SystemUser_AAA" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<ExtractIdentity>
			<EIBitmap>
				<http-basic-auth>off</http-basic-auth>
				<wssec-username>on</wssec-username>
				<wssec-derived-key>off</wssec-derived-key>
				<wssec-binary-token>off</wssec-binary-token>
				<ws-secure-conversation>off</ws-secure-conversation>
				<ws-trust>off</ws-trust>
				<kerberos>off</kerberos>
				<kerberos-spnego>off</kerberos-spnego>
				<client-ssl>off</client-ssl>
				<saml-attr-name>off</saml-attr-name>
				<saml-authen-name>off</saml-authen-name>
				<saml-artifact>off</saml-artifact>
				<client-ip-address>off</client-ip-address>
				<signer-dn>off</signer-dn>
				<token>off</token>
				<cookie-token>off</cookie-token>
				<ltpa>off</ltpa>
				<metadata>off</metadata>
				<custom>off</custom>
				<html-forms-auth>off</html-forms-auth>
				<oauth>off</oauth>
			</EIBitmap>
			<EICustomURL/>
			<EIXPath/>
			<EISignerDNValcred/>
			<EICookieName/>
			<EIBasicAuthRealm>login</EIBasicAuthRealm>
			<EIUseWSSec>off</EIUseWSSec>
			<EIMetadata/>
			<EIAllowRemoteTokenReference>off</EIAllowRemoteTokenReference>
			<EIRemoteTokenProcessService/>
			<EIPasswordRetrievalMechanism>xmlfile</EIPasswordRetrievalMechanism>
			<EIPasswordRetrievalCustomURL/>
			<EIPasswordRetrievalAAAInfoURL/>
			<EISSLProxyProfile/>
			<EIFormsLoginPolicy/>
			<EIOAuthClientGroup/>
		</ExtractIdentity>
		<Authenticate>
			<AUMethod>token</AUMethod>
			<AUCustomURL/>
			<AUMapURL/>
			<AUHost/>
			<AUPort/>
			<AUSSLValcred/>
			<AUCacheAllow>absolute</AUCacheAllow>
			<AUCacheTTL>3</AUCacheTTL>
			<AUKerberosPrincipal/>
			<AUKerberosPassword/>
			<AUClearTrustServerURL/>
			<AUClearTrustApplication/>
			<AUSAMLArtifactResponder/>
			<AUKerberosVerifySignature>on</AUKerberosVerifySignature>
			<AUNetegrityBaseURI/>
			<AUSAMLAuthQueryServer/>
			<AUSAMLVersion>1.1</AUSAMLVersion>
			<AULDAPPrefix>cn=</AULDAPPrefix>
			<AULDAPSuffix/>
			<AULDAPLoadBalanceGroup/>
			<AUKerberosKeytab/>
			<AUWSTrustURL/>
			<AUSAML2Issuer/>
			<AUSignerValcred/>
			<AUSignedXPath/>
			<AUSSLProxyProfile/>
			<AUNetegrityConfig/>
			<AULDAPBindDN/>
			<AULDAPBindPassword/>
			<AULDAPSearchAttribute>userPassword</AULDAPSearchAttribute>
			<AULTPATokenVersionsBitmap>
				<LTPA>off</LTPA>
				<LTPA2>on</LTPA2>
				<LTPADomino>off</LTPADomino>
			</AULTPATokenVersionsBitmap>
			<AULTPAKeyFile/>
			<AULTPAKeyFilePassword/>
			<AULTPAStashFile/>
			<AUBinaryTokenX509Valcred/>
			<AUTAMServer/>
			<AUAllowRemoteTokenReference>off</AUAllowRemoteTokenReference>
			<AURemoteTokenProcessService/>
			<AUWSTrustVersion>1.2</AUWSTrustVersion>
			<AULDAPSearchForDN>off</AULDAPSearchForDN>
			<AULDAPSearchParameters/>
			<AUWSTrustRequireClientEntropy>off</AUWSTrustRequireClientEntropy>
			<AUWSTrustClientEntropySize>32</AUWSTrustClientEntropySize>
			<AUWSTrustRequireServerEntropy>off</AUWSTrustRequireServerEntropy>
			<AUWSTrustServerEntropySize>32</AUWSTrustServerEntropySize>
			<AUWSTrustRequireRSTC>off</AUWSTrustRequireRSTC>
			<AUWSTrustRequireAppliesToHeader>off</AUWSTrustRequireAppliesToHeader>
			<AUWSTrustAppliesToHeader/>
			<AUWSTrustEncryptionCertificate/>
			<AUZOSNSSConfig/>
			<AULDAPAttributes/>
			<AUSkewTime>0</AUSkewTime>
			<AUTAMPACReturn>off</AUTAMPACReturn>
		</Authenticate>
		<MapCredentials>
			<MCMethod>none</MCMethod>
			<MCCustomURL/>
			<MCMapURL/>
			<MCMapXPath/>
			<MCTFIMEndpoint/>
		</MapCredentials>
		<ExtractResource>
			<ERBitmap>
				<target-url>on</target-url>
				<original-url>on</original-url>
				<request-uri>off</request-uri>
				<request-opname>on</request-opname>
				<http-method>off</http-method>
				<XPath>off</XPath>
				<metadata>off</metadata>
			</ERBitmap>
			<ERXPath/>
			<ERMetadata/>
		</ExtractResource>
		<MapResource>
			<MRMethod>none</MRMethod>
			<MRCustomURL/>
			<MRMapURL/>
			<MRMapXPath/>
			<MRTAMMap>WebSEAL</MRTAMMap>
			<MRTAMInstancePrefix/>
			<MRTAMWebSEALDynURLFile/>
		</MapResource>
		<Authorize>
			<AZMethod>anyauthenticated</AZMethod>
			<AZCustomURL/>
			<AZMapURL/>
			<AZHost/>
			<AZPort/>
			<AZLDAPGroup/>
			<AZValcred/>
			<AZSAMLURL/>
			<AZSAMLType>any</AZSAMLType>
			<AZSAMLXPath/>
			<AZSAMLNameQualifier/>
			<AZCacheAllow>absolute</AZCacheAllow>
			<AZCacheTTL>3</AZCacheTTL>
			<AZNetegrityBaseURI/>
			<AZNetegrityOpNameExtension/>
			<AZClearTrustServerURL/>
			<AZSAMLVersion>1.1</AZSAMLVersion>
			<AZLDAPLoadBalanceGroup/>
			<AZLDAPBindDN/>
			<AZLDAPBindPassword/>
			<AZLDAPGroupAttribute>member</AZLDAPGroupAttribute>
			<AZSSLProxyProfile/>
			<AZNetegrityConfig/>
			<AZLDAPSearchScope>subtree</AZLDAPSearchScope>
			<AZLDAPSearchFilter>(objectClass=*)</AZLDAPSearchFilter>
			<AZXACMLVersion>2.0</AZXACMLVersion>
			<AZXACMLPEPType>deny-biased</AZXACMLPEPType>
			<AZXACMLUseOnBoxPDP>on</AZXACMLUseOnBoxPDP>
			<AZXACMLPDP/>
			<AZXACMLExternalPDPUrl/>
			<AZXACMLBindingMethod>custom</AZXACMLBindingMethod>
			<AZXACMLBindingObject/>
			<AZXACMLBindingXSL/>
			<AZXACMLCustomObligation/>
			<AZXACMLUseSAML2>off</AZXACMLUseSAML2>
			<AZTAMServer/>
			<AZTAMDefaultAction>T</AZTAMDefaultAction>
			<AZTAMActionResourceMap/>
			<AZXACMLUseSOAP>off</AZXACMLUseSOAP>
			<AZZOSNSSConfig/>
			<AZSAFDefaultAction>r</AZSAFDefaultAction>
			<AZLDAPAttributes/>
			<AZSkewTime>0</AZSkewTime>
			<AZOAuthValidationEndpointType>tfim</AZOAuthValidationEndpointType>
			<AZTFIMEndpoint/>
			<AZOAuthEnforceScope>off</AZOAuthEnforceScope>
			<AZOAuthExportHeaders>on</AZOAuthExportHeaders>
			<AZTAMPACReturn>off</AZTAMPACReturn>
			<AZTAMPACUse>off</AZTAMPACUse>
		</Authorize>
		<PostProcess>
			<PPEnabled>off</PPEnabled>
			<PPCustomURL/>
			<PPSAMLAuthAssertion>off</PPSAMLAuthAssertion>
			<PPSAMLServerName>sts-datapower</PPSAMLServerName>
			<PPSAMLNameQualifier/>
			<PPKerberosTicket>off</PPKerberosTicket>
			<PPKerberosClient/>
			<PPKerberosClientPassword/>
			<PPKerberosServer/>
			<PPWSTrust>off</PPWSTrust>
			<PPTimestamp>on</PPTimestamp>
			<PPTimestampExpiry>0</PPTimestampExpiry>
			<PPAllowRenewal>off</PPAllowRenewal>
			<PPSAMLVersion>2.0</PPSAMLVersion>
			<PPSAMLSendSLO>off</PPSAMLSendSLO>
			<PPSAMLSLOEndpoint/>
			<PPSSLProxyProfile/>
			<PPWSUsernameToken>off</PPWSUsernameToken>
			<PPWSUsernameTokenPasswordType>Digest</PPWSUsernameTokenPasswordType>
			<PPSAMLValidity>3600</PPSAMLValidity>
			<PPSAMLSkew>0</PPSAMLSkew>
			<PPWSUsernameTokenIncludePwd>on</PPWSUsernameTokenIncludePwd>
			<PPLTPA>off</PPLTPA>
			<PPLTPAVersion>LTPA2</PPLTPAVersion>
			<PPLTPAExpiry>600</PPLTPAExpiry>
			<PPLTPAKeyFile/>
			<PPLTPAKeyFilePassword/>
			<PPLTPAStashFile/>
			<PPKerberosSPNEGOToken>off</PPKerberosSPNEGOToken>
			<PPKerberosBstValueType>http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ</PPKerberosBstValueType>
			<PPSAMLUseWSSec>off</PPSAMLUseWSSec>
			<PPKerberosClientKeytab/>
			<PPUseWSSec>off</PPUseWSSec>
			<PPActorRoleID/>
			<PPTFIMTokenMapping>off</PPTFIMTokenMapping>
			<PPTFIMEndpoint/>
			<PPWSDerivedKeyUsernameToken>off</PPWSDerivedKeyUsernameToken>
			<PPWSDerivedKeyUsernameTokenIterations>1000</PPWSDerivedKeyUsernameTokenIterations>
			<PPWSUsernameTokenAllowReplacement>off</PPWSUsernameTokenAllowReplacement>
			<PPTFIMReplaceMethod>all</PPTFIMReplaceMethod>
			<PPTFIMRetrieveMode>CallTFIM</PPTFIMRetrieveMode>
			<PPHMACSigningAlg>hmac-sha1</PPHMACSigningAlg>
			<PPSigningHashAlg>sha1</PPSigningHashAlg>
			<PPWSTrustHeader>off</PPWSTrustHeader>
			<PPWSSCKeySource>random</PPWSSCKeySource>
			<PPSharedSecretKey/>
			<PPWSTrustRenewalWait>0</PPWSTrustRenewalWait>
			<PPWSTrustNewInstance>off</PPWSTrustNewInstance>
			<PPWSTrustNewKey>off</PPWSTrustNewKey>
			<PPWSTrustNeverExpire>off</PPWSTrustNeverExpire>
			<PPICRXToken>off</PPICRXToken>
			<PPICRXUserRealm/>
			<PPSAMLIdentityProvider>on</PPSAMLIdentityProvider>
			<PPSAMLProtocol>assertion</PPSAMLProtocol>
			<PPSAMLResponseDestination/>
			<PPResultWrapup>none</PPResultWrapup>
			<PPSAMLAssertionType>
				<authentication>off</authentication>
				<attribute>on</attribute>
				<authorization>off</authorization>
			</PPSAMLAssertionType>
			<PPSAMLSubjectConfirm>bearer</PPSAMLSubjectConfirm>
			<PPSAMLNameID>on</PPSAMLNameID>
			<PPSAMLNameIDFormat/>
			<PPSAMLRecipient/>
			<PPSAMLAudience/>
			<PPSAMLOmitNotBefore>off</PPSAMLOmitNotBefore>
			<PPOneTimeUse>off</PPOneTimeUse>
			<PPSAMLProxy>off</PPSAMLProxy>
			<PPSAMLProxyAudience/>
			<PPSAMLProxyCount>0</PPSAMLProxyCount>
			<PPSAMLAuthzAction>AllHTTP</PPSAMLAuthzAction>
			<PPSAMLAttributes class="SAMLAttributes">SystemUser_SAMLAttributes</PPSAMLAttributes>
			<PPLTPAInsertCookie>on</PPLTPAInsertCookie>
			<PPTAMPACPropagate>off</PPTAMPACPropagate>
			<PPTAMHeader>HTTP_IV_CREDS</PPTAMHeader>
			<PPTAMHeaderSize>0</PPTAMHeaderSize>
		</PostProcess>
		<SAMLValcred class="CryptoValCred">sts_backside_CryptoValCred</SAMLValcred>
		<SAMLSigningHashAlg>sha1</SAMLSigningHashAlg>
		<SAMLSigningAlg>rsa</SAMLSigningAlg>
		<LDAPsuffix/>
		<LogAllowed>on</LogAllowed>
		<LogAllowedLevel>info</LogAllowedLevel>
		<LogRejected>on</LogRejected>
		<LogRejectedLevel>warn</LogRejectedLevel>
		<PingIdentityCompatibility>off</PingIdentityCompatibility>
		<DoSValve>1</DoSValve>
		<LDAPVersion>v2</LDAPVersion>
		<EnforceSOAPActor>on</EnforceSOAPActor>
		<WSSecActorRoleID/>
	</AAAPolicy>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_conditional_0_refaction_aaa_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>aaa</Type>
		<Input>dpvar_1</Input>
		<Output>samltoken</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<AAA class="AAAPolicy">SecurityTokenService_SystemUser_AAA</AAA>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyRule name="SecurityTokenService_systemuser_rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>request-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_conditional_0_refaction_aaa_0</Actions>
	</StylePolicyRule>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_conditional_0_refaction_call_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>call</Type>
		<Input>dpvar_1</Input>
		<Output>dpvar_2</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<Rule>SecurityTokenService_systemuser_rule</Rule>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_conditional_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>conditional</Type>
		<Input>dpvar_1</Input>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<Condition>
			<Expression>boolean(//*[local-name()='RequestSecurityToken']/*[local-name()='Claims'])</Expression>
			<ConditionAction>SecurityTokenService_default_request-rule_conditional_0_refaction_call_0</ConditionAction>
		</Condition>
		<Condition>
			<Expression>/*</Expression>
			<ConditionAction>SecurityTokenService_default_request-rule_conditional_0_refaction_call_1</ConditionAction>
		</Condition>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_log_0" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>log</Type>
		<Input>samltoken</Input>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<LogLevel>error</LogLevel>
		<LogType class="LogLabel">all</LogType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_sign_2" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>xform</Type>
		<Input>samltoken</Input>
		<Transform>store:///sign-enveloped.xsl</Transform>
		<Output>signedtoken</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<StylesheetParameters>
			<ParameterName>{http://www.datapower.com/param/config}XPath</ParameterName>
			<ParameterValue>//*[local-name()='Assertion']</ParameterValue>
		</StylesheetParameters>
		<StylesheetParameters>
			<ParameterName>{http://www.datapower.com/param/config}c14nalg</ParameterName>
			<ParameterValue>exc-c14n</ParameterValue>
		</StylesheetParameters>
		<StylesheetParameters>
			<ParameterName>{http://www.datapower.com/param/config}keypair-cert</ParameterName>
			<ParameterValue>${cfgHost}</ParameterValue>
		</StylesheetParameters>
		<StylesheetParameters>
			<ParameterName>{http://www.datapower.com/param/config}keypair-key</ParameterName>
			<ParameterValue>${cfgHost}</ParameterValue>
		</StylesheetParameters>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_xform_3" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>xform</Type>
		<Input>signedtoken</Input>
		<Transform>local:///xslt/rst-response.xsl</Transform>
		<Output>response</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<StylePolicyAction name="SecurityTokenService_default_request-rule_defaultaction_result" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>results</Type>
		<Input>response</Input>
		<Output>OUTPUT</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<WSStylePolicyRule name="SecurityTokenService_default_request-rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>request-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_aaa_1</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_conditional_0</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_log_0</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_sign_2</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_xform_3</Actions>
		<Actions class="StylePolicyAction">SecurityTokenService_default_request-rule_defaultaction_result</Actions>
	</WSStylePolicyRule>
	<Matching name="SecurityTokenService_match_all" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<MatchRules>
			<Type>url</Type>
			<HttpTag/>
			<HttpValue/>
			<Url>*</Url>
			<ErrorCode/>
			<XPATHExpression/>
			<Method>default</Method>
		</MatchRules>
		<MatchWithPCRE>off</MatchWithPCRE>
		<CombineWithOr>off</CombineWithOr>
	</Matching>
	<StylePolicyAction name="SecurityTokenService_default_response-rule_defaultaction_result" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>results</Type>
		<Input>INPUT</Input>
		<Output>OUTPUT</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<WSStylePolicyRule name="SecurityTokenService_default_response-rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>response-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_default_response-rule_defaultaction_result</Actions>
	</WSStylePolicyRule>
	<StylePolicyAction name="SecurityTokenService_error_rule_xform_2" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Type>xform</Type>
		<Input>INPUT</Input>
		<Transform>local:///xslt/error-template.xsl</Transform>
		<Output>OUTPUT</Output>
		<NamedInOutLocationType>default</NamedInOutLocationType>
		<OutputType>default</OutputType>
		<Transactional>off</Transactional>
		<SOAPValidation>body</SOAPValidation>
		<SQLSourceType>static</SQLSourceType>
		<Asynchronous>off</Asynchronous>
		<ResultsMode>first-available</ResultsMode>
		<RetryCount>0</RetryCount>
		<RetryInterval>1000</RetryInterval>
		<MultipleOutputs>off</MultipleOutputs>
		<IteratorType>XPATH</IteratorType>
		<Timeout>0</Timeout>
		<MethodRewriteType>GET</MethodRewriteType>
		<MethodType>POST</MethodType>
		<MethodType2>POST</MethodType2>
	</StylePolicyAction>
	<WSStylePolicyRule name="SecurityTokenService_error_rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Direction>error-rule</Direction>
		<InputFormat>none</InputFormat>
		<OutputFormat>none</OutputFormat>
		<NonXMLProcessing>off</NonXMLProcessing>
		<Unprocessed>off</Unprocessed>
		<Actions class="StylePolicyAction">SecurityTokenService_error_rule_xform_2</Actions>
	</WSStylePolicyRule>
	<WSStylePolicy name="SecurityTokenService" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<DefStylesheetForSoap>store:///filter-reject-all.xsl</DefStylesheetForSoap>
		<DefStylesheetForXsl>store:///identity.xsl</DefStylesheetForXsl>
		<PolicyMaps>
			<WSDLComponentType>fragmentid</WSDLComponentType>
			<WSDLComponentValue/>
			<Match class="Matching">action_negative_match</Match>
			<Rule class="WSStylePolicyRule">SecurityTokenService_action_negative_match_rule</Rule>
			<Subscription/>
			<WSDLFragmentID>http://www.datapower.com/fragment-id#dp.all()</WSDLFragmentID>
		</PolicyMaps>
		<PolicyMaps>
			<WSDLComponentType>fragmentid</WSDLComponentType>
			<WSDLComponentValue/>
			<Match class="Matching">Match-SAMLV2-OpenAMClaim</Match>
			<Rule class="WSStylePolicyRule">SecurityTokenService_default_request-rule</Rule>
			<Subscription/>
			<WSDLFragmentID>http://www.datapower.com/fragment-id#dp.all()</WSDLFragmentID>
		</PolicyMaps>
		<PolicyMaps>
			<WSDLComponentType>fragmentid</WSDLComponentType>
			<WSDLComponentValue/>
			<Match class="Matching">SecurityTokenService_match_all</Match>
			<Rule class="WSStylePolicyRule">SecurityTokenService_default_response-rule</Rule>
			<Subscription/>
			<WSDLFragmentID>http://www.datapower.com/fragment-id#dp.all()</WSDLFragmentID>
		</PolicyMaps>
		<PolicyMaps>
			<WSDLComponentType>fragmentid</WSDLComponentType>
			<WSDLComponentValue/>
			<Match class="Matching">SecurityTokenService_match_all</Match>
			<Rule class="WSStylePolicyRule">SecurityTokenService_error_rule</Rule>
			<Subscription/>
			<WSDLFragmentID>http://www.datapower.com/fragment-id#dp.all()</WSDLFragmentID>
		</PolicyMaps>
	</WSStylePolicy>
	<PolicyAttachments name="SecurityTokenService_ws-trust-1.4-service.wsdl" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<EnforcementMode>enforce</EnforcementMode>
		<PolicyReferences>on</PolicyReferences>
		<SLAEnforcementMode>allow-if-no-sla</SLAEnforcementMode>
	</PolicyAttachments>
	<WSGateway name="SecurityTokenService" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
		<mAdminState>enabled</mAdminState>
		<Priority>normal</Priority>
		<XMLManager class="XMLManager">default-attempt-stream</XMLManager>
		<DefaultParamNamespace>http://www.datapower.com/param/config</DefaultParamNamespace>
		<QueryParamNamespace>http://www.datapower.com/param/query</QueryParamNamespace>
		<PropagateURI>off</PropagateURI>
		<MonitorProcessingPolicy>terminate-at-first-throttle</MonitorProcessingPolicy>
		<RequestAttachments>strip</RequestAttachments>
		<ResponseAttachments>strip</ResponseAttachments>
		<RootPartNotFirstAction>process-in-order</RootPartNotFirstAction>
		<FrontAttachmentFormat>dynamic</FrontAttachmentFormat>
		<BackAttachmentFormat>dynamic</BackAttachmentFormat>
		<MIMEFrontHeaders>on</MIMEFrontHeaders>
		<MIMEBackHeaders>on</MIMEBackHeaders>
		<StreamOutputToBack>buffer-until-verification</StreamOutputToBack>
		<StreamOutputToFront>buffer-until-verification</StreamOutputToFront>
		<MaxMessageSize>0</MaxMessageSize>
		<GatewayParserLimits>off</GatewayParserLimits>
		<ParserLimitsElementDepth>512</ParserLimitsElementDepth>
		<ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
		<ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
		<ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
		<ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
		<ParserLimitsMaxPrefixes>0</ParserLimitsMaxPrefixes>
		<ParserLimitsMaxNamespaces>0</ParserLimitsMaxNamespaces>
		<ParserLimitsMaxLocalNames>0</ParserLimitsMaxLocalNames>
		<ParserLimitsAttachmentByteCount>2000000000</ParserLimitsAttachmentByteCount>
		<ParserLimitsAttachmentPackageByteCount>0</ParserLimitsAttachmentPackageByteCount>
		<DebugMode persisted="false">on</DebugMode>
		<DebuggerType>internal</DebuggerType>
		<DebugHistory>25</DebugHistory>
		<FlowControl>off</FlowControl>
		<SOAPSchemaURL>store:///schemas/soap-envelope.xsd</SOAPSchemaURL>
		<FrontTimeout>120</FrontTimeout>
		<BackTimeout>120</BackTimeout>
		<FrontPersistentTimeout>180</FrontPersistentTimeout>
		<BackPersistentTimeout>180</BackPersistentTimeout>
		<IncludeResponseTypeEncoding>off</IncludeResponseTypeEncoding>
		<BackHTTPVersion>HTTP/1.1</BackHTTPVersion>
		<PersistentConnections>on</PersistentConnections>
		<LoopDetection>off</LoopDetection>
		<DoHostRewriting>on</DoHostRewriting>
		<DoChunkedUpload>off</DoChunkedUpload>
		<ProcessHTTPErrors>on</ProcessHTTPErrors>
		<HTTPClientIPLabel>X-Client-IP</HTTPClientIPLabel>
		<InOrderMode>
			<Request>off</Request>
			<Backend>off</Backend>
			<Response>off</Response>
		</InOrderMode>
		<WSAMode>sync2sync</WSAMode>
		<WSARequireAAA>on</WSARequireAAA>
		<WSAStrip>on</WSAStrip>
		<WSADefaultReplyTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultReplyTo>
		<WSADefaultFaultTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultFaultTo>
		<WSAForce>off</WSAForce>
		<WSAGenStyle>sync</WSAGenStyle>
		<WSAHTTPAsyncResponseCode>204</WSAHTTPAsyncResponseCode>
		<WSATimeout>120</WSATimeout>
		<WSRMEnabled>off</WSRMEnabled>
		<WSRMSequenceExpiration>3600</WSRMSequenceExpiration>
		<WSRMDestinationAcceptCreateSequence>on</WSRMDestinationAcceptCreateSequence>
		<WSRMDestinationMaximumSequences>400</WSRMDestinationMaximumSequences>
		<WSRMDestinationInOrder>off</WSRMDestinationInOrder>
		<WSRMDestinationMaximumInOrderQueueLength>10</WSRMDestinationMaximumInOrderQueueLength>
		<WSRMDestinationAcceptOffers>off</WSRMDestinationAcceptOffers>
		<WSRMFrontForce>off</WSRMFrontForce>
		<WSRMBackForce>off</WSRMBackForce>
		<WSRMBackCreateSequence>off</WSRMBackCreateSequence>
		<WSRMFrontCreateSequence>off</WSRMFrontCreateSequence>
		<WSRMSourceMakeOffer>off</WSRMSourceMakeOffer>
		<WSRMUsesSequenceSSL>off</WSRMUsesSequenceSSL>
		<WSRMSourceMaximumSequences>400</WSRMSourceMaximumSequences>
		<WSRMSourceRetransmissionInterval>10</WSRMSourceRetransmissionInterval>
		<WSRMSourceExponentialBackoff>on</WSRMSourceExponentialBackoff>
		<WSRMSourceMaximumRetransmissions>4</WSRMSourceMaximumRetransmissions>
		<WSRMSourceMaximumQueueLength>30</WSRMSourceMaximumQueueLength>
		<WSRMSourceRequestAckCount>1</WSRMSourceRequestAckCount>
		<WSRMSourceInactivityClose>360</WSRMSourceInactivityClose>
		<ForcePolicyExec>off</ForcePolicyExec>
		<RewriteErrors>on</RewriteErrors>
		<DelayErrors>on</DelayErrors>
		<DelayErrorsDuration>1000</DelayErrorsDuration>
		<RequestType>soap</RequestType>
		<ResponseType>soap</ResponseType>
		<FollowRedirects>on</FollowRedirects>
		<AllowCompression>off</AllowCompression>
		<AllowCacheControlHeader>off</AllowCacheControlHeader>
		<Type>static-from-wsdl</Type>
		<AutoCreateSources>off</AutoCreateSources>
		<EndpointRewritePolicy class="WSEndpointRewritePolicy">SecurityTokenService</EndpointRewritePolicy>
		<StylePolicy class="WSStylePolicy">SecurityTokenService</StylePolicy>
		<RemoteFetchRetry>
			<AutomaticRetry>off</AutomaticRetry>
			<RetryInterval>1</RetryInterval>
			<ReportingInterval>1</ReportingInterval>
			<TotalRetries>1</TotalRetries>
		</RemoteFetchRetry>
		<BaseWSDL>
			<WSDLSourceLocation>local:///wsdl/ws-trust-1.4-service.wsdl</WSDLSourceLocation>
			<WSDLName>ws-trust-1.4-service.wsdl</WSDLName>
			<PolicyAttachments class="PolicyAttachments">SecurityTokenService_ws-trust-1.4-service.wsdl</PolicyAttachments>
		</BaseWSDL>
		<UserToggles>
			<WSDLName/>
			<ServiceName/>
			<ServicePortName/>
			<PortTypeName/>
			<BindingName/>
			<OperationName/>
			<Toggles>
				<Enable>on</Enable>
				<Publish>on</Publish>
				<VerifyFaults>on</VerifyFaults>
				<VerifyHeaders>off</VerifyHeaders>
				<NoRequestValidation>off</NoRequestValidation>
				<NoResponseValidation>on</NoResponseValidation>
				<SuppressFaultsElementsForRPCWrappers>off</SuppressFaultsElementsForRPCWrappers>
				<NoWSA>off</NoWSA>
				<NoWSRM>off</NoWSRM>
				<AllowXOPInclude>on</AllowXOPInclude>
			</Toggles>
			<Subscription/>
			<UseFragmentID>on</UseFragmentID>
			<FragmentID>http://docs.oasis-open.org/ws-sx/ws-trust/200512/wsdl#dp.wsdlName(ws-trust-1.4-service.wsdl)</FragmentID>
		</UserToggles>
		<EncryptedKeySHA1CacheLifeTime>0</EncryptedKeySHA1CacheLifeTime>
		<PreserveKeyChain>off</PreserveKeyChain>
		<DecryptWithKeyFromED>off</DecryptWithKeyFromED>
		<SOAPActionPolicy>lax</SOAPActionPolicy>
		<WSMAgentMonitor>on</WSMAgentMonitor>
	</WSGateway>
</#macro>