<#macro StylePolicyActionAntiVirusScan name webwasher icap_server icap_port icap_uri>
    <StylePolicyAction name="${name}" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>antivirus</Type>
        <Input>PIPE</Input>
        <Transform>${webwasher}</Transform>
        <Output>PIPE</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}AntiVirusProcessingMode</ParameterName>
            <ParameterValue>attachments</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}ICAPHostType</ParameterName>
            <ParameterValue>custom</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}ICAPRemoteHost</ParameterName>
            <ParameterValue>${icap_server}</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}ICAPRemotePort</ParameterName>
            <ParameterValue>${icap_port}</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}ICAPRemoteURI</ParameterName>
            <ParameterValue>${icap_uri}</ParameterValue>
        </StylesheetParameters>
		<StylesheetParameters>
			<ParameterName>{http://www.datapower.com/param/config}virus-header</ParameterName>
			<ParameterValue>X-Virus-Name</ParameterValue>
		</StylesheetParameters>
		<OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
</#macro>