<#macro SAMLProxy cfgHost port>
    <HTTPSSourceProtocolHandler name="SAMLProxy_FrontSideHandler" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <LocalAddress>${cfgHost}</LocalAddress>
        <LocalPort>${port}</LocalPort>
        <HTTPVersion>HTTP/1.1</HTTPVersion>
        <AllowedFeatures>
            <HTTP-1.0>on</HTTP-1.0>
            <HTTP-1.1>on</HTTP-1.1>
            <POST>on</POST>
            <GET>off</GET>
            <PUT>on</PUT>
            <HEAD>off</HEAD>
            <OPTIONS>off</OPTIONS>
            <TRACE>off</TRACE>
            <DELETE>off</DELETE>
            <CONNECT>off</CONNECT>
            <QueryString>on</QueryString>
            <FragmentIdentifiers>on</FragmentIdentifiers>
            <DotDot>off</DotDot>
            <CmdExe>off</CmdExe>
        </AllowedFeatures>
        <PersistentConnections>on</PersistentConnections>
        <AllowCompression>off</AllowCompression>
        <MaxURLLen>16384</MaxURLLen>
        <MaxTotalHdrLen>128000</MaxTotalHdrLen>
        <MaxHdrCount>0</MaxHdrCount>
        <MaxNameHdrLen>0</MaxNameHdrLen>
        <MaxValueHdrLen>0</MaxValueHdrLen>
        <MaxQueryStringLen>0</MaxQueryStringLen>
        <SSLProxy class="SSLProxyProfile">${cfgHost}_SSLProxyProfile</SSLProxy>
        <CredentialCharset>protocol</CredentialCharset>
    </HTTPSSourceProtocolHandler>
    <SSLProxyProfile name="SAMLValidation_SSLProxyProfile" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>forward</Direction>
        <ForwardCryptoProfile class="CryptoProfile">backside_SSLCryptoProfile</ForwardCryptoProfile>
        <ServerCaching>on</ServerCaching>
        <SessionTimeout>300</SessionTimeout>
        <CacheSize>20</CacheSize>
        <ClientCache>on</ClientCache>
        <ClientAuthOptional>off</ClientAuthOptional>
        <ClientAuthAlwaysRequest>off</ClientAuthAlwaysRequest>
        <PermitInsecureServers>on</PermitInsecureServers>
    </SSLProxyProfile>
    <Matching name="unt_match" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <MatchRules>
            <Type>xpath</Type>
            <HttpTag/>
            <HttpValue/>
            <Url/>
            <ErrorCode/>
            <XPATHExpression>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='UsernameToken']</XPATHExpression>
            <Method>default</Method>
        </MatchRules>
        <MatchWithPCRE>off</MatchWithPCRE>
        <CombineWithOr>off</CombineWithOr>
    </Matching>
    <StylePolicyAction name="xform_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>local:///xslt/extract-wsaddresing-info-with-wsaTo.xsl</Transform>
        <Output>NULL</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <SAMLAttributes name="SAML_Attributes_Definition" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <SAMLAttribute>
            <SourceType>static</SourceType>
            <Name>authenticationLevel</Name>
            <Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
            <XPath/>
            <ValueData>11</ValueData>
            <SubValueData/>
            <FriendlyName>authenticationLevel</FriendlyName>
        </SAMLAttribute>
        <SAMLAttribute>
            <SourceType>static</SourceType>
            <Name>identType</Name>
            <Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
            <XPath/>
            <ValueData>external</ValueData>
            <SubValueData/>
            <FriendlyName>identType</FriendlyName>
        </SAMLAttribute>
        <SAMLAttribute>
            <SourceType>static</SourceType>
            <Name>consumerId</Name>
            <Format>urn:oasis:names:tc:SAML:2.0:attrname-format:uri</Format>
            <XPath/>
            <ValueData>virgo</ValueData>
            <SubValueData/>
            <FriendlyName>consumerId</FriendlyName>
        </SAMLAttribute>
    </SAMLAttributes>
    <AAAPolicy name="AAA_Policy" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <NamespaceMapping>
            <Prefix>wsse</Prefix>
            <URI>http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd</URI>
        </NamespaceMapping>
        <ExtractIdentity>
            <EIBitmap>
                <http-basic-auth>off</http-basic-auth>
                <wssec-username>on</wssec-username>
                <wssec-derived-key>off</wssec-derived-key>
                <wssec-binary-token>off</wssec-binary-token>
                <ws-secure-conversation>off</ws-secure-conversation>
                <ws-trust>off</ws-trust>
                <kerberos>off</kerberos>
                <kerberos-spnego>off</kerberos-spnego>
                <client-ssl>off</client-ssl>
                <saml-attr-name>off</saml-attr-name>
                <saml-authen-name>off</saml-authen-name>
                <saml-artifact>off</saml-artifact>
                <client-ip-address>off</client-ip-address>
                <signer-dn>off</signer-dn>
                <token>off</token>
                <cookie-token>off</cookie-token>
                <ltpa>off</ltpa>
                <metadata>off</metadata>
                <custom>off</custom>
                <html-forms-auth>off</html-forms-auth>
                <oauth>off</oauth>
            </EIBitmap>
            <EICustomURL/>
            <EIXPath/>
            <EISignerDNValcred/>
            <EICookieName/>
            <EIBasicAuthRealm>login</EIBasicAuthRealm>
            <EIUseWSSec>off</EIUseWSSec>
            <EIMetadata/>
            <EIAllowRemoteTokenReference>off</EIAllowRemoteTokenReference>
            <EIRemoteTokenProcessService/>
            <EIPasswordRetrievalMechanism>xmlfile</EIPasswordRetrievalMechanism>
            <EIPasswordRetrievalCustomURL/>
            <EIPasswordRetrievalAAAInfoURL/>
            <EISSLProxyProfile/>
            <EIFormsLoginPolicy/>
            <EIOAuthClientGroup/>
        </ExtractIdentity>
        <Authenticate>
            <AUMethod>token</AUMethod>
            <AUCustomURL/>
            <AUMapURL/>
            <AUHost/>
            <AUPort/>
            <AUSSLValcred/>
            <AUCacheAllow>absolute</AUCacheAllow>
            <AUCacheTTL>3</AUCacheTTL>
            <AUKerberosPrincipal/>
            <AUKerberosPassword/>
            <AUClearTrustServerURL/>
            <AUClearTrustApplication/>
            <AUSAMLArtifactResponder/>
            <AUKerberosVerifySignature>on</AUKerberosVerifySignature>
            <AUNetegrityBaseURI/>
            <AUSAMLAuthQueryServer/>
            <AUSAMLVersion>1.1</AUSAMLVersion>
            <AULDAPPrefix>cn=</AULDAPPrefix>
            <AULDAPSuffix/>
            <AULDAPLoadBalanceGroup/>
            <AUKerberosKeytab/>
            <AUWSTrustURL/>
            <AUSAML2Issuer/>
            <AUSignerValcred/>
            <AUSignedXPath/>
            <AUSSLProxyProfile/>
            <AUNetegrityConfig/>
            <AULDAPBindDN/>
            <AULDAPBindPassword/>
            <AULDAPSearchAttribute>userPassword</AULDAPSearchAttribute>
            <AULTPATokenVersionsBitmap>
                <LTPA>off</LTPA>
                <LTPA2>on</LTPA2>
                <LTPADomino>off</LTPADomino>
            </AULTPATokenVersionsBitmap>
            <AULTPAKeyFile/>
            <AULTPAKeyFilePassword/>
            <AULTPAStashFile/>
            <AUBinaryTokenX509Valcred/>
            <AUTAMServer/>
            <AUAllowRemoteTokenReference>off</AUAllowRemoteTokenReference>
            <AURemoteTokenProcessService/>
            <AUWSTrustVersion>1.2</AUWSTrustVersion>
            <AULDAPSearchForDN>off</AULDAPSearchForDN>
            <AULDAPSearchParameters/>
            <AUWSTrustRequireClientEntropy>off</AUWSTrustRequireClientEntropy>
            <AUWSTrustClientEntropySize>32</AUWSTrustClientEntropySize>
            <AUWSTrustRequireServerEntropy>off</AUWSTrustRequireServerEntropy>
            <AUWSTrustServerEntropySize>32</AUWSTrustServerEntropySize>
            <AUWSTrustRequireRSTC>off</AUWSTrustRequireRSTC>
            <AUWSTrustRequireAppliesToHeader>off</AUWSTrustRequireAppliesToHeader>
            <AUWSTrustAppliesToHeader/>
            <AUWSTrustEncryptionCertificate/>
            <AUZOSNSSConfig/>
            <AULDAPAttributes/>
            <AUSkewTime>0</AUSkewTime>
            <AUTAMPACReturn>off</AUTAMPACReturn>
        </Authenticate>
        <MapCredentials>
            <MCMethod>none</MCMethod>
            <MCCustomURL/>
            <MCMapURL/>
            <MCMapXPath/>
            <MCTFIMEndpoint/>
        </MapCredentials>
        <ExtractResource>
            <ERBitmap>
                <target-url>off</target-url>
                <original-url>off</original-url>
                <request-uri>off</request-uri>
                <request-opname>off</request-opname>
                <http-method>on</http-method>
                <XPath>off</XPath>
                <metadata>off</metadata>
            </ERBitmap>
            <ERXPath/>
            <ERMetadata/>
        </ExtractResource>
        <MapResource>
            <MRMethod>none</MRMethod>
            <MRCustomURL/>
            <MRMapURL/>
            <MRMapXPath/>
            <MRTAMMap>WebSEAL</MRTAMMap>
            <MRTAMInstancePrefix/>
            <MRTAMWebSEALDynURLFile/>
        </MapResource>
        <Authorize>
            <AZMethod>passthrough</AZMethod>
            <AZCustomURL/>
            <AZMapURL/>
            <AZHost/>
            <AZPort/>
            <AZLDAPGroup/>
            <AZValcred/>
            <AZSAMLURL/>
            <AZSAMLType>any</AZSAMLType>
            <AZSAMLXPath/>
            <AZSAMLNameQualifier/>
            <AZCacheAllow>absolute</AZCacheAllow>
            <AZCacheTTL>3</AZCacheTTL>
            <AZNetegrityBaseURI/>
            <AZNetegrityOpNameExtension/>
            <AZClearTrustServerURL/>
            <AZSAMLVersion>1.1</AZSAMLVersion>
            <AZLDAPLoadBalanceGroup/>
            <AZLDAPBindDN/>
            <AZLDAPBindPassword/>
            <AZLDAPGroupAttribute>member</AZLDAPGroupAttribute>
            <AZSSLProxyProfile/>
            <AZNetegrityConfig/>
            <AZLDAPSearchScope>subtree</AZLDAPSearchScope>
            <AZLDAPSearchFilter>(objectClass=*)</AZLDAPSearchFilter>
            <AZXACMLVersion>2.0</AZXACMLVersion>
            <AZXACMLPEPType>deny-biased</AZXACMLPEPType>
            <AZXACMLUseOnBoxPDP>on</AZXACMLUseOnBoxPDP>
            <AZXACMLPDP/>
            <AZXACMLExternalPDPUrl/>
            <AZXACMLBindingMethod>custom</AZXACMLBindingMethod>
            <AZXACMLBindingObject/>
            <AZXACMLBindingXSL/>
            <AZXACMLCustomObligation/>
            <AZXACMLUseSAML2>off</AZXACMLUseSAML2>
            <AZTAMServer/>
            <AZTAMDefaultAction>T</AZTAMDefaultAction>
            <AZTAMActionResourceMap/>
            <AZXACMLUseSOAP>off</AZXACMLUseSOAP>
            <AZZOSNSSConfig/>
            <AZSAFDefaultAction>r</AZSAFDefaultAction>
            <AZLDAPAttributes/>
            <AZSkewTime>0</AZSkewTime>
            <AZOAuthValidationEndpointType>tfim</AZOAuthValidationEndpointType>
            <AZTFIMEndpoint/>
            <AZOAuthEnforceScope>off</AZOAuthEnforceScope>
            <AZOAuthExportHeaders>on</AZOAuthExportHeaders>
            <AZTAMPACReturn>off</AZTAMPACReturn>
            <AZTAMPACUse>off</AZTAMPACUse>
        </Authorize>
        <PostProcess>
            <PPEnabled>off</PPEnabled>
            <PPCustomURL/>
            <PPSAMLAuthAssertion>off</PPSAMLAuthAssertion>
            <PPSAMLServerName>virgo</PPSAMLServerName>
            <PPSAMLNameQualifier>www.nav.no</PPSAMLNameQualifier>
            <PPKerberosTicket>off</PPKerberosTicket>
            <PPKerberosClient/>
            <PPKerberosClientPassword/>
            <PPKerberosServer/>
            <PPWSTrust>off</PPWSTrust>
            <PPTimestamp>on</PPTimestamp>
            <PPTimestampExpiry>0</PPTimestampExpiry>
            <PPAllowRenewal>off</PPAllowRenewal>
            <PPSAMLVersion>2.0</PPSAMLVersion>
            <PPSAMLSendSLO>off</PPSAMLSendSLO>
            <PPSAMLSLOEndpoint/>
            <PPSSLProxyProfile/>
            <PPWSUsernameToken>off</PPWSUsernameToken>
            <PPWSUsernameTokenPasswordType>Digest</PPWSUsernameTokenPasswordType>
            <PPSAMLValidity>1000</PPSAMLValidity>
            <PPSAMLSkew>0</PPSAMLSkew>
            <PPWSUsernameTokenIncludePwd>on</PPWSUsernameTokenIncludePwd>
            <PPLTPA>off</PPLTPA>
            <PPLTPAVersion>LTPA2</PPLTPAVersion>
            <PPLTPAExpiry>600</PPLTPAExpiry>
            <PPLTPAKeyFile/>
            <PPLTPAKeyFilePassword/>
            <PPLTPAStashFile/>
            <PPKerberosSPNEGOToken>off</PPKerberosSPNEGOToken>
            <PPKerberosBstValueType>http://docs.oasis-open.org/wss/oasis-wss-kerberos-token-profile-1.1#GSS_Kerberosv5_AP_REQ</PPKerberosBstValueType>
            <PPSAMLUseWSSec>off</PPSAMLUseWSSec>
            <PPKerberosClientKeytab/>
            <PPUseWSSec>off</PPUseWSSec>
            <PPActorRoleID/>
            <PPTFIMTokenMapping>off</PPTFIMTokenMapping>
            <PPTFIMEndpoint/>
            <PPWSDerivedKeyUsernameToken>off</PPWSDerivedKeyUsernameToken>
            <PPWSDerivedKeyUsernameTokenIterations>1000</PPWSDerivedKeyUsernameTokenIterations>
            <PPWSUsernameTokenAllowReplacement>off</PPWSUsernameTokenAllowReplacement>
            <PPTFIMReplaceMethod>all</PPTFIMReplaceMethod>
            <PPTFIMRetrieveMode>CallTFIM</PPTFIMRetrieveMode>
            <PPHMACSigningAlg>hmac-sha1</PPHMACSigningAlg>
            <PPSigningHashAlg>sha1</PPSigningHashAlg>
            <PPWSTrustHeader>off</PPWSTrustHeader>
            <PPWSSCKeySource>random</PPWSSCKeySource>
            <PPSharedSecretKey/>
            <PPWSTrustRenewalWait>0</PPWSTrustRenewalWait>
            <PPWSTrustNewInstance>off</PPWSTrustNewInstance>
            <PPWSTrustNewKey>off</PPWSTrustNewKey>
            <PPWSTrustNeverExpire>off</PPWSTrustNeverExpire>
            <PPICRXToken>off</PPICRXToken>
            <PPICRXUserRealm/>
            <PPSAMLIdentityProvider>on</PPSAMLIdentityProvider>
            <PPSAMLProtocol>assertion</PPSAMLProtocol>
            <PPSAMLResponseDestination/>
            <PPResultWrapup>wssec-new</PPResultWrapup>
            <PPSAMLAssertionType>
                <authentication>off</authentication>
                <attribute>on</attribute>
                <authorization>off</authorization>
            </PPSAMLAssertionType>
            <PPSAMLSubjectConfirm>bearer</PPSAMLSubjectConfirm>
            <PPSAMLNameID>on</PPSAMLNameID>
            <PPSAMLNameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</PPSAMLNameIDFormat>
            <PPSAMLRecipient/>
            <PPSAMLAudience/>
            <PPSAMLOmitNotBefore>off</PPSAMLOmitNotBefore>
            <PPOneTimeUse>off</PPOneTimeUse>
            <PPSAMLProxy>off</PPSAMLProxy>
            <PPSAMLProxyAudience/>
            <PPSAMLProxyCount>0</PPSAMLProxyCount>
            <PPSAMLAuthzAction>AllHTTP</PPSAMLAuthzAction>
            <PPSAMLAttributes class="SAMLAttributes">SAML_Attributes_Definition</PPSAMLAttributes>
            <PPLTPAInsertCookie>on</PPLTPAInsertCookie>
            <PPTAMPACPropagate>off</PPTAMPACPropagate>
            <PPTAMHeader>HTTP_IV_CREDS</PPTAMHeader>
            <PPTAMHeaderSize>0</PPTAMHeaderSize>
        </PostProcess>
        <SAMLSigningHashAlg>sha1</SAMLSigningHashAlg>
        <SAMLSigningAlg>rsa</SAMLSigningAlg>
        <LDAPsuffix/>
        <LogAllowed>on</LogAllowed>
        <LogAllowedLevel>info</LogAllowedLevel>
        <LogRejected>on</LogRejected>
        <LogRejectedLevel>warn</LogRejectedLevel>
        <PingIdentityCompatibility>off</PingIdentityCompatibility>
        <DoSValve>1</DoSValve>
        <LDAPVersion>v2</LDAPVersion>
        <EnforceSOAPActor>on</EnforceSOAPActor>
        <WSSecActorRoleID/>
    </AAAPolicy>
    <StylePolicyAction name="AAA_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>aaa</Type>
        <Input>INPUT</Input>
        <Output>PIPE</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <AAA class="AAAPolicy">AAA_Policy</AAA>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="sign_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>PIPE</Input>
        <Transform>store:///sign-enveloped.xsl</Transform>
        <Output>dpvar_3</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}XPath</ParameterName>
            <ParameterValue>//*[namespace-uri()='urn:oasis:names:tc:SAML:2.0:assertion' and local-name()='Assertion']</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}c14nalg</ParameterName>
            <ParameterValue>exc-c14n</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}keypair-cert</ParameterName>
            <ParameterValue>${cfgHost}</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}keypair-key</ParameterName>
            <ParameterValue>${cfgHost}</ParameterValue>
        </StylesheetParameters>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="route-action_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>route-action</Type>
        <Input>dpvar_3</Input>
        <Transform>local:///xslt/wsaTo-route-to-endpoint.xsl</Transform>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="results-output_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>dpvar_3</Input>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyRule name="request-rule_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>request-rule</Direction>
        <InputFormat>none</InputFormat>
        <OutputFormat>none</OutputFormat>
        <NonXMLProcessing>off</NonXMLProcessing>
        <Unprocessed>off</Unprocessed>
        <Actions class="StylePolicyAction">xform_PolicyAction</Actions>
        <Actions class="StylePolicyAction">AAA_PolicyAction</Actions>
        <Actions class="StylePolicyAction">sign_1_PolicyAction</Actions>
        <Actions class="StylePolicyAction">route-action_1_PolicyAction</Actions>
        <Actions class="StylePolicyAction">results-output_1_PolicyAction</Actions>
    </StylePolicyRule>
    <Matching name="unsigned_MatchingRule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <MatchRules>
            <Type>xpath</Type>
            <HttpTag/>
            <HttpValue/>
            <Url/>
            <ErrorCode/>
            <XPATHExpression>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Header']/*[namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd' and local-name()='Security']/*[namespace-uri()='urn:oasis:names:tc:SAML:2.0:assertion' and local-name()='Assertion']</XPATHExpression>
            <Method>default</Method>
        </MatchRules>
        <MatchWithPCRE>off</MatchWithPCRE>
        <CombineWithOr>off</CombineWithOr>
    </Matching>

    <StylePolicyAction name="sign_2_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>store:///sign-enveloped.xsl</Transform>
        <Output>dpvar_4</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}XPath</ParameterName>
            <ParameterValue>//*[namespace-uri()='urn:oasis:names:tc:SAML:2.0:assertion' and local-name()='Assertion']</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}c14nalg</ParameterName>
            <ParameterValue>exc-c14n</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}keypair-cert</ParameterName>
            <ParameterValue>${cfgHost}</ParameterValue>
        </StylesheetParameters>
        <StylesheetParameters>
            <ParameterName>{http://www.datapower.com/param/config}keypair-key</ParameterName>
            <ParameterValue>${cfgHost}</ParameterValue>
        </StylesheetParameters>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="route-action_2_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>route-action</Type>
        <Input>dpvar_4</Input>
        <Transform>local:///xslt/wsaTo-route-to-endpoint.xsl</Transform>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="results_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>dpvar_4</Input>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyRule name="request-rule_PolicyRule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>request-rule</Direction>
        <InputFormat>none</InputFormat>
        <OutputFormat>none</OutputFormat>
        <NonXMLProcessing>off</NonXMLProcessing>
        <Unprocessed>off</Unprocessed>
        <Actions class="StylePolicyAction">xform_PolicyAction</Actions>
        <Actions class="StylePolicyAction">sign_2_PolicyAction</Actions>
        <Actions class="StylePolicyAction">route-action_2_PolicyAction</Actions>
        <Actions class="StylePolicyAction">results_1_PolicyAction</Actions>
    </StylePolicyRule>
    <Matching name="ServiceGateway_match_allSoapFaults" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <MatchRules>
            <Type>xpath</Type>
            <HttpTag/>
            <HttpValue/>
            <Url/>
            <ErrorCode/>
            <XPATHExpression>/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Envelope']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Body']/*[namespace-uri()='http://schemas.xmlsoap.org/soap/envelope/' and local-name()='Fault']</XPATHExpression>
            <Method>default</Method>
        </MatchRules>
        <MatchWithPCRE>off</MatchWithPCRE>
        <CombineWithOr>off</CombineWithOr>
    </Matching>
    <StylePolicyAction name="fault-response_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>local:///xslt/fault-category-logging.xsl</Transform>
        <Output>NULL</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="fault-response_2_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>local:///xslt/nfs-logger.xsl</Transform>
        <Output>log</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="fault-response-conditional_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>log</Input>
        <Output>NULL</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <Destination>var://context/log/destination</Destination>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>on</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="fault-response-conditional_2_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>conditional</Type>
        <Input>INPUT</Input>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <Condition>
            <Expression>//remote-log[normalize-space(.)='true']</Expression>
            <ConditionAction>fault-response-conditional_1_PolicyAction</ConditionAction>
        </Condition>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="fault-response-results_1_PolicyAction" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>INPUT</Input>
        <Output>OUTPUT</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyRule name="fault-response_PolicyRule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>response-rule</Direction>
        <InputFormat>none</InputFormat>
        <OutputFormat>none</OutputFormat>
        <NonXMLProcessing>off</NonXMLProcessing>
        <Unprocessed>off</Unprocessed>
        <Actions class="StylePolicyAction">fault-response_1_PolicyAction</Actions>
        <Actions class="StylePolicyAction">fault-response_2_PolicyAction</Actions>
        <Actions class="StylePolicyAction">fault-response-conditional_2_PolicyAction</Actions>
        <Actions class="StylePolicyAction">fault-response-results_1_PolicyAction</Actions>
    </StylePolicyRule>
    <Matching name="ServiceGateway_match_all" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <MatchRules>
            <Type>url</Type>
            <HttpTag/>
            <HttpValue/>
            <Url>*</Url>
            <ErrorCode/>
            <XPATHExpression/>
            <Method>default</Method>
        </MatchRules>
        <MatchWithPCRE>off</MatchWithPCRE>
        <CombineWithOr>off</CombineWithOr>
    </Matching>
    <StylePolicyAction name="Response_rule_results_1" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>INPUT</Input>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyRule name="Response_rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>response-rule</Direction>
        <InputFormat>none</InputFormat>
        <OutputFormat>none</OutputFormat>
        <NonXMLProcessing>off</NonXMLProcessing>
        <Unprocessed>off</Unprocessed>
        <Actions class="StylePolicyAction">Response_rule_results_1</Actions>
    </StylePolicyRule>
    <Matching name="ServiceGateway_match_allErrors" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <MatchRules>
            <Type>errorcode</Type>
            <HttpTag/>
            <HttpValue/>
            <Url/>
            <ErrorCode>*</ErrorCode>
            <XPATHExpression/>
            <Method>default</Method>
        </MatchRules>
        <MatchWithPCRE>off</MatchWithPCRE>
        <CombineWithOr>off</CombineWithOr>
    </Matching>
    <StylePolicyAction name="error-rule_xform_8" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>local:///xslt/fault-category-logging.xsl</Transform>
        <Output>NULL</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="error-rule_xform_9" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>INPUT</Input>
        <Transform>local:///xslt/fault-handler.xsl</Transform>
        <Output>result</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="error-rule_xform_10" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>xform</Type>
        <Input>result</Input>
        <Transform>local:///xslt/nfs-logger.xsl</Transform>
        <Output>log</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="error-rule_results_4" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>log</Input>
        <Output>NULL</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <Destination>var://context/log/destination</Destination>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>on</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyAction name="error-rule_results_5" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Type>results</Type>
        <Input>result</Input>
        <Output>OUTPUT</Output>
        <NamedInOutLocationType>default</NamedInOutLocationType>
        <OutputType>default</OutputType>
        <Transactional>off</Transactional>
        <SOAPValidation>body</SOAPValidation>
        <SQLSourceType>static</SQLSourceType>
        <Asynchronous>off</Asynchronous>
        <ResultsMode>first-available</ResultsMode>
        <RetryCount>0</RetryCount>
        <RetryInterval>1000</RetryInterval>
        <MultipleOutputs>off</MultipleOutputs>
        <IteratorType>XPATH</IteratorType>
        <Timeout>0</Timeout>
        <MethodRewriteType>GET</MethodRewriteType>
        <MethodType>POST</MethodType>
        <MethodType2>POST</MethodType2>
    </StylePolicyAction>
    <StylePolicyRule name="error-rule" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Direction>error-rule</Direction>
        <InputFormat>none</InputFormat>
        <OutputFormat>none</OutputFormat>
        <NonXMLProcessing>off</NonXMLProcessing>
        <Unprocessed>off</Unprocessed>
        <Actions class="StylePolicyAction">error-rule_xform_8</Actions>
        <Actions class="StylePolicyAction">error-rule_xform_9</Actions>
        <Actions class="StylePolicyAction">error-rule_xform_10</Actions>
        <Actions class="StylePolicyAction">error-rule_results_4</Actions>
        <Actions class="StylePolicyAction">error-rule_results_5</Actions>
    </StylePolicyRule>
    <StylePolicy name="SAMLProxy_Policy" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <DefStylesheetForSoap>store:///filter-reject-all.xsl</DefStylesheetForSoap>
        <DefStylesheetForXsl>store:///identity.xsl</DefStylesheetForXsl>
        <PolicyMaps>
            <Match class="Matching">unt_match</Match>
            <Rule class="StylePolicyRule">request-rule_1_PolicyAction</Rule>
        </PolicyMaps>
        <PolicyMaps>
            <Match class="Matching">unsigned_MatchingRule</Match>
            <Rule class="StylePolicyRule">request-rule_PolicyRule</Rule>
        </PolicyMaps>
        <PolicyMaps>
            <Match class="Matching">ServiceGateway_match_allSoapFaults</Match>
            <Rule class="StylePolicyRule">fault-response_PolicyRule</Rule>
        </PolicyMaps>
        <PolicyMaps>
            <Match class="Matching">ServiceGateway_match_all</Match>
            <Rule class="StylePolicyRule">Response_rule</Rule>
        </PolicyMaps>
        <PolicyMaps>
            <Match class="Matching">ServiceGateway_match_allErrors</Match>
            <Rule class="StylePolicyRule">error-rule</Rule>
        </PolicyMaps>
    </StylePolicy>
    <MultiProtocolGateway name="UsernameTokenOrUnsignedSAMLToValidSAML_MPG" xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:dp="http://www.datapower.com/schemas/management">
        <mAdminState>enabled</mAdminState>
        <Priority>normal</Priority>
        <FrontProtocol class="HTTPSSourceProtocolHandler">SAMLProxy_FrontSideHandler</FrontProtocol>
        <XMLManager class="XMLManager">default</XMLManager>
        <SSLProxy class="SSLProxyProfile">SAMLValidation_SSLProxyProfile</SSLProxy>
        <DefaultParamNamespace>http://www.datapower.com/param/config</DefaultParamNamespace>
        <QueryParamNamespace>http://www.datapower.com/param/query</QueryParamNamespace>
        <PropagateURI>off</PropagateURI>
        <MonitorProcessingPolicy>terminate-at-first-throttle</MonitorProcessingPolicy>
        <RequestAttachments>allow</RequestAttachments>
        <ResponseAttachments>allow</ResponseAttachments>
        <RootPartNotFirstAction>process-in-order</RootPartNotFirstAction>
        <FrontAttachmentFormat>dynamic</FrontAttachmentFormat>
        <BackAttachmentFormat>dynamic</BackAttachmentFormat>
        <MIMEFrontHeaders>on</MIMEFrontHeaders>
        <MIMEBackHeaders>on</MIMEBackHeaders>
        <StreamOutputToBack>buffer-until-verification</StreamOutputToBack>
        <StreamOutputToFront>buffer-until-verification</StreamOutputToFront>
        <MaxMessageSize>0</MaxMessageSize>
        <GatewayParserLimits>off</GatewayParserLimits>
        <ParserLimitsElementDepth>512</ParserLimitsElementDepth>
        <ParserLimitsAttributeCount>128</ParserLimitsAttributeCount>
        <ParserLimitsMaxNodeSize>33554432</ParserLimitsMaxNodeSize>
        <ParserLimitsForbidExternalReferences>on</ParserLimitsForbidExternalReferences>
        <ParserLimitsExternalReferences>forbid</ParserLimitsExternalReferences>
        <ParserLimitsMaxPrefixes>0</ParserLimitsMaxPrefixes>
        <ParserLimitsMaxNamespaces>0</ParserLimitsMaxNamespaces>
        <ParserLimitsMaxLocalNames>0</ParserLimitsMaxLocalNames>
        <ParserLimitsAttachmentByteCount>2000000000</ParserLimitsAttachmentByteCount>
        <ParserLimitsAttachmentPackageByteCount>0</ParserLimitsAttachmentPackageByteCount>
        <DebugMode persisted="false">on</DebugMode>
        <DebuggerType>internal</DebuggerType>
        <DebugHistory>25</DebugHistory>
        <FlowControl>off</FlowControl>
        <SOAPSchemaURL>store:///schemas/soap-envelope.xsd</SOAPSchemaURL>
        <FrontTimeout>120</FrontTimeout>
        <BackTimeout>120</BackTimeout>
        <FrontPersistentTimeout>180</FrontPersistentTimeout>
        <BackPersistentTimeout>180</BackPersistentTimeout>
        <IncludeResponseTypeEncoding>off</IncludeResponseTypeEncoding>
        <BackHTTPVersion>HTTP/1.1</BackHTTPVersion>
        <PersistentConnections>on</PersistentConnections>
        <LoopDetection>off</LoopDetection>
        <DoHostRewriting>on</DoHostRewriting>
        <DoChunkedUpload>off</DoChunkedUpload>
        <ProcessHTTPErrors>on</ProcessHTTPErrors>
        <HTTPClientIPLabel>X-Client-IP</HTTPClientIPLabel>
        <InOrderMode>
            <Request>off</Request>
            <Backend>off</Backend>
            <Response>off</Response>
        </InOrderMode>
        <WSAMode>sync2sync</WSAMode>
        <WSARequireAAA>on</WSARequireAAA>
        <WSAStrip>on</WSAStrip>
        <WSADefaultReplyTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultReplyTo>
        <WSADefaultFaultTo>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</WSADefaultFaultTo>
        <WSAForce>off</WSAForce>
        <WSAGenStyle>sync</WSAGenStyle>
        <WSAHTTPAsyncResponseCode>204</WSAHTTPAsyncResponseCode>
        <WSATimeout>120</WSATimeout>
        <WSRMEnabled>off</WSRMEnabled>
        <WSRMSequenceExpiration>3600</WSRMSequenceExpiration>
        <WSRMDestinationAcceptCreateSequence>on</WSRMDestinationAcceptCreateSequence>
        <WSRMDestinationMaximumSequences>400</WSRMDestinationMaximumSequences>
        <WSRMDestinationInOrder>off</WSRMDestinationInOrder>
        <WSRMDestinationMaximumInOrderQueueLength>10</WSRMDestinationMaximumInOrderQueueLength>
        <WSRMDestinationAcceptOffers>off</WSRMDestinationAcceptOffers>
        <WSRMFrontForce>off</WSRMFrontForce>
        <WSRMBackForce>off</WSRMBackForce>
        <WSRMBackCreateSequence>off</WSRMBackCreateSequence>
        <WSRMFrontCreateSequence>off</WSRMFrontCreateSequence>
        <WSRMSourceMakeOffer>off</WSRMSourceMakeOffer>
        <WSRMUsesSequenceSSL>off</WSRMUsesSequenceSSL>
        <WSRMSourceMaximumSequences>400</WSRMSourceMaximumSequences>
        <WSRMSourceRetransmissionInterval>10</WSRMSourceRetransmissionInterval>
        <WSRMSourceExponentialBackoff>on</WSRMSourceExponentialBackoff>
        <WSRMSourceMaximumRetransmissions>4</WSRMSourceMaximumRetransmissions>
        <WSRMSourceMaximumQueueLength>30</WSRMSourceMaximumQueueLength>
        <WSRMSourceRequestAckCount>1</WSRMSourceRequestAckCount>
        <WSRMSourceInactivityClose>360</WSRMSourceInactivityClose>
        <ForcePolicyExec>off</ForcePolicyExec>
        <RewriteErrors>on</RewriteErrors>
        <DelayErrors>on</DelayErrors>
        <DelayErrorsDuration>1000</DelayErrorsDuration>
        <RequestType>soap</RequestType>
        <ResponseType>soap</ResponseType>
        <FollowRedirects>on</FollowRedirects>
        <StylePolicy class="StylePolicy">SAMLProxy_Policy</StylePolicy>
        <Type>dynamic-backend</Type>
        <AllowCompression>off</AllowCompression>
        <AllowCacheControlHeader>off</AllowCacheControlHeader>
    </MultiProtocolGateway>
</#macro>