<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/person/mediation/xslt/output_map.map" md5sum="bf74bda5f9f4df7f2a4e36bf8b6968c9" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		output_map.map
*   Map declaration(s):	output_map
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252Fprovider%252FV1%252FPersonService%257DgetPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV1%252FPersonService%257DgetPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.stelvio.no/example/person/provider/V1/PersonService"
    xmlns:in2="wsdl.http://www.stelvio.no/example/person/provider/V1/PersonService"
    xmlns:in3="http://www.stelvio.no/example/person/provider/V1"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://www.stelvio.no/example/person/V1"
    xmlns:out2="http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="wsdl.http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://www.stelvio.no/example/person/mediation/xslt/output_map"
    exclude-result-prefixes="map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:output_map"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:output_map">
    <body>
      <!-- a structural mapping: "in:getPersonResponse"(<Anonymous>) to "out2:getPersonResponse"(<Anonymous>) -->
      <xsl:apply-templates select="in:getPersonResponse" mode="localGetPersonResponseToGetPersonResponse_1192177875"/>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "in:getPersonResponse" to "out2:getPersonResponse".  -->
  <xsl:template match="in:getPersonResponse"  mode="localGetPersonResponseToGetPersonResponse_1192177875">
    <out2:getPersonResponse>
      <!-- a structural mapping: "getPersonResponse"(GetPersonResponse) to "getPersonResponse"(GetPersonResponse) -->
      <xsl:apply-templates select="getPersonResponse" mode="localGetPersonResponseToGetPersonResponse_691376766"/>
    </out2:getPersonResponse>
  </xsl:template>

  <!-- This rule represents an element mapping: "getPersonResponse" to "getPersonResponse".  -->
  <xsl:template match="getPersonResponse"  mode="localGetPersonResponseToGetPersonResponse_691376766">
    <getPersonResponse>
      <!-- a structural mapping: "person"(Person) to "person"(Person) -->
      <xsl:apply-templates select="person" mode="localPersonToPerson_112651254"/>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="person/following-sibling::*"/>
    </getPersonResponse>
  </xsl:template>

  <!-- This rule represents an element mapping: "person" to "person".  -->
  <xsl:template match="person"  mode="localPersonToPerson_112651254">
    <person>
      <!-- a simple data mapping: "id"(string) to "id"(string) -->
      <id>
        <xsl:value-of select="id"/>
      </id>
      <!-- a structural mapping: "name"(Name) to "name"(Name) -->
      <xsl:apply-templates select="name" mode="localNameToName_1748368270"/>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="name/following-sibling::*"/>
    </person>
  </xsl:template>

  <!-- This rule represents an element mapping: "name" to "name".  -->
  <xsl:template match="name"  mode="localNameToName_1748368270">
    <name>
      <!-- a simple data mapping: "firstName"(string) to "firstName"(string) -->
      <firstName>
        <xsl:value-of select="firstName"/>
      </firstName>
      <!-- a simple data mapping: "middleName"(string) to "middleName"(string) -->
      <xsl:if test="middleName">
        <middleName>
          <xsl:value-of select="middleName"/>
        </middleName>
      </xsl:if>
      <!-- a simple data mapping: "lastName"(string) to "lastName"(string) -->
      <lastName>
        <xsl:value-of select="lastName"/>
      </lastName>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="lastName/following-sibling::*"/>
    </name>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
