<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/person/mediation/V1/getPersonPersonNotFoundFault.map" md5sum="ba2da5ca5417a9d6f828a9a3efd94f9b" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		getPersonPersonNotFoundFault.map
*   Map declaration(s):	getPersonPersonNotFoundFault
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252Fprovider%252FV1%252FPersonService%257DgetPerson_getPersonPersonNotFoundFaultMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV1%252FPersonService%257DgetPerson_getPersonPersonNotFoundFaultMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.stelvio.no/example/person/provider/V1/PersonService"
    xmlns:in2="wsdl.http://www.stelvio.no/example/person/provider/V1/PersonService"
    xmlns:in3="http://www.stelvio.no/example/person/provider/V1"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="http://www.stelvio.no/example/person/V1"
    xmlns:out2="http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="wsdl.http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://www.stelvio.no/example/person/mediation/xslt/fault_map"
    exclude-result-prefixes="map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:getPersonPersonNotFoundFault"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:getPersonPersonNotFoundFault">
    <body>
      <!-- a structural mapping: "in:getPersonFault1_getPersonPersonNotFoundFault"(PersonNotFoundFault) to "out2:getPersonFault1_getPersonPersonNotFoundFault"(PersonNotFoundFault) -->
      <xsl:apply-templates select="in:getPersonFault1_getPersonPersonNotFoundFault" mode="localGetPersonFault1_getPersonPersonNotFoundFaultToGetPersonFault1_getPersonPersonNotFoundFault_1546987870"/>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "in:getPersonFault1_getPersonPersonNotFoundFault" to "out2:getPersonFault1_getPersonPersonNotFoundFault".  -->
  <xsl:template match="in:getPersonFault1_getPersonPersonNotFoundFault"  mode="localGetPersonFault1_getPersonPersonNotFoundFaultToGetPersonFault1_getPersonPersonNotFoundFault_1546987870">
    <out2:getPersonFault1_getPersonPersonNotFoundFault>
      <!-- a simple data mapping: "id"(string) to "id"(string) -->
      <id>
        <xsl:value-of select="id"/>
      </id>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="id/following-sibling::*"/>
    </out2:getPersonFault1_getPersonPersonNotFoundFault>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
