//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.wsn.notification_broker;

import javax.xml.ws.WebFault;
import org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType;

@WebFault(name = "PublisherRegistrationRejectedFault", targetNamespace = "http://docs.oasis-open.org/wsn/br-2")
public class PublisherRegistrationRejectedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PublisherRegistrationRejectedFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PublisherRegistrationRejectedFault(String message, PublisherRegistrationRejectedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public PublisherRegistrationRejectedFault(String message, PublisherRegistrationRejectedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.br_2.PublisherRegistrationRejectedFaultType
     */
    public PublisherRegistrationRejectedFaultType getFaultInfo() {
        return faultInfo;
    }

}
