//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.wsn.subscription_manager;

import javax.xml.ws.WebFault;
import org.oasis_open.docs.wsrf.rl_2.UnableToSetTerminationTimeFaultType;

@WebFault(name = "UnableToSetTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsrf/rl-2")
public class UnableToSetTerminationTimeFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnableToSetTerminationTimeFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnableToSetTerminationTimeFault(String message, UnableToSetTerminationTimeFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public UnableToSetTerminationTimeFault(String message, UnableToSetTerminationTimeFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsrf.rl_2.UnableToSetTerminationTimeFaultType
     */
    public UnableToSetTerminationTimeFaultType getFaultInfo() {
        return faultInfo;
    }

}
