//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.wsn.subscription_manager;

import javax.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType;

@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableTerminationTimeFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UnacceptableTerminationTimeFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UnacceptableTerminationTimeFault(String message, UnacceptableTerminationTimeFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public UnacceptableTerminationTimeFault(String message, UnacceptableTerminationTimeFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.UnacceptableTerminationTimeFaultType
     */
    public UnacceptableTerminationTimeFaultType getFaultInfo() {
        return faultInfo;
    }

}
