//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package org.oasis_open.docs.wsrf.rl_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.oasis_open.docs.wsrf.rl_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResourceNotDestroyedFault_QNAME = new QName("http://docs.oasis-open.org/wsrf/rl-2", "ResourceNotDestroyedFault");
    private final static QName _TerminationTimeChangeRejectedFault_QNAME = new QName("http://docs.oasis-open.org/wsrf/rl-2", "TerminationTimeChangeRejectedFault");
    private final static QName _UnableToSetTerminationTimeFault_QNAME = new QName("http://docs.oasis-open.org/wsrf/rl-2", "UnableToSetTerminationTimeFault");
    private final static QName _TerminationTime_QNAME = new QName("http://docs.oasis-open.org/wsrf/rl-2", "TerminationTime");
    private final static QName _SetTerminationTimeRequestedTerminationTime_QNAME = new QName("http://docs.oasis-open.org/wsrf/rl-2", "RequestedTerminationTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.oasis_open.docs.wsrf.rl_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResourceNotDestroyedFaultType }
     * 
     */
    public ResourceNotDestroyedFaultType createResourceNotDestroyedFaultType() {
        return new ResourceNotDestroyedFaultType();
    }

    /**
     * Create an instance of {@link TerminationTimeChangeRejectedFaultType }
     * 
     */
    public TerminationTimeChangeRejectedFaultType createTerminationTimeChangeRejectedFaultType() {
        return new TerminationTimeChangeRejectedFaultType();
    }

    /**
     * Create an instance of {@link TerminationTime }
     * 
     */
    public TerminationTime createTerminationTime() {
        return new TerminationTime();
    }

    /**
     * Create an instance of {@link ScheduledResourceTerminationRP }
     * 
     */
    public ScheduledResourceTerminationRP createScheduledResourceTerminationRP() {
        return new ScheduledResourceTerminationRP();
    }

    /**
     * Create an instance of {@link CurrentTime }
     * 
     */
    public CurrentTime createCurrentTime() {
        return new CurrentTime();
    }

    /**
     * Create an instance of {@link SetTerminationTimeResponse }
     * 
     */
    public SetTerminationTimeResponse createSetTerminationTimeResponse() {
        return new SetTerminationTimeResponse();
    }

    /**
     * Create an instance of {@link TerminationNotification }
     * 
     */
    public TerminationNotification createTerminationNotification() {
        return new TerminationNotification();
    }

    /**
     * Create an instance of {@link UnableToSetTerminationTimeFaultType }
     * 
     */
    public UnableToSetTerminationTimeFaultType createUnableToSetTerminationTimeFaultType() {
        return new UnableToSetTerminationTimeFaultType();
    }

    /**
     * Create an instance of {@link SetTerminationTime }
     * 
     */
    public SetTerminationTime createSetTerminationTime() {
        return new SetTerminationTime();
    }

    /**
     * Create an instance of {@link DestroyResponse }
     * 
     */
    public DestroyResponse createDestroyResponse() {
        return new DestroyResponse();
    }

    /**
     * Create an instance of {@link Destroy }
     * 
     */
    public Destroy createDestroy() {
        return new Destroy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceNotDestroyedFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsrf/rl-2", name = "ResourceNotDestroyedFault")
    public JAXBElement<ResourceNotDestroyedFaultType> createResourceNotDestroyedFault(ResourceNotDestroyedFaultType value) {
        return new JAXBElement<ResourceNotDestroyedFaultType>(_ResourceNotDestroyedFault_QNAME, ResourceNotDestroyedFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminationTimeChangeRejectedFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsrf/rl-2", name = "TerminationTimeChangeRejectedFault")
    public JAXBElement<TerminationTimeChangeRejectedFaultType> createTerminationTimeChangeRejectedFault(TerminationTimeChangeRejectedFaultType value) {
        return new JAXBElement<TerminationTimeChangeRejectedFaultType>(_TerminationTimeChangeRejectedFault_QNAME, TerminationTimeChangeRejectedFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnableToSetTerminationTimeFaultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsrf/rl-2", name = "UnableToSetTerminationTimeFault")
    public JAXBElement<UnableToSetTerminationTimeFaultType> createUnableToSetTerminationTimeFault(UnableToSetTerminationTimeFaultType value) {
        return new JAXBElement<UnableToSetTerminationTimeFaultType>(_UnableToSetTerminationTimeFault_QNAME, UnableToSetTerminationTimeFaultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TerminationTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsrf/rl-2", name = "TerminationTime")
    public JAXBElement<TerminationTime> createTerminationTime(TerminationTime value) {
        return new JAXBElement<TerminationTime>(_TerminationTime_QNAME, TerminationTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wsrf/rl-2", name = "RequestedTerminationTime", scope = SetTerminationTime.class)
    public JAXBElement<XMLGregorianCalendar> createSetTerminationTimeRequestedTerminationTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SetTerminationTimeRequestedTerminationTime_QNAME, XMLGregorianCalendar.class, SetTerminationTime.class, value);
    }

}
