//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package org.oasis_open.docs.wsrf.rl_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="RequestedTerminationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="RequestedLifetimeDuration" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestedTerminationTime",
    "requestedLifetimeDuration"
})
@XmlRootElement(name = "SetTerminationTime")
public class SetTerminationTime {

    @XmlElementRef(name = "RequestedTerminationTime", namespace = "http://docs.oasis-open.org/wsrf/rl-2", type = JAXBElement.class)
    protected JAXBElement<XMLGregorianCalendar> requestedTerminationTime;
    @XmlElement(name = "RequestedLifetimeDuration")
    protected Duration requestedLifetimeDuration;

    /**
     * Gets the value of the requestedTerminationTime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getRequestedTerminationTime() {
        return requestedTerminationTime;
    }

    /**
     * Sets the value of the requestedTerminationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setRequestedTerminationTime(JAXBElement<XMLGregorianCalendar> value) {
        this.requestedTerminationTime = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the requestedLifetimeDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRequestedLifetimeDuration() {
        return requestedLifetimeDuration;
    }

    /**
     * Sets the value of the requestedLifetimeDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRequestedLifetimeDuration(Duration value) {
        this.requestedLifetimeDuration = value;
    }

}
