<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="ServiceGateway" targetNamespace="http://www.ibm.com/websphere/sibx/ServiceGateway"
	xmlns:tns="http://www.ibm.com/websphere/sibx/ServiceGateway" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://www.ibm.com/websphere/sibx/ServiceGateway" xmlns:tns="http://www.ibm.com/websphere/sibx/ServiceGateway" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:element name="message" type="xsd:anyType"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="gatewayMessage">
    <wsdl:part element="tns:message" name="message"/>
  </wsdl:message>
    <wsdl:portType name="ServiceGateway">
    <wsdl:operation name="requestOnly">
      <wsdl:input message="tns:gatewayMessage" name="requestOnlyRequest"/>
    </wsdl:operation>
    <wsdl:operation name="requestResponse">
      <wsdl:input message="tns:gatewayMessage" name="requestResponseRequest"/>
      <wsdl:output message="tns:gatewayMessage" name="requestResponseResponse"/>
      <wsdl:fault message="tns:gatewayMessage" name="fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
