<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/IdentIkkeFunnet.map" md5sum="19c889c9555f1f25659713e06e8ddd7d" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		IdentIkkeFunnet.map
*   Map declaration(s):	IdentIkkeFunnet
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Fnav-lib-frg%252Fno%252Fnav%252Flib%252Ffrg%252Finf%252FPerson%257DfinnPerson_faultPersonIkkeFunnetMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Foppgave-poc%252FSED%257DvaliderOgLagreUtenlandskId_norskIdIkkeFunnetMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://nav-lib-frg/no/nav/lib/frg/fault"
    xmlns:in2="http://nav-lib-frg/no/nav/lib/frg/inf/Person"
    xmlns:in5="wsdl.http://nav-lib-frg/no/nav/lib/frg/inf/Person"
    xmlns:in3="http://nav-lib-frg/no/nav/lib/frg/gbo"
    xmlns:in4="http://stelvio-commons-lib/no/nav/gbo"
    xmlns:out="http://oppgave-poc/SED"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="wsdl.http://oppgave-poc/SED"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:out3="http://oppgave-poc"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://oppgave-poc/xslt/IdentIkkeFunnet"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="set in msl math exsl in2 in3 date in4 in5 xalan str map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:validerOgLagreUtenlandskId_norskIdIkkeFunnetMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:IdentIkkeFunnet2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:IdentIkkeFunnet"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:IdentIkkeFunnet">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:validerOgLagreUtenlandskId_norskIdIkkeFunnetMsg'"/>
      </xsl:attribute>
      <out:hentIdDataFraSEDFault1_idIkkeFunnet xsi:nil="true"/>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:IdentIkkeFunnet2">
    <xsl:param name="body"/>
    <out:hentIdDataFraSEDFault1_idIkkeFunnet xsi:nil="true"/>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
