<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/PINtoNavnesøk.map" md5sum="7d7bc466c2789bfd60889b3994b6ac2b" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		PINtoNavnesøk.map
*   Map declaration(s):	PINtoNavnesøk
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Foppgave-poc%252FSED%257DvaliderOgLagreUtenlandskIdRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Fnav-lib-frg%252Fno%252Fnav%252Flib%252Ffrg%252Finf%252FPerson%257DfinnPersonRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://oppgave-poc/SED"
    xmlns:in2="wsdl.http://oppgave-poc/SED"
    xmlns:in3="http://oppgave-poc"
    xmlns:out="http://nav-lib-frg/no/nav/lib/frg/fault"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out2="http://nav-lib-frg/no/nav/lib/frg/inf/Person"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out5="wsdl.http://nav-lib-frg/no/nav/lib/frg/inf/Person"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out3="http://nav-lib-frg/no/nav/lib/frg/gbo"
    xmlns:out4="http://stelvio-commons-lib/no/nav/gbo"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://oppgave-poc/xslt/PINtoNavnesøk"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="xalan str set in msl math map exsl in2 date in3"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out5:finnPersonRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:PINtoNavnesøk2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:PINtoNavnesøk"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:PINtoNavnesøk">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out5:finnPersonRequestMsg'"/>
      </xsl:attribute>
      <out2:finnPerson>
        <finnPersonRequest>
          <navnesok>
            <!-- a simple data mapping: "in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames"(string) to "fornavn"(string) -->
            <xsl:if test="in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames">
              <fornavn>
                <xsl:value-of select="in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames"/>
              </fornavn>
            </xsl:if>
            <!-- a simple data mapping: "in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName"(string) to "etternavn"(string) -->
            <xsl:if test="in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName">
              <etternavn>
                <xsl:value-of select="in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName"/>
              </etternavn>
            </xsl:if>
            <!-- a simple data mapping: "in:validerOgLagreUtenlandskId/minIDSetWithPin/gender"(string) to "kjonn"(string) -->
            <xsl:if test="in:validerOgLagreUtenlandskId/minIDSetWithPin/gender">
              <kjonn>
                <xsl:value-of select="in:validerOgLagreUtenlandskId/minIDSetWithPin/gender"/>
              </kjonn>
            </xsl:if>
            <!-- a simple data mapping: "in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate"(date) to "datoFodt"(string) -->
            <xsl:if test="in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate">
              <datoFodt>
                <xsl:value-of select="in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate"/>
              </datoFodt>
            </xsl:if>
          </navnesok>
        </finnPersonRequest>
      </out2:finnPerson>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:PINtoNavnesøk2">
    <xsl:param name="body"/>
    <out2:finnPerson>
      <finnPersonRequest>
        <navnesok>
          <!-- a simple data mapping: "$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames"(string) to "fornavn"(string) -->
          <xsl:if test="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames">
            <fornavn>
              <xsl:value-of select="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/forenames"/>
            </fornavn>
          </xsl:if>
          <!-- a simple data mapping: "$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName"(string) to "etternavn"(string) -->
          <xsl:if test="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName">
            <etternavn>
              <xsl:value-of select="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/familyName"/>
            </etternavn>
          </xsl:if>
          <!-- a simple data mapping: "$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/gender"(string) to "kjonn"(string) -->
          <xsl:if test="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/gender">
            <kjonn>
              <xsl:value-of select="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/gender"/>
            </kjonn>
          </xsl:if>
          <!-- a simple data mapping: "$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate"(date) to "datoFodt"(string) -->
          <xsl:if test="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate">
            <datoFodt>
              <xsl:value-of select="$body/in:validerOgLagreUtenlandskId/minIDSetWithPin/birthDate"/>
            </datoFodt>
          </xsl:if>
        </navnesok>
      </finnPersonRequest>
    </out2:finnPerson>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
