<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/ValidertPIN.map" md5sum="305be27b408ecd6c08bbad5a94a0b754" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		ValidertPIN.map
*   Map declaration(s):	ValidertPIN
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Foppgave-poc%252FValiderPIN%257DvaliderPINResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Foppgave-poc%257DMinIDSetWithPIN/message%3D%257Bhttp%253A%252F%252Foppgave-poc%252FPerson%257DavklarIdentitetResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="wsdl.http://oppgave-poc/ValiderPIN"
    xmlns:in2="http://nav-lib-frg/no/nav/lib/frg/gbo"
    xmlns:in3="http://stelvio-commons-lib/no/nav/gbo"
    xmlns:in4="http://oppgave-poc/ValiderPIN"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out="http://oppgave-poc/Person"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:out2="wsdl.http://oppgave-poc/Person"
    xmlns:io7="http://oppgave-poc"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://oppgave-poc/xslt/ValidertPIN"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="xalan str set in msl math map exsl in2 date in3 in4"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out2:avklarIdentitetResponseMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:ValidertPIN2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:ValidertPIN"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:ValidertPIN">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out2:avklarIdentitetResponseMsg'"/>
      </xsl:attribute>
      <out:avklarIdentitetResponse>
        <!-- a simple data mapping: "in4:validerPINResponse/pin"(string) to "norskPIN"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space(in4:validerPINResponse/pin)">
            <norskPIN>
              <xsl:value-of select="in4:validerPINResponse/pin"/>
            </norskPIN>
          </xsl:when>
          <xsl:otherwise>
            <norskPIN xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
      </out:avklarIdentitetResponse>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:ValidertPIN2">
    <xsl:param name="body"/>
    <out:avklarIdentitetResponse>
      <!-- a simple data mapping: "$body/in4:validerPINResponse/pin"(string) to "norskPIN"(string) -->
      <xsl:choose>
        <xsl:when test="normalize-space($body/in4:validerPINResponse/pin)">
          <norskPIN>
            <xsl:value-of select="$body/in4:validerPINResponse/pin"/>
          </norskPIN>
        </xsl:when>
        <xsl:otherwise>
          <norskPIN xsi:nil="true"/>
        </xsl:otherwise>
      </xsl:choose>
    </out:avklarIdentitetResponse>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
