<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Binding" targetNamespace="http://nav.no/virksomhet/tjenester/oppholdsstatus/v1/Binding/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav.no/virksomhet/tjenester/oppholdsstatus/v1/Binding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:oppholdsstatus="http://nav.no/virksomhet/tjenester/oppholdsstatus/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:import namespace="http://nav.no/virksomhet/tjenester/oppholdsstatus/v1" location="../oppholdsstatus.wsdl">
    </wsdl:import>
  <wsdl:binding name="OppholdsstatusBinding" type="oppholdsstatus:Oppholdsstatus">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing/>
    <wsdl:operation name="hentOppholdsstatus">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="oppholdsstatusIkkeFunnet">
        <soap:fault name="oppholdsstatusIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="personIkkeFunnet">
        <soap:fault name="personIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Oppholdsstatus">
    <wsdl:port name="OppholdsstatusPort" binding="tns:OppholdsstatusBinding">
      <soap:address location="http://localhost:9080/nav-tjeneste-oppholdsstatus_v1Web/sca/OppholdsstatusWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
