<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="PersonWSEXP_PersonHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/person/v1/Binding" xmlns:Port_0="http://nav.no/virksomhet/tjenester/person/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/person/v1/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="no/nav/virksomhet/tjenester/person/person.wsdl" namespace="http://nav.no/virksomhet/tjenester/person/v1"/>
  <wsdl:binding name="PersonWSEXP_PersonHttpBinding" type="Port_0:Person">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="registrereAdresseForDodsbo">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="kunneIkkeRegistrereAdresseForDodsbo">
        <soap:fault name="kunneIkkeRegistrereAdresseForDodsbo" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="personHarUtlandsadresse">
        <soap:fault name="personHarUtlandsadresse" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentPerson">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="PersonIkkeFunnet">
        <soap:fault name="PersonIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PersonWSEXP_PersonHttpService">
    <wsdl:port binding="this:PersonWSEXP_PersonHttpBinding" name="PersonWSEXP_PersonHttpPort">
      <soap:address location="http://localhost:9080/nav-tjeneste-personWeb/sca/PersonWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>