<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://BpelInvokeTest/Test" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://BpelInvokeTest/Test/Binding" name="BpelInvokeTestWSEXP_TestHttp_Service" targetNamespace="http://BpelInvokeTest/Test/Binding">
  <wsdl:import location="Test.wsdl" namespace="http://BpelInvokeTest/Test"/>
  <wsdl:binding name="BpelInvokeTestWSEXP_TestHttpBinding" type="Port_0:Test">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="test">
      <soap:operation soapAction=""/>
      <wsdl:input name="testRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="testResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="BpelInvokeTestWSEXP_TestHttpService">
    <wsdl:port binding="this:BpelInvokeTestWSEXP_TestHttpBinding" name="BpelInvokeTestWSEXP_TestHttpPort">
      <soap:address location="http://localhost:9080/BpelInvokeTestWeb/sca/BpelInvokeTestWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
