<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://BpelInvokeTest/Echo" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://BpelInvokeTest/InvokeTestArtifacts" xmlns:wsdl0="http://BpelInvokeTest/Test" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="InvokeTest" targetNamespace="http://BpelInvokeTest/InvokeTestArtifacts">
  <plnk:partnerLinkType name="TestPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:Test"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="PartnerPLT">
    <plnk:role name="Reference">
      <plnk:portType name="wsdl0:Test"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="Test.wsdl" namespace="http://BpelInvokeTest/Test"/>
</wsdl:definitions>
