<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://BpelInvokeTest/Test" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Test" targetNamespace="http://BpelInvokeTest/Test">
    <wsdl:types>
    <xsd:schema targetNamespace="http://BpelInvokeTest/Test" xmlns:tns="http://BpelInvokeTest/Test" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:element name="test">
        <xsd:complexType>
          <xsd:sequence/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="testResponse">
        <xsd:complexType>
          <xsd:sequence/>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="testRequestMsg">
    <wsdl:part element="tns:test" name="testParameters"/>
  </wsdl:message>
    <wsdl:message name="testResponseMsg">
    <wsdl:part element="tns:testResponse" name="testResult"/>
  </wsdl:message>
    <wsdl:portType name="Test">
    <wsdl:operation name="test">
      <wsdl:input message="tns:testRequestMsg" name="testRequest"/>
      <wsdl:output message="tns:testResponseMsg" name="testResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
