<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://nav/metronome"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://nav/metronome"
	xmlns:bw2="http://docs.oasis-open.org/wsn/bw-2">

	<!--
		Import the 'base notification' WSDL definitions; this includes the
		port type (a.k.a. interface definition) that the consumer will
		implement
	-->

	<wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" location="bw-2.wsdl"/>

	<!--
		Define a binding from the NotificationConsumer port type to SOAP over
		HTTP, document literal style
	-->
	<wsdl:binding name="PushNotificationConsumerSOAP" type="bw2:NotificationConsumer">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="Notify">
			<soap:operation soapAction="" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>

	<!--
		Define the web service and associated ports; only one port in this
		case - the SOAP/HTTP port defined above
	-->
	<wsdl:service name="PushNotificationConsumer">
		<wsdl:port name="PushNotificationConsumerSOAP" binding="tns:PushNotificationConsumerSOAP">
			<soap:address location="http://localhost:9080/ctx/svcs/consumerSOAP" />
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>