<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:bons1="http://www.rtv.no/NamespaceTPS" xmlns:tns="http://nav-cons-frg-tps/no/nav/inf/TPSPersonHendelse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TPSPersonHendelse" targetNamespace="http://nav-cons-frg-tps/no/nav/inf/TPSPersonHendelse">
  <wsdl:types>
    <xsd:schema targetNamespace="http://nav-cons-frg-tps/no/nav/inf/TPSPersonHendelse" xmlns:bons1="http://www.rtv.no/NamespaceTPS" xmlns:tns="http://nav-cons-frg-tps/no/nav/inf/TPSPersonHendelse" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://www.rtv.no/NamespaceTPS" schemaLocation="../../../xsd-includes/http.www.rtv.no.NamespaceTPS.xsd"/>
      <xsd:element name="TPSEndringsmelding">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element ref="bons1:distribusjonsMelding"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
        </xsd:schema>
  </wsdl:types>
    <wsdl:message name="TPSEndringsmeldingRequestMsg">
    <wsdl:part element="tns:TPSEndringsmelding" name="TPSEndringsmeldingParameters"/>
  </wsdl:message>
    <wsdl:portType name="TPSPersonHendelse">
    <wsdl:operation name="TPSEndringsmelding">
      <wsdl:input message="tns:TPSEndringsmeldingRequestMsg" name="TPSEndringsmeldingRequest"/>
    </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
