<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="PersonService" targetNamespace="http://www.stelvio.no/example/services/V1/PersonService" xmlns:tns="http://www.stelvio.no/example/services/V1/PersonService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:portType name="PersonService"/>
</wsdl:definitions>