<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ExampleStubWSEXP_ExamplePortTypeHttp_Service" targetNamespace="http://www.stelvio.no/example/ExamplePortType/Binding" xmlns:Port_0="http://www.stelvio.no/example/ExamplePortType" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://www.stelvio.no/example/ExamplePortType/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ExamplePortType.wsdl" namespace="http://www.stelvio.no/example/ExamplePortType"/>
  <wsdl:binding name="ExampleStubWSEXP_ExamplePortTypeHttpBinding" type="Port_0:ExamplePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="echo">
      <soap:operation soapAction=""/>
      <wsdl:input name="echoRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="echoResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ExampleStubWSEXP_ExamplePortTypeHttpService">
    <wsdl:port binding="this:ExampleStubWSEXP_ExamplePortTypeHttpBinding" name="ExampleStubWSEXP_ExamplePortTypeHttpPort">
      <soap:address location="http://localhost:9080/stelvio-inc-example-stubWeb/sca/ExampleStubWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>