<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/person/xslt/V1toV2output.map" md5sum="0b8d4efa3deaaa42708c027ecee7638e" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		V1toV2output.map
*   Map declaration(s):	V1toV2output
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV2%252FPersonService%257DgetPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV1%252FPersonService%257DgetPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.stelvio.no/example/person/V2"
    xmlns:in2="http://www.stelvio.no/example/person/V2/PersonService"
    xmlns:in3="wsdl.http://www.stelvio.no/example/person/V2/PersonService"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://www.stelvio.no/example/person/V1"
    xmlns:out="http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="wsdl.http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://www.stelvio.no/example/person/xslt/V1toV2output"
    exclude-result-prefixes="in in2 in3 map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:V1toV2output"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:V1toV2output">
    <body>
      <!-- a structural mapping: "in2:getPersonResponse"(<Anonymous>) to "out:getPersonResponse"(<Anonymous>) -->
      <xsl:apply-templates select="in2:getPersonResponse" mode="localGetPersonResponseToGetPersonResponse_1839596356"/>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "in2:getPersonResponse" to "out:getPersonResponse".  -->
  <xsl:template match="in2:getPersonResponse"  mode="localGetPersonResponseToGetPersonResponse_1839596356">
    <out:getPersonResponse>
      <!-- a structural mapping: "getPersonResponse"(GetPersonResponse) to "getPersonResponse"(GetPersonResponse) -->
      <xsl:apply-templates select="getPersonResponse" mode="localGetPersonResponseToGetPersonResponse_206584336"/>
    </out:getPersonResponse>
  </xsl:template>

  <!-- This rule represents an element mapping: "getPersonResponse" to "getPersonResponse".  -->
  <xsl:template match="getPersonResponse"  mode="localGetPersonResponseToGetPersonResponse_206584336">
    <getPersonResponse>
      <!-- a structural mapping: "person"(Person) to "person"(Person) -->
      <xsl:apply-templates select="person" mode="localPersonToPerson_532789266"/>
    </getPersonResponse>
  </xsl:template>

  <!-- This rule represents an element mapping: "person" to "person".  -->
  <xsl:template match="person"  mode="localPersonToPerson_532789266">
    <person>
      <!-- a simple data mapping: "id"(string) to "id"(string) -->
      <id>
        <xsl:value-of select="id"/>
      </id>
    </person>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
