<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:bons1="http://nav-lib-frg/no/nav/lib/frg/gbo" xmlns:bons2="http://nav-lib-frg/no/nav/lib/frg/gbo" xmlns:tns="http://nav-lib-frg/no/nav/lib/frg/inf/MedlemskapsunntakHendelse" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MedlemskapsunntakHendelse" targetNamespace="http://nav-lib-frg/no/nav/lib/frg/inf/MedlemskapsunntakHendelse">
  <wsdl:types>
    <xsd:schema targetNamespace="http://nav-lib-frg/no/nav/lib/frg/inf/MedlemskapsunntakHendelse" xmlns:bons1="http://nav-lib-frg/no/nav/lib/frg/gbo" xmlns:bons2="http://nav-lib-frg/no/nav/lib/frg/gbo" xmlns:tns="http://nav-lib-frg/no/nav/lib/frg/inf/MedlemskapsunntakHendelse" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://nav-lib-frg/no/nav/lib/frg/gbo" schemaLocation="../../../../../xsd-includes/http.nav-lib-frg.no.nav.lib.frg.gbo.xsd"/>
            <xsd:import namespace="http://nav-lib-frg/no/nav/lib/frg/gbo" schemaLocation="../../../../../xsd-includes/http.nav-lib-frg.no.nav.lib.frg.gbo.xsd"/>
            <xsd:element name="medlemskapsunntakOppdatert">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="oppdaterMedlemskapsunntakRequest" nillable="true" type="bons2:GBOMedlemskapsunntak"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="medlemskapsunntakOppdatertRequestMsg">
    <wsdl:part element="tns:medlemskapsunntakOppdatert" name="medlemskapsunntakOppdatertParameters"/>
  </wsdl:message>
    <wsdl:portType name="MedlemskapsunntakHendelse">
    <wsdl:operation name="medlemskapsunntakOppdatert">
      <wsdl:input message="tns:medlemskapsunntakOppdatertRequestMsg" name="medlemskapsunntakOppdatertRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
