<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://nav-lib-oko/no/nav/lib/oko/gbo" xmlns:tns="http://nav-bproc-pen-ppen015-1.2.2/no/nav/inf/OppdragOnlineAsync" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="OppdragOnlineAsync" targetNamespace="http://nav-bproc-pen-ppen015-1.2.2/no/nav/inf/OppdragOnlineAsync">
    <wsdl:types>
    <xsd:schema targetNamespace="http://nav-bproc-pen-ppen015-1.2.2/no/nav/inf/OppdragOnlineAsync" xmlns:bons1="http://nav-lib-oko/no/nav/lib/oko/gbo" xmlns:tns="http://nav-bproc-pen-ppen015-1.2.2/no/nav/inf/OppdragOnlineAsync" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://nav-lib-oko/no/nav/lib/oko/gbo" schemaLocation="../lib/oko/gbo/GBOOppdrag.xsd"/>
      <xsd:element name="sendAsynkronOppdragsmeldingProsessOnline">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="sendAsynkronOppdragsmeldingProsessOnlineRequest" nillable="true" type="bons1:GBOOppdrag"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="sendAsynkronOppdragsmeldingProsessOnlineRequestMsg">
    <wsdl:part element="tns:sendAsynkronOppdragsmeldingProsessOnline" name="sendAsynkronOppdragsmeldingProsessOnlineParameters"/>
  </wsdl:message>
    <wsdl:portType name="OppdragOnlineAsync">
    <wsdl:operation name="sendAsynkronOppdragsmeldingProsessOnline">
      <wsdl:input message="tns:sendAsynkronOppdragsmeldingProsessOnlineRequestMsg" name="sendAsynkronOppdragsmeldingProsessOnlineRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
