//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package ejbs.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "echoResponse", namespace = "http://ejbs")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "echoResponse", namespace = "http://ejbs")
public class EchoResponse {

    @XmlElement(name = "return", namespace = "")
    private ejbs.LGResponse _return;

    /**
     * 
     * @return
     *     returns LGResponse
     */
    public ejbs.LGResponse getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(ejbs.LGResponse _return) {
        this._return = _return;
    }

}
