<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_1.map" md5sum="64d0b32b7a46d14161aee1820875bb4c" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		XSLTransformation1_req_1.map
*   Map declaration(s):	XSLTransformation1_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Fwww.nav.no%252FStelvioContextPropagation%257DStelvioContext/message%3D%257Bhttp%253A%252F%252Fstelvio-example-contexthandler-prosess%252Fno%252Fnav%252Finf%252FStartExampleProcess%257DstartExampleProcessWRRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Fwww.nav.no%252FStelvioContextPropagation%257DStelvioContext/message%3D%257Bhttp%253A%252F%252Fstelvio-example-contexthandler-provider-lib%252Fno%252Fnav%252Finf%252FContextHandlerVerifier%257DcallWSChainRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"
    xmlns:in2="wsdl.http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"
    xmlns:out="wsdl.http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier"
    xmlns:out2="http://stelvio-example-contexthandler-provider-lib/no/nav/dataobject"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out3="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier"
    xmlns:io5="http://www.nav.no/StelvioContextPropagation"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://stelvio-example-contexthandler-mediationflow/xslt/XSLTransformation1_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="xalan str set in msl math map exsl in2 date"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation1_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation1_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation1_req_1">
    <io2:smo>
      <context>
        <!-- a structural mapping: "headers/SOAPHeader/value"(StelvioContext) to "transient"(StelvioContext) -->
        <xsl:if test="headers/SOAPHeader/value">
          <transient>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:StelvioContext'"/>
            </xsl:attribute>
            <xsl:call-template name="copyNamespaceDeclarations">
              <xsl:with-param name="root" select="headers/SOAPHeader/value"/>
            </xsl:call-template>
            <xsl:copy-of select="headers/SOAPHeader/value/@*|headers/SOAPHeader/value/node()"/>
          </transient>
        </xsl:if>
      </context>
      <headers>
        <SOAPHeader>
          <!-- a simple data mapping: "headers/SOAPHeader/nameSpace"(anyURI) to "nameSpace"(anyURI) -->
          <nameSpace>
            <xsl:value-of select="headers/SOAPHeader/nameSpace"/>
          </nameSpace>
          <!-- a simple data mapping: "headers/SOAPHeader/name"(NCName) to "name"(NCName) -->
          <name>
            <xsl:value-of select="headers/SOAPHeader/name"/>
          </name>
          <!-- a structural mapping: "headers/SOAPHeader/value"(StelvioContext) to "value"(StelvioContext) -->
          <xsl:if test="headers/SOAPHeader/value">
            <xsl:copy-of select="headers/SOAPHeader/value"/>
          </xsl:if>
        </SOAPHeader>
      </headers>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:callWSChainRequestMsg'"/>
        </xsl:attribute>
        <out3:callWSChain>
          <request>
            <!-- a simple data mapping: "body/in:startExampleProcessWR/inputString"(string) to "request"(string) -->
            <xsl:if test="body/in:startExampleProcessWR/inputString">
              <request>
                <xsl:value-of select="body/in:startExampleProcessWR/inputString"/>
              </request>
            </xsl:if>
          </request>
        </out3:callWSChain>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation1_req_12">
    <xsl:param name="smo"/>
    <context>
      <!-- a structural mapping: "$smo/headers/SOAPHeader/value"(StelvioContext) to "transient"(StelvioContext) -->
      <xsl:if test="$smo/headers/SOAPHeader/value">
        <transient>
          <xsl:attribute name="xsi:type">
            <xsl:value-of select="'io5:StelvioContext'"/>
          </xsl:attribute>
          <xsl:call-template name="copyNamespaceDeclarations">
            <xsl:with-param name="root" select="$smo/headers/SOAPHeader/value"/>
          </xsl:call-template>
          <xsl:copy-of select="$smo/headers/SOAPHeader/value/@*|$smo/headers/SOAPHeader/value/node()"/>
        </transient>
      </xsl:if>
    </context>
    <headers>
      <SOAPHeader>
        <!-- a simple data mapping: "$smo/headers/SOAPHeader/nameSpace"(anyURI) to "nameSpace"(anyURI) -->
        <nameSpace>
          <xsl:value-of select="$smo/headers/SOAPHeader/nameSpace"/>
        </nameSpace>
        <!-- a simple data mapping: "$smo/headers/SOAPHeader/name"(NCName) to "name"(NCName) -->
        <name>
          <xsl:value-of select="$smo/headers/SOAPHeader/name"/>
        </name>
        <!-- a structural mapping: "$smo/headers/SOAPHeader/value"(StelvioContext) to "value"(StelvioContext) -->
        <xsl:if test="$smo/headers/SOAPHeader/value">
          <xsl:copy-of select="$smo/headers/SOAPHeader/value"/>
        </xsl:if>
      </SOAPHeader>
    </headers>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:callWSChainRequestMsg'"/>
      </xsl:attribute>
      <out3:callWSChain>
        <request>
          <!-- a simple data mapping: "$smo/body/in:startExampleProcessWR/inputString"(string) to "request"(string) -->
          <xsl:if test="$smo/body/in:startExampleProcessWR/inputString">
            <request>
              <xsl:value-of select="$smo/body/in:startExampleProcessWR/inputString"/>
            </request>
          </xsl:if>
        </request>
      </out3:callWSChain>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
