<?xml version="1.0" encoding="UTF-8"?><definitions name="Metronome_Endpoint" targetNamespace="http://stelvio" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://stelvio">
    <import location="Metronome.wsdl" namespace="http://stelvio"/>
  <binding name="MetronomeWSEXP_MetronomeHttpPortBinding" type="tns:Metronome">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="tick">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="Metronome">
    <port binding="tns:MetronomeWSEXP_MetronomeHttpPortBinding" name="MetronomeSubscriber">
      <soap:address location="http://localhost:9080/stelvio-example-metronome-subscriber/Metronome"/>
    </port>
  </service>
</definitions>