<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Metronome" targetNamespace="http://stelvio" xmlns:tns="http://stelvio" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://stelvio">
      <xsd:element name="tick">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="time" nillable="true" type="xsd:dateTime"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="tickRequestMsg">
    <wsdl:part element="tns:tick" name="tickParameters"/>
  </wsdl:message>
    <wsdl:portType name="Metronome">
    <wsdl:operation name="tick">
      <wsdl:input message="tns:tickRequestMsg" name="tickRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>