<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="MetronomeWSEXP_MetronomeHttp_Service" targetNamespace="http://stelvio" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://stelvio" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="Metronome.wsdl" namespace="http://stelvio"/>
  <wsdl:binding name="MetronomeWSEXP_MetronomeHttpBinding" type="this:Metronome">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="tick">
      <soap:operation soapAction=""/>
      <wsdl:input name="tickRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MetronomeWSEXP_MetronomeHttpService">
    <wsdl:port binding="this:MetronomeWSEXP_MetronomeHttpBinding" name="MetronomeWSEXP_MetronomeHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-metronome-static-brokerWeb/sca/MetronomeWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>