<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/person/mediation/V2/findPersonResponse.map" md5sum="cf951e8eff5996fdb05864cf303340fd" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		findPersonResponse.map
*   Map declaration(s):	findPersonResponse
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV1%252FPersonService%257DfindPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fperson%252FV2%252FPersonService%257DfindPersonResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:in="http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:in2="wsdl.http://www.stelvio.no/example/person/V1/PersonService"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://www.stelvio.no/example/person/V1"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out="http://www.stelvio.no/example/person/V2/PersonService"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:out2="wsdl.http://www.stelvio.no/example/person/V2/PersonService"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://www.stelvio.no/example/person/mediation/V2/FindPersonResponse"
    exclude-result-prefixes="map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:findPersonResponse"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:findPersonResponse">
    <body>
      <!-- a structural mapping: "in:findPersonResponse"(<Anonymous>) to "out:findPersonResponse"(<Anonymous>) -->
      <xsl:apply-templates select="in:findPersonResponse" mode="localFindPersonResponseToFindPersonResponse_45017498"/>
    </body>
  </xsl:template>

  <!-- This rule represents an element mapping: "in:findPersonResponse" to "out:findPersonResponse".  -->
  <xsl:template match="in:findPersonResponse"  mode="localFindPersonResponseToFindPersonResponse_45017498">
    <out:findPersonResponse>
      <!-- a structural mapping: "findPersonResponse"(FindPersonResponse) to "findPersonResponse"(FindPersonResponse) -->
      <xsl:apply-templates select="findPersonResponse" mode="localFindPersonResponseToFindPersonResponse_1193089965"/>
    </out:findPersonResponse>
  </xsl:template>

  <!-- This rule represents an element mapping: "findPersonResponse" to "findPersonResponse".  -->
  <xsl:template match="findPersonResponse"  mode="localFindPersonResponseToFindPersonResponse_1193089965">
    <findPersonResponse>
      <!-- a for-each transform: "person"(Person) to "person"(Person) -->
      <xsl:apply-templates select="person" mode="localPersonToPerson_848809896"/>
      <!-- a simple data mapping: "totalHits"(int) to "totalHits"(int) -->
      <totalHits>
        <xsl:value-of select="totalHits"/>
      </totalHits>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="totalHits/following-sibling::*"/>
    </findPersonResponse>
  </xsl:template>

  <!-- This rule represents a for-each transform: "person" to "person".  -->
  <xsl:template match="person"  mode="localPersonToPerson_848809896">
    <person>
      <!-- a simple data mapping: "id"(string) to "id"(string) -->
      <id>
        <xsl:value-of select="id"/>
      </id>
      <!-- a structural mapping: "name"(Name) to "name"(Name) -->
      <xsl:apply-templates select="name" mode="localNameToName_948532826"/>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="name/following-sibling::*"/>
    </person>
  </xsl:template>

  <!-- This rule represents an element mapping: "name" to "name".  -->
  <xsl:template match="name"  mode="localNameToName_948532826">
    <name>
      <!-- a simple data mapping: "firstName"(string) to "firstName"(string) -->
      <firstName>
        <xsl:value-of select="firstName"/>
      </firstName>
      <!-- a simple data mapping: "middleName"(string) to "middleName"(string) -->
      <xsl:if test="middleName">
        <middleName>
          <xsl:value-of select="middleName"/>
        </middleName>
      </xsl:if>
      <!-- a simple data mapping: "lastName"(string) to "lastName"(string) -->
      <lastName>
        <xsl:value-of select="lastName"/>
      </lastName>
      <!-- a wildcard mapping: "any" to "any" -->
      <xsl:copy-of select="lastName/following-sibling::*"/>
    </name>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
