<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://nav-bproc-pen-testProc/no/nav/inf/TestProc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="TestProc" targetNamespace="http://nav-bproc-pen-testProc/no/nav/inf/TestProc">
    <wsdl:types>
    <xsd:schema xmlns:bons0="http://nav-lib-test/no/nav/lib/test/gbo" targetNamespace="http://nav-bproc-pen-testProc/no/nav/inf/TestProc" xmlns:tns="http://nav-bproc-pen-testProc/no/nav/inf/TestProc" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://nav-lib-test/no/nav/lib/test/gbo" schemaLocation="../gbo/GBOTestProcRequest.xsd"/>
            <xsd:element name="invokeTestProc">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="testProcRequest" nillable="true" type="bons0:GBOTestProcRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="invokeTestProcRequestMsg">
    <wsdl:part element="tns:invokeTestProc" name="invokeTestProcParameters"/>
  </wsdl:message>
    <wsdl:portType name="TestProc">
    <wsdl:operation name="invokeTestProc">
      <wsdl:input message="tns:invokeTestProcRequestMsg" name="invokeTestProcRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
