<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="OrderQuery" targetNamespace="http://www.stelvio.no/example/order/V1/OrderQuery" xmlns:tns="http://www.stelvio.no/example/order/V1/OrderQuery" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.stelvio.no/example/order/V1/OrderQuery" xmlns:order="http://www.stelvio.no/example/order/V1">
      <xsd:import namespace="http://www.stelvio.no/example/order/V1" schemaLocation="../V1.xsd"/>
      <xsd:element name="getOrder" type="xsd:string"/>
      <xsd:element name="getOrderResponse" type="order:Order"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="getOrderRequest">
    <wsdl:part element="tns:getOrder" name="orderId"/>
  </wsdl:message>
  <wsdl:message name="getOrderResponse">
    <wsdl:part element="tns:getOrderResponse" name="order"/>
  </wsdl:message>
  <wsdl:portType name="OrderQuery">
    <wsdl:operation name="getOrder">
      <wsdl:input message="tns:getOrderRequest"/>
      <wsdl:output message="tns:getOrderResponse"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>