<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="OrderQueryBinding" targetNamespace="http://order/V1/OrderQuery/OrderQueryBinding/" xmlns:orderQuery="http://www.stelvio.no/example/order/V1/OrderQuery" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://order/V1/OrderQuery/OrderQueryBinding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="OrderQuery.wsdl" namespace="http://www.stelvio.no/example/order/V1/OrderQuery"/>
  <wsdl:binding name="OrderQueryBinding" type="orderQuery:OrderQuery">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getOrder">
      <soap:operation soapAction="http://order/V1/OrderQuery/OrderQueryBinding/getOrder/"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="service">
    <wsdl:port binding="tns:OrderQueryBinding" name="OrderQueryPort">
      <soap:address location="http://order/V1/OrderQuery/OrderQueryBinding/service/OrderQueryPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>