<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-cons-deploy-verifikasjon/nav/no/deploy/inf/Verifikasjon" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://nav-cons-deploy-verifikasjon/nav/no/deploy/inf/Verifikasjon/Binding" name="VerfikasjonWSExp_VerifikasjonHttp_Service" targetNamespace="http://nav-cons-deploy-verifikasjon/nav/no/deploy/inf/Verifikasjon/Binding">
  <wsdl:import location="Verifikasjon.wsdl" namespace="http://nav-cons-deploy-verifikasjon/nav/no/deploy/inf/Verifikasjon"/>
  <wsdl:binding name="VerfikasjonWSExp_VerifikasjonHttpBinding" type="Port_0:Verifikasjon">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="opWS">
      <soap:operation soapAction=""/>
      <wsdl:input name="opWSRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opWSResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultVerfikasjonGeneriskWS">
        <soap:fault name="faultVerfikasjonGeneriskWS" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opCEI">
      <soap:operation soapAction=""/>
      <wsdl:input name="opCEIRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opCEIResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultVerfikasjonGeneriskCEI">
        <soap:fault name="faultVerfikasjonGeneriskCEI" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opFEM">
      <soap:operation soapAction=""/>
      <wsdl:input name="opFEMRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opFEMResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultVerfikasjonGeneriskFEM">
        <soap:fault name="faultVerfikasjonGeneriskFEM" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opSCA">
      <soap:operation soapAction=""/>
      <wsdl:input name="opSCARequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opSCAResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultVerfikasjonGeneriskSCA">
        <soap:fault name="faultVerfikasjonGeneriskSCA" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="VerfikasjonWSExp_VerifikasjonHttpService">
    <wsdl:port binding="this:VerfikasjonWSExp_VerifikasjonHttpBinding" name="VerfikasjonWSExp_VerifikasjonHttpPort">
      <soap:address location="http://localhost:9080/nav-cons-deploy-verifikasjonWeb/sca/VerfikasjonWSExp"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
