<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://myConsumerModule/LRBPELArtifacts" xmlns:wsdl0="http://myLibrary/ConsumerInterface" xmlns:wsdl1="http://myLibrary/ProducerInterface" name="LRBPEL" targetNamespace="http://myConsumerModule/LRBPELArtifacts">
  <plnk:partnerLinkType name="ConsumerInterfacePLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:ConsumerInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="ProducerInterfacePLT2">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl1:ProducerInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
  <plnk:partnerLinkType name="ProducerInterfacePLT3">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl1:ProducerInterface"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="ConsumerInterface.wsdl" namespace="http://myLibrary/ConsumerInterface"/>
    <wsdl:import location="ProducerInterface.wsdl" namespace="http://myLibrary/ProducerInterface"/>
</wsdl:definitions>
