<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="StartExampleJavaWSEXP_StartExampleJavaHttp_Service" targetNamespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="StartExampleJava.wsdl" namespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"/>
  <wsdl:binding name="StartExampleJavaWSEXP_StartExampleJavaHttpBinding" type="this:StartExampleJava">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="startExampleProcessWR">
      <soap:operation soapAction=""/>
      <wsdl:input name="startExampleProcessWRRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="startExampleProcessWRResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="StartExampleJavaWSEXP_StartExampleJavaHttpService">
    <wsdl:port binding="this:StartExampleJavaWSEXP_StartExampleJavaHttpBinding" name="StartExampleJavaWSEXP_StartExampleJavaHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-contexthandler-mediationflowWeb/sca/StartExampleJavaWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>