//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package no.stelvio.example.services.v1.echoservice.binding2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import no.stelvio.example.services.v1.echoservice.ObjectFactory;

@WebService(name = "EchoService", targetNamespace = "http://www.stelvio.no/example/services/V1/EchoService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EchoService {


    /**
     * 
     * @param input
     * @return
     *     returns java.lang.String
     * @throws EchoEchoFault1Msg
     */
    @WebMethod
    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://www.stelvio.no/example/services/V1/EchoService", className = "no.stelvio.example.services.v1.echoservice.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://www.stelvio.no/example/services/V1/EchoService", className = "no.stelvio.example.services.v1.echoservice.EchoResponse")
    public String echo(
        @WebParam(name = "input", targetNamespace = "")
        String input)
        throws EchoEchoFault1Msg
    ;

}
