<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://nav-lib-pen/no/nav/lib/pen/gbo" xmlns:bons2="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakTest" xmlns:tns="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="IverksettVedtak" targetNamespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow">
  <wsdl:types>
    <xsd:schema xmlns:bons2="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow" xmlns:tns="http://nav-lib-pen/no/nav/lib/pen/inf/IverksettVedtak" targetNamespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow" xmlns:bons1="http://nav-lib-pen/no/nav/lib/pen/gbo" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://nav-lib-pen/no/nav/lib/pen/gbo" schemaLocation="../lib/pen/gbo/GBOIverksettVedtakRequest.xsd"/>
      <xsd:element name="invokeIverksettVedtak">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="iverksettVedtakRequest" nillable="true" type="bons1:GBOIverksettVedtakRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
        </xsd:schema>
  </wsdl:types>
    <wsdl:message name="invokeIverksettVedtakRequestMsg">
    <wsdl:part element="tns:invokeIverksettVedtak" name="invokeIverksettVedtakParameters"/>
  </wsdl:message>
    <wsdl:portType name="IverksettVedtakMicroflow">
    <wsdl:operation name="invokeIverksettVedtak">
      <wsdl:input message="tns:invokeIverksettVedtakRequestMsg" name="invokeIverksettVedtakRequest"/>
    </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
