<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow/Binding" name="iverksettVedtakMicroflowWSEXP_IverksettVedtakMicroflowHttp_Service" targetNamespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow/Binding">
  <wsdl:import location="IverksettVedtakMicroflow.wsdl" namespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakMicroflow"/>
  <wsdl:binding name="iverksettVedtakMicroflowWSEXP_IverksettVedtakMicroflowHttpBinding" type="Port_0:IverksettVedtakMicroflow">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="invokeIverksettVedtak">
      <soap:operation soapAction=""/>
      <wsdl:input name="invokeIverksettVedtakRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="iverksettVedtakMicroflowWSEXP_IverksettVedtakMicroflowHttpService">
    <wsdl:port binding="this:iverksettVedtakMicroflowWSEXP_IverksettVedtakMicroflowHttpBinding" name="iverksettVedtakMicroflowWSEXP_IverksettVedtakMicroflowHttpPort">
      <soap:address location="http://localhost:9080/nav-bproc-test-ppen015-microflowWeb/sca/iverksettVedtakMicroflowWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
