<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Test" targetNamespace="http://stelvio-example-echo-proxy-ejb-jaxb/Test" xmlns:tns="http://stelvio-example-echo-proxy-ejb-jaxb/Test" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://stelvio-example-echo-proxy-ejb-jaxb/Test">
      <xsd:element name="test">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="numInvokes" nillable="true" type="xsd:int"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="testRequestMsg">
    <wsdl:part element="tns:test" name="testParameters"/>
  </wsdl:message>
    <wsdl:portType name="Test">
    <wsdl:operation name="test">
      <wsdl:input message="tns:testRequestMsg" name="testRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>