//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package no.nav.provider.pensjon.vedlikehold.ejb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "hentPenPersonResponse", namespace = "http://ejb/vedlikehold/pensjon/provider/nav/no")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hentPenPersonResponse", namespace = "http://ejb/vedlikehold/pensjon/provider/nav/no")
public class HentPenPersonResponse {

    @XmlElement(name = "return", namespace = "")
    private no.nav.dto.pensjon.vedlikehold.to.HentPenPersonResponseDto _return;

    /**
     * 
     * @return
     *     returns HentPenPersonResponseDto
     */
    public no.nav.dto.pensjon.vedlikehold.to.HentPenPersonResponseDto getReturn() {
        return this._return;
    }

    /**
     * 
     * @param _return
     *     the value for the _return property
     */
    public void setReturn(no.nav.dto.pensjon.vedlikehold.to.HentPenPersonResponseDto _return) {
        this._return = _return;
    }

}
