<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ExampleBP" targetNamespace="http://stelvio-example-contexthandler-prosess/no/nav/bpel/ExampleBPArtifacts" xmlns:plnk="http://schemas.xmlsoap.org/ws/2004/03/partner-link/" xmlns:tns="http://stelvio-example-contexthandler-prosess/no/nav/bpel/ExampleBPArtifacts" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl0="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:wsdl1="http://nav.no/domene/pensjon/tjenester/sak/v1" xmlns:wsdl2="http://nav.no/domene/pensjon/tjenester/krav/v1" xmlns:wsdl3="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <plnk:partnerLinkType name="StartExampleProcessPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl0:StartExampleProcess"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="ContextHandlerVerifierProviderPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl3:ContextHandlerVerifierProvider"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <plnk:partnerLinkType name="SakPLT">
    <plnk:role name="Interface">
      <plnk:portType name="wsdl1:Sak"/>
    </plnk:role>
  </plnk:partnerLinkType>
    <wsdl:import location="../inf/StartExampleProcess.wsdl" namespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"/>
    <wsdl:import location="../inf/ContextHandlerVerifierProvider.wsdl" namespace="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier"/>
    <wsdl:import location="../../../domene/pensjon/tjenester/sak/sak.wsdl" namespace="http://nav.no/domene/pensjon/tjenester/sak/v1"/>
</wsdl:definitions>