<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Export1_StartExampleProcessHttp_Service" targetNamespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess/Binding" xmlns:Port_0="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="StartExampleProcess.wsdl" namespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"/>
  <wsdl:binding name="Export1_StartExampleProcessHttpBinding" type="Port_0:StartExampleProcess">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="startExampleProcess">
      <soap:operation soapAction=""/>
      <wsdl:input name="startExampleProcessRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Export1_StartExampleProcessHttpService">
    <wsdl:port binding="this:Export1_StartExampleProcessHttpBinding" name="ExampleProcessWSEXP_StartExampleProcessHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-contexthandler-prosessWeb/sca/ExampleProcessWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>