<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="StartExampleProcess" targetNamespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:tns="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
    <xsd:schema targetNamespace="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess">
      <xsd:element name="startExampleProcess">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="input1" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="startExampleProcessRequestMsg">
    <wsdl:part element="tns:startExampleProcess" name="startExampleProcessParameters"/>
  </wsdl:message>
    <wsdl:portType name="StartExampleProcess">
    <wsdl:operation name="startExampleProcess">
      <wsdl:input message="tns:startExampleProcessRequestMsg" name="startExampleProcessRequest"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>