<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://nav-lib-sto/no/nav/lib/sto/gbo" xmlns:tns="http://nav-bproc-pen-ppen015/no/nav/inf/SamordningAsync" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SamordningAsync" targetNamespace="http://nav-bproc-pen-ppen015/no/nav/inf/SamordningAsync">
    <wsdl:types>
    <xsd:schema targetNamespace="http://nav-bproc-pen-ppen015/no/nav/inf/SamordningAsync" xmlns:bons1="http://nav-lib-sto/no/nav/lib/sto/gbo" xmlns:tns="http://nav-bproc-pen-ppen015/no/nav/inf/SamordningAsync" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:import namespace="http://nav-lib-sto/no/nav/lib/sto/gbo" schemaLocation="../lib/sto/gbo/GBOOpprettVedtakSamordningRequest.xsd"/>
      <xsd:element name="opprettVedtakSamordning">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="opprettVedtakSamordningRequest" nillable="true" type="bons1:GBOOpprettVedtakSamordningRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
    <wsdl:message name="opprettVedtakSamordningRequestMsg">
    <wsdl:part element="tns:opprettVedtakSamordning" name="opprettVedtakSamordningParameters"/>
  </wsdl:message>
    <wsdl:message name="opprettVedtakSamordningResponseMsg"/>
    <wsdl:portType name="SamordningAsync">
    <wsdl:operation name="opprettVedtakSamordning">
      <wsdl:input message="tns:opprettVedtakSamordningRequestMsg" name="opprettVedtakSamordningRequest"/>
            <wsdl:output message="tns:opprettVedtakSamordningResponseMsg" name="opprettVedtakSamordningResponse"/>
        </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
