<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/mediation/xslt/CopyInputToOutputImpl.map" md5sum="7e5e11c00107909fcf1aad3ac231b390" version="7.0.300" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.300
*
*   Mapping file:		CopyInputToOutputImpl.map
*   Map declaration(s):	CopyInputToOutputImpl
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fservices%252FV1%252FEchoService%257DechoRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Fservices%252FV1%252FEchoService%257DechoResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:regexp="http://exslt.org/regular-expressions"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io2="wsdl.http://www.stelvio.no/example/services/V1/EchoService"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:io7="http://www.stelvio.no/example/services/V1/EchoService"
    xmlns:map="http://www.stelvio.no/example/mediation/xslt/CopyInputToOutputImpl"
    exclude-result-prefixes="xalan str set math regexp map exsl date"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:CopyInputToOutputImpl"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:CopyInputToOutputImpl">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io2:echoResponseMsg'"/>
      </xsl:attribute>
      <io7:echoResponse>
        <!-- a simple data mapping: "io7:echo/input"(string) to "output"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space(io7:echo/input)">
            <output>
              <xsl:value-of select="io7:echo/input"/>
            </output>
          </xsl:when>
          <xsl:otherwise>
            <output xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
      </io7:echoResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
