package no.nav.maven.plugin.sca.attributes;

import java.io.File;
import java.io.IOException;

import no.nav.maven.utilities.sca.ScaAttributesBuilder;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.project.MavenProject;

/**
 * Goal which updates the ear file generated by service deploy.
 * 
 * @author test@example.com
 * 
 * @goal generate-sca-attributes
 * @requiresDependencyResolution
 */
public class GenerateScaAttributesMojo extends AbstractMojo {
	/**
	 * @parameter expression="${project}"
	 * @required
	 * @readonly
	 */
	private MavenProject project;
	
	/**
	 * @parameter expression="${project.build.outputDirectory}"
	 * @required
	 * @readonly
	 */
	private File outputDirectory;

	public void execute() throws MojoExecutionException, MojoFailureException {
		// This "stupid" if test is here because I want to configure the plugin
		// execution element i parent POMs
		if (!"pom".equals(project.getPackaging())) {
			executeInternal();
		}
	}

	private void executeInternal() throws MojoExecutionException {
		try {
			if (!outputDirectory.exists()) {
				outputDirectory.mkdirs();
			}
			new ScaAttributesBuilder(project).setVersioned(true).writeToDirectory(outputDirectory);
		} catch (IOException e) {
			throw new MojoExecutionException("Unable to write SCA Attributes file", e);
		}
	}
}
