<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TPSamordningRegistreringWSEXP_TPSamordningRegistreringHttp_Service" targetNamespace="http://nav.no/elsam/tpsamordningregistrering/V0_2/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:Port_0="http://nav.no/elsam/tpsamordningregistrering/V0_2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://nav.no/elsam/tpsamordningregistrering/V0_2/Binding" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://nav.no/elsam/tpsamordningregistrering/V0_2" location="../inf/TPSamordningRegistrering.wsdl"/>
  <wsdl:binding name="TPSamordningRegistreringWSEXP_TPSamordningRegistreringHttpBinding" type="Port_0:TPSamordningRegistrering">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="lagreTPYtelse">
      <soap:operation soapAction=""/>
      <wsdl:input name="lagreTPYtelseRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="lagreTPYtelseResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultTPYtelseAlleredeRegistrert">
        <soap:fault name="faultTPYtelseAlleredeRegistrert" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="slettTPYtelse">
      <soap:operation soapAction=""/>
      <wsdl:input name="slettTPYtelseRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="slettTPYtelseResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultTPYtelseIkkeFunnet">
        <soap:fault name="faultTPYtelseIkkeFunnet" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="hentSamordningsdata">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentSamordningsdataRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentSamordningsdataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultTPForholdIkkeIverksatt">
        <soap:fault name="faultTPForholdIkkeIverksatt" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettRefusjonskrav">
      <soap:operation soapAction=""/>
      <wsdl:input name="opprettRefusjonskravRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettRefusjonskravResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultSamordningsIdIkkeFunnet">
        <soap:fault name="faultSamordningsIdIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultRefusjonskravUtenforTidsfrist">
        <soap:fault name="faultRefusjonskravUtenforTidsfrist" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultSamordningsIdOgPersonKorrelererIkke">
        <soap:fault name="faultSamordningsIdOgPersonKorrelererIkke" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultAlleredeMottattRefusjonskrav">
        <soap:fault name="faultAlleredeMottattRefusjonskrav" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultRefusjonskravUtenforSamordningspliktigPeriode">
        <soap:fault name="faultRefusjonskravUtenforSamordningspliktigPeriode" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TPSamordningRegistreringWSEXP_TPSamordningRegistreringHttpService">
    <wsdl:port name="TPSamordningRegistreringWSEXP_TPSamordningRegistreringHttpPort" binding="this:TPSamordningRegistreringWSEXP_TPSamordningRegistreringHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-elsam-tptilb-tpsamordningregistreringV0_2Web/sca/TPSamordningRegistreringWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
