//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package no.stelvio.example.services.v1.echoservice.binding2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "EchoServiceWSEXP_EchoServiceHttpService", targetNamespace = "http://www.stelvio.no/example/services/V1/EchoService/Binding2", wsdlLocation = "WEB-INF/wsdl/stelvio-example-echo-service_EchoServiceWSEXP.wsdl")
public class EchoServiceWSEXPEchoServiceHttpService
    extends Service
{

    private final static URL ECHOSERVICEWSEXPECHOSERVICEHTTPSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = no.stelvio.example.services.v1.echoservice.binding2.EchoServiceWSEXPEchoServiceHttpService.class.getResource("/WEB-INF/wsdl/stelvio-example-echo-service_EchoServiceWSEXP.wsdl");
            if (url == null) throw new MalformedURLException("/WEB-INF/wsdl/stelvio-example-echo-service_EchoServiceWSEXP.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ECHOSERVICEWSEXPECHOSERVICEHTTPSERVICE_WSDL_LOCATION = url;
    }

    public EchoServiceWSEXPEchoServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EchoServiceWSEXPEchoServiceHttpService() {
        super(ECHOSERVICEWSEXPECHOSERVICEHTTPSERVICE_WSDL_LOCATION, new QName("http://www.stelvio.no/example/services/V1/EchoService/Binding2", "EchoServiceWSEXP_EchoServiceHttpService"));
    }

    /**
     * 
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceWSEXP_EchoServiceHttpPort")
    public EchoService getEchoServiceWSEXPEchoServiceHttpPort() {
        return (EchoService)super.getPort(new QName("http://www.stelvio.no/example/services/V1/EchoService/Binding2", "EchoServiceWSEXP_EchoServiceHttpPort"), EchoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EchoService
     */
    @WebEndpoint(name = "EchoServiceWSEXP_EchoServiceHttpPort")
    public EchoService getEchoServiceWSEXPEchoServiceHttpPort(WebServiceFeature... features) {
        return (EchoService)super.getPort(new QName("http://www.stelvio.no/example/services/V1/EchoService/Binding2", "EchoServiceWSEXP_EchoServiceHttpPort"), EchoService.class, features);
    }

}
