//
// Generated By:JAX-WS RI IBM 2.1.1 in JDK 6 (JAXB RI IBM JAXB 2.1.3 in JDK 1.6)
//


package com.ibm.websphere.wsn.notification_broker;

import javax.xml.ws.WebFault;
import org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType;

@WebFault(name = "InvalidMessageContentExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidMessageContentExpressionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidMessageContentExpressionFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidMessageContentExpressionFault(String message, InvalidMessageContentExpressionFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public InvalidMessageContentExpressionFault(String message, InvalidMessageContentExpressionFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType
     */
    public InvalidMessageContentExpressionFaultType getFaultInfo() {
        return faultInfo;
    }

}
