<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="Service" targetNamespace="http://lib1/Service" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:portType name="Service"/>
</wsdl:definitions>