<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ArkivWSEXP_ArkivHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/arkiv/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/arkiv/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="virksomhet/tjenester/arkiv/arkiv.wsdl" namespace="http://nav.no/virksomhet/tjenester/arkiv/v1"/>
  <wsdl:binding name="ArkivWSEXP_ArkivHttpBinding" type="this:Arkiv">

  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="bestillBrev">

  		<soap:operation
  			soapAction="http://nav.no/virksomhet/tjenester/arkiv/v1/bestillBrev" />
  		<wsdl:input>

  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal" />
  		</wsdl:output>
  		<wsdl:fault name="adresseIkkeRegistrert">

  			<soap:fault use="literal" name="adresseIkkeRegistrert" />
  		</wsdl:fault>
  		<wsdl:fault name="henteBrevdataFeilet">

  			<soap:fault use="literal" name="henteBrevdataFeilet" />
  		</wsdl:fault>
  		<wsdl:fault name="manglerObligatoriskInput">

  			<soap:fault use="literal" name="manglerObligatoriskInput" />
  		</wsdl:fault>
  		<wsdl:fault name="generiskFeil">

  			<soap:fault use="literal" name="generiskFeil" />
  		</wsdl:fault>
  		<wsdl:fault name="opprettelseJournalpostFeilet">

  			<soap:fault use="literal"
  				name="opprettelseJournalpostFeilet" />
  		</wsdl:fault>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ArkivWSEXP_ArkivHttpService">
    <wsdl:port binding="this:ArkivWSEXP_ArkivHttpBinding" name="ArkivWSEXP_ArkivHttpPort">
      <soap:address location="http://localhost:9080/nav-tjeneste-arkivWeb/sca/ArkivWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>