<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="FullmaktWSEXP_FullmaktHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/fullmakt/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/fullmakt/v1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="virksomhet/tjenester/fullmakt/fullmakt.wsdl" namespace="http://nav.no/virksomhet/tjenester/fullmakt/v1"/>
  <wsdl:binding name="FullmaktWSEXP_FullmaktHttpBinding"
  	type="this:Fullmakt">

  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="finnFullmaktmottagere">

  		<soap:operation
  			soapAction="http://nav.no/virksomhet/tjenester/fullmakt/v1/finnFullmaktmottagere" />
  		<wsdl:input>

  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal" />
  		</wsdl:output>
  		<wsdl:fault name="generiskFeil">

  			<soap:fault use="literal" name="generiskFeil" />
  		</wsdl:fault>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="FullmaktWSEXP_FullmaktHttpService">
    <wsdl:port binding="this:FullmaktWSEXP_FullmaktHttpBinding" name="FullmaktWSEXP_FullmaktHttpPort">
      <soap:address location="http://localhost:9080/nav-tjeneste-fullmaktWeb/sca/FullmaktWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>