<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="IverksettingWSEXP_IverksettingHttp_Service" targetNamespace="http://nav.no/domene/pensjon/tjenester/iverksetting/v1/Binding" xmlns:Port_0="http://nav.no/domene/pensjon/tjenester/iverksetting/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/domene/pensjon/tjenester/iverksetting/v1/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="domene/pensjon/tjenester/iverksetting/iverksetting.wsdl" namespace="http://nav.no/domene/pensjon/tjenester/iverksetting/v1"/>
  <wsdl:binding name="IverksettingWSEXP_IverksettingHttpBinding" type="Port_0:Iverksetting">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="behandleOppdragKvittering">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="genererOppdragsmelding">
      <soap:operation soapAction=""/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="IverksettingWSEXP_IverksettingHttpService">
    <wsdl:port binding="this:IverksettingWSEXP_IverksettingHttpBinding" name="IverksettingWSEXP_IverksettingHttpPort">
      <soap:address location="http://localhost:9080/pensjon-tjeneste-iverksettingWeb/sca/IverksettingWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>