<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="OppdragWSEXP_OppdragHttp_Service" targetNamespace="http://nav.no/virksomhet/tjenester/oppdrag/v1/Binding" xmlns:Port_0="http://nav.no/virksomhet/tjenester/oppdrag/v1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:this="http://nav.no/virksomhet/tjenester/oppdrag/v1/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="virksomhet/tjenester/oppdrag/oppdrag.wsdl" namespace="http://nav.no/virksomhet/tjenester/oppdrag/v1"/>
  <wsdl:binding name="OppdragWSEXP_OppdragHttpBinding"
  	type="Port_0:Oppdrag">

  	<soap:binding style="document"
  		transport="http://schemas.xmlsoap.org/soap/http" />
  	<wsdl:operation name="sendAsynkronOppdragsmeldingProsess">

  		<soap:operation
  			soapAction="http://nav.no/virksomhet/tjenester/oppdrag/v1/Binding/sendAsynkronOppdragsmeldingProsess" />
  		<wsdl:input>

  			<soap:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>

  			<soap:body use="literal" />
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OppdragWSEXP_OppdragHttpService">
    <wsdl:port binding="this:OppdragWSEXP_OppdragHttpBinding" name="OppdragWSEXP_OppdragHttpPort">
      <soap:address location="http://localhost:9080/pensjon-prosess-iverksettVedtakWeb/sca/OppdragWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>