<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/order/V1/CreateOrderStubTransform.map" md5sum="f228468542d947317f07c3e165e16123" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		CreateOrderStubTransform.map
*   Map declaration(s):	CreateOrderStubTransform
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Forder%252FV1%252FOrderCommand%257DcreateOrderRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Forder%252FV1%252FOrderCommand%257DcreateOrderResponseMsg/xpath%3D%252Fbody/smo.xsd
*   XSLT import(s):   	OrderStubTransform.xsl
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io="http://www.stelvio.no/example/order/V1/OrderCommand"
    xmlns:io2="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io5="wsdl.http://www.stelvio.no/example/order/V1/OrderCommand"
    xmlns:io6="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io8="http://www.stelvio.no/example/order/V1"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io9="http://www.w3.org/2005/08/addressing"
    xmlns:io10="http://www.stelvio.no/example/common/V1"
    xmlns:map0="http://www.stelvio.no/example/order/V1/OrderStubTransform"
    xmlns:map="http://www.stelvio.no/example/order/V1/CreateOrderStubTransform"
    exclude-result-prefixes="map0 map xalan"
    version="1.0">

  <!-- imports  -->
  <xsl:import href="OrderStubTransform.xsl"/>
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:CreateOrderStubTransform"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:CreateOrderStubTransform">
    <body>
      <io:createOrderResponse>
        <!-- a structural mapping: "io:createOrder"(<Anonymous>) to "order"(Order) -->
        <order>
          <xsl:call-template name="map0:OrderStubTransform">
            <xsl:with-param name="anyType" select="io:createOrder"/>
          </xsl:call-template>
        </order>
      </io:createOrderResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
