<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/stelvio/example/order/V1/OrderQueryStubTransform.map" md5sum="0211de9a74df3ea0400e855846793e6b" version="7.0.101" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.101
*
*   Mapping file:		OrderQueryStubTransform.map
*   Map declaration(s):	OrderQueryStubTransform
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Forder%252FV1%252FOrderQuery%257DgetOrderRequestMsg/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fwww.stelvio.no%252Fexample%252Forder%252FV1%252FOrderQuery%257DgetOrderResponseMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io3="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io2="wsdl.http://www.stelvio.no/example/order/V1/OrderQuery"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:io7="http://www.stelvio.no/example/order/V1"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io9="http://www.w3.org/2005/08/addressing"
    xmlns:io8="http://www.stelvio.no/example/order/V1/OrderQuery"
    xmlns:io10="http://www.stelvio.no/example/common/V1"
    xmlns:map="http://www.stelvio.no/example/order/V1/OrderQueryStubTransform"
    exclude-result-prefixes="map xalan"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root template  -->
  <xsl:template match="/">
    <xsl:apply-templates select="body" mode="map:OrderQueryStubTransform"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:OrderQueryStubTransform">
    <body>
      <io8:getOrderResponse>
        <order>
          <!-- a simple data mapping: "io8:getOrder/orderId"(string) to "id"(string) -->
          <id>
            <xsl:value-of select="io8:getOrder/orderId"/>
          </id>
          <!-- a simple mapping with no associated source:  to "customerId"(string) -->
          <customerId>
            <xsl:text>customerId</xsl:text>
          </customerId>
          <orderLineItem>
            <!-- a simple mapping with no associated source:  to "id"(string) -->
            <id>
              <xsl:text>orderLineItemId</xsl:text>
            </id>
            <!-- a simple mapping with no associated source:  to "productId"(string) -->
            <productId>
              <xsl:text>productId</xsl:text>
            </productId>
            <!-- a simple mapping with no associated source:  to "quantity"(int) -->
            <quantity>
              <xsl:text>10</xsl:text>
            </quantity>
            <additionalInfo>
              <discount>
                <!-- a simple mapping with no associated source:  to "sinceVersion"(string) -->
                <xsl:attribute name="sinceVersion">
                  <xsl:value-of select="'1.1'"/>
                </xsl:attribute>
                <!-- a simple content mapping -->
                <xsl:text>0.30</xsl:text>
              </discount>
            </additionalInfo>
          </orderLineItem>
        </order>
      </io8:getOrderResponse>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
