<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:bons1="http://myLibrary" xmlns:bons2="http://myLibrary/ConsumerrInterface" xmlns:tns="http://myLibrary/ConsumerInterface" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ConsumerInterface" targetNamespace="http://myLibrary/ConsumerInterface">
    <wsdl:types>
    <xsd:schema xmlns:bons2="http://myLibrary/ConsumerInterface" xmlns:tns="http://myLibrary/ProducerInterface" targetNamespace="http://myLibrary/ConsumerInterface" xmlns:bons1="http://myLibrary" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://myLibrary" schemaLocation="GBOTwoWayRequest.xsd"/>
            <xsd:element name="oneWay">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="oneWayRequest" nillable="true" type="bons1:GBOTwoWayRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
        </xsd:schema>
  </wsdl:types>
    <wsdl:message name="oneWayRequestMsg">
    <wsdl:part element="tns:oneWay" name="oneWayParameters"/>
  </wsdl:message>
    <wsdl:portType name="ConsumerInterface">
        <wsdl:operation name="oneWay">
      <wsdl:input message="tns:oneWayRequestMsg" name="oneWayRequest"/>
    </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
