<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://myLibrary/ConsumerInterface" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://myLibrary/ConsumerInterface/Binding" name="LRBPELWSEXP_ConsumerInterfaceHttp_Service" targetNamespace="http://myLibrary/ConsumerInterface/Binding">
  <wsdl:import location="ConsumerInterface.wsdl" namespace="http://myLibrary/ConsumerInterface"/>
  <wsdl:binding name="LRBPELWSEXP_ConsumerInterfaceHttpBinding" type="Port_0:ConsumerInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="oneWay">
      <soap:operation soapAction=""/>
      <wsdl:input name="oneWayRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="LRBPELWSEXP_ConsumerInterfaceHttpService">
    <wsdl:port binding="this:LRBPELWSEXP_ConsumerInterfaceHttpBinding" name="LRBPELWSEXP_ConsumerInterfaceHttpPort">
      <soap:address location="http://localhost:9080/nav-broc-fault-testWeb/sca/LRBPELWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
