<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="RegistrereTPForholdWSEXP_RegistrereTPForholdHttp_Service" targetNamespace="http://nav.no/elsam/registreretpforhold/V0_1/Binding" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:Port_0="http://nav.no/elsam/registreretpforhold/V0_1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:this="http://nav.no/elsam/registreretpforhold/V0_1/Binding" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://nav.no/elsam/registreretpforhold/V0_1" location="no/nav/registreretpforhold/V0_1/inf/RegistrereTPForhold.wsdl"/>
  <wsdl:binding name="RegistrereTPForholdWSEXP_RegistrereTPForholdHttpBinding" type="Port_0:RegistrereTPForhold">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="hentTPForholdListe">
      <soap:operation soapAction=""/>
      <wsdl:input name="hentTPForholdListeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="hentTPForholdListeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultTjenestepensjonForholdIkkeFunnet">
        <soap:fault name="faultTjenestepensjonForholdIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="opprettTPForhold">
      <soap:operation soapAction=""/>
      <wsdl:input name="opprettTPForholdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="opprettTPForholdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultPersonIkkeFunnet">
        <soap:fault name="faultPersonIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="slettTPForhold">
      <soap:operation soapAction=""/>
      <wsdl:input name="slettTPForholdRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="slettTPForholdResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="faultKanIkkeSlettes">
        <soap:fault name="faultKanIkkeSlettes" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultTjenestepensjonForholdIkkeFunnet">
        <soap:fault name="faultTjenestepensjonForholdIkkeFunnet" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="faultGenerisk">
        <soap:fault name="faultGenerisk" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RegistrereTPForholdWSEXP_RegistrereTPForholdHttpService">
    <wsdl:port name="RegistrereTPForholdWSEXP_RegistrereTPForholdHttpPort" binding="this:RegistrereTPForholdWSEXP_RegistrereTPForholdHttpBinding">
      <soap:address location="http://localhost:9080/nav-cons-elsam-tptilb-registreretpforholdV0_1Web/sca/RegistrereTPForholdWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
