<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ErrorIFHandlerEXP_ErrorIFHttp_Service" targetNamespace="http://errorModuleJAXRPC/ErrorIF/Binding3" xmlns:Port_0="http://errorModuleJAXRPC/ErrorIF" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://errorModuleJAXRPC/ErrorIF/Binding3" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ErrorIF.wsdl" namespace="http://errorModuleJAXRPC/ErrorIF"/>
  <wsdl:binding name="ErrorIFHandlerEXP_ErrorIFHttpBinding" type="Port_0:ErrorIF">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="operation1">
      <soap:operation soapAction=""/>
      <wsdl:input name="operation1Request">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="operation1Response">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ErrorIFHandlerEXP_ErrorIFHttpService">
    <wsdl:port binding="this:ErrorIFHandlerEXP_ErrorIFHttpBinding" name="ErrorIFHandlerEXP_ErrorIFHttpPort">
      <soap:address location="http://localhost:9080/errorModuleJAXRPCWeb/sca/ErrorIFHandlerEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>