<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:Port_0="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakTest" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakTest/Binding" name="iverksettVedtakWSEXP_IverksettVedtakTestHttp_Service" targetNamespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakTest/Binding">
  <wsdl:import location="IverksettVedtakTest.wsdl" namespace="http://nav-bproc-test-ppen015/no/nav/inf/IverksettVedtakTest"/>
  <wsdl:binding name="iverksettVedtakWSEXP_IverksettVedtakTestHttpBinding" type="Port_0:IverksettVedtakTest">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="invokeIverksettVedtak">
      <soap:operation soapAction=""/>
      <wsdl:input name="invokeIverksettVedtakRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="mottaSamhandlerSvar">
      <soap:operation soapAction=""/>
      <wsdl:input name="mottaSamhandlerSvarRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="samordningFerdig">
      <soap:operation soapAction=""/>
      <wsdl:input name="samordningFerdigRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="mottaOSKvittering">
      <soap:operation soapAction=""/>
      <wsdl:input name="mottaOSKvitteringRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="positivOSKvitteringMottatt">
      <soap:operation soapAction=""/>
      <wsdl:input name="positivOSKvitteringMottattRequest">
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="iverksettVedtakWSEXP_IverksettVedtakTestHttpService">
    <wsdl:port binding="this:iverksettVedtakWSEXP_IverksettVedtakTestHttpBinding" name="iverksettVedtakTestWSEXP_IverksettVedtakTestHttpPort">
      <soap:address location="http://localhost:9080/nav-bproc-test-ppen015Web/sca/iverksettVedtakTestWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
