<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/nav/xslt/ForMangeEpsFnr.map" md5sum="d5db5b1a08df96e32ec4ddcfd66ab99e" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		ForMangeEpsFnr.map
*   Map declaration(s):	ForMangeEpsFnr
*   Input file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Fnav-tjeneste-person%252Fno%252Fnav%252Fbo%257DlocalVariables/message%3D%257Bhttp%253A%252F%252Fnav.no%252Fvirksomhet%252Ftjenester%252Ffamilieforhold%252Fv1%257DhentFamilierelasjonerResponse/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/transientContext%3D%257Bhttp%253A%252F%252Fnav-tjeneste-person%252Fno%252Fnav%252Fbo%257DlocalVariables/message%3D%257Bhttp%253A%252F%252Fnav.no%252Fvirksomhet%252Ftjenester%252Fperson%252Fv1%257DregistrereAdresseForDodsbo_kunneIkkeRegistrereAdresseForDodsbo/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://nav.no/virksomhet/tjenester/familieforhold/v1"
    xmlns:in2="wsdl.http://nav.no/virksomhet/tjenester/familieforhold/v1"
    xmlns:in3="http://nav.no/virksomhet/tjenester/familieforhold/feil/v1"
    xmlns:in4="http://nav.no/virksomhet/grunnlag/familieforhold/v1"
    xmlns:in5="http://nav.no/virksomhet/tjenester/familieforhold/meldinger/v1"
    xmlns:io="http://nav-tjeneste-person/no/nav/bo"
    xmlns:io4="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io5="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out6="http://nav.no/virksomhet/part/person/v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out="http://nav.no/virksomhet/tjenester/person/v1"
    xmlns:out7="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/tjenester/person"
    xmlns:out8="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/part/person"
    xmlns:io2="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:out2="http://nav.no/virksomhet/tjenester/person/feil/v1"
    xmlns:io3="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:io6="http://nav.no/virksomhet/tjenester/felles/v1"
    xmlns:io7="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out3="wsdl.http://nav.no/virksomhet/tjenester/person/v1"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="http://www.w3.org/2005/08/addressing"
    xmlns:out4="http://nav.no/virksomhet/tjenester/person/meldinger/v1"
    xmlns:out5="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/tjenester/person/meldinger"
    xmlns:map="http://nav-tjeneste-person/no/nav/xslt/ForMangeEpsFnr"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="set in msl math exsl in2 in3 date in4 in5 xalan str map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io5:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:ForMangeEpsFnr2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io5:smo" mode="map:ForMangeEpsFnr"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template match="io5:smo"  mode="map:ForMangeEpsFnr">
    <io5:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out3:registrereAdresseForDodsbo_kunneIkkeRegistrereAdresseForDodsbo'"/>
        </xsl:attribute>
        <out:registrereAdresseForDodsbokunneIkkeRegistrereAdresseForDodsbo>
          <!-- a simple mapping with no associated source:  to "errorMessage"(string) -->
          <errorMessage>
            <xsl:text>KunneIkkeRegistrereAdresseForDodsbo - Flere pårørende Funnet</xsl:text>
          </errorMessage>
          <!-- a simple mapping with no associated source:  to "errorSource"(string) -->
          <errorSource>
            <xsl:text>nav-tjeneste-person_RegistrereAdresseForDodsbo_A2</xsl:text>
          </errorSource>
          <!-- a simple data mapping: "context/transient/brukerFnr"(string) to "rootCause"(string) -->
          <xsl:if test="context/transient/brukerFnr">
            <rootCause>
              <xsl:value-of select="context/transient/brukerFnr"/>
            </rootCause>
          </xsl:if>
        </out:registrereAdresseForDodsbokunneIkkeRegistrereAdresseForDodsbo>
      </body>
    </io5:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io5:smo" to "io5:smo".  -->
  <xsl:template name="map:ForMangeEpsFnr2">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:registrereAdresseForDodsbo_kunneIkkeRegistrereAdresseForDodsbo'"/>
      </xsl:attribute>
      <out:registrereAdresseForDodsbokunneIkkeRegistrereAdresseForDodsbo>
        <!-- a simple mapping with no associated source:  to "errorMessage"(string) -->
        <errorMessage>
          <xsl:text>KunneIkkeRegistrereAdresseForDodsbo - Flere pårørende Funnet</xsl:text>
        </errorMessage>
        <!-- a simple mapping with no associated source:  to "errorSource"(string) -->
        <errorSource>
          <xsl:text>nav-tjeneste-person_RegistrereAdresseForDodsbo_A2</xsl:text>
        </errorSource>
        <!-- a simple data mapping: "$smo/context/transient/brukerFnr"(string) to "rootCause"(string) -->
        <xsl:if test="$smo/context/transient/brukerFnr">
          <rootCause>
            <xsl:value-of select="$smo/context/transient/brukerFnr"/>
          </rootCause>
        </xsl:if>
      </out:registrereAdresseForDodsbokunneIkkeRegistrereAdresseForDodsbo>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
