<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="no/nav/xslt/hentTPSAdresseMap.map" md5sum="2964a8e5db34ef6505fdf9896cca8d2c" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		hentTPSAdresseMap.map
*   Map declaration(s):	hentTPSAdresseMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fnav.no%252Fvirksomhet%252Ftjenester%252Fperson%252Fv1%257DregistrereAdresseForDodsboRequest/xpath%3D%252Fbody/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fnav-lib-frg-tps%252Fno%252Fnav%252Flib%252Ffrg%252Finf%257DhentTPSDataRequestMsg/xpath%3D%252Fbody/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://nav.no/virksomhet/part/person/v1"
    xmlns:in2="http://nav.no/virksomhet/tjenester/person/v1"
    xmlns:in3="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/tjenester/person"
    xmlns:in4="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/part/person"
    xmlns:in5="http://nav.no/virksomhet/tjenester/person/feil/v1"
    xmlns:in6="http://nav.no/virksomhet/tjenester/felles/v1"
    xmlns:in7="wsdl.http://nav.no/virksomhet/tjenester/person/v1"
    xmlns:in8="http://nav.no/virksomhet/tjenester/person/meldinger/v1"
    xmlns:in9="http://nav-person-tjenestespesifikasjon/no/nav/virksomhet/tjenester/person/meldinger"
    xmlns:out="http://nav-lib-frg-tps/no/nav/lib/frg/tps/fault"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:out2="http://nav-lib-frg-tps/no/nav/lib/frg/inf"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:out3="wsdl.http://nav-lib-frg-tps/no/nav/lib/frg/inf"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://nav-tjeneste-person/no/nav/xslt/hentTPSAdresseMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="set in msl math exsl in2 date in3 in4 xalan in5 in6 str in7 in8 in9 map"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'out3:hentTPSDataRequestMsg'"/>
            </xsl:attribute>
            <xsl:call-template name="map:hentTPSAdresseMap2">
              <xsl:with-param name="body" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="body" mode="map:hentTPSAdresseMap"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "body" to "body".  -->
  <xsl:template match="body"  mode="map:hentTPSAdresseMap">
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out3:hentTPSDataRequestMsg'"/>
      </xsl:attribute>
      <!-- a structural mapping: "in2:registrereAdresseForDodsbo"(<Anonymous>) to "out2:hentTPSData"(<Anonymous>) -->
      <xsl:apply-templates select="in2:registrereAdresseForDodsbo" mode="localRegistrereAdresseForDodsboToHentTPSData_969064480"/>
    </body>
  </xsl:template>

  <!-- This rule represents a type mapping: "body" to "body".  -->
  <xsl:template name="map:hentTPSAdresseMap2">
    <xsl:param name="body"/>
    <!-- a structural mapping: "$body/in2:registrereAdresseForDodsbo"(<Anonymous>) to "out2:hentTPSData"(<Anonymous>) -->
    <xsl:apply-templates select="$body/in2:registrereAdresseForDodsbo" mode="localRegistrereAdresseForDodsboToHentTPSData_969064480"/>
  </xsl:template>

  <!-- This rule represents an element mapping: "in2:registrereAdresseForDodsbo" to "out2:hentTPSData".  -->
  <xsl:template match="in2:registrereAdresseForDodsbo"  mode="localRegistrereAdresseForDodsboToHentTPSData_969064480">
    <out2:hentTPSData>
      <!-- a structural mapping: "request"(RegistrereAdresseForDodsboRequest) to "tpsPersonDataReq"(tpsPersonDataType) -->
      <xsl:apply-templates select="request" mode="localRequestToTpsPersonDataReq_903832467"/>
    </out2:hentTPSData>
  </xsl:template>

  <!-- This rule represents an element mapping: "request" to "tpsPersonDataReq".  -->
  <xsl:template match="request"  mode="localRequestToTpsPersonDataReq_903832467">
    <tpsPersonDataReq>
      <tpsServiceRutine>
        <!-- a simple mapping with no associated source:  to "serviceRutinenavn"(<SRnavn>) -->
        <serviceRutinenavn>
          <xsl:text>FS03-FDNUMMER-ADRESSER-M</xsl:text>
        </serviceRutinenavn>
        <!-- a simple mapping with no associated source:  to "aksjonsKode"(<AK>) -->
        <aksjonsKode>
          <xsl:text>A</xsl:text>
        </aksjonsKode>
        <!-- a simple mapping with no associated source:  to "aksjonsKode2"(<AK2>) -->
        <aksjonsKode2>
          <xsl:text>0</xsl:text>
        </aksjonsKode2>
        <M303>
          <!-- a simple mapping with no associated source:  to "adressePrior"(string) -->
          <adressePrior>
            <xsl:text>2</xsl:text>
          </adressePrior>
        </M303>
        <!-- a simple mapping with no associated source:  to "antallFnr"(<AK2>) -->
        <antallFnr>
          <xsl:text>1</xsl:text>
        </antallFnr>
        <nFnr>
          <!-- a simple data mapping: "fnr"(string) to "fnr"(Tfnr) -->
          <fnr>
            <xsl:value-of select="fnr"/>
          </fnr>
        </nFnr>
      </tpsServiceRutine>
    </tpsPersonDataReq>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
