<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="SystemAvailabilityConfigWSEXP_StubbingHttp_Service" targetNamespace="http://system-availability-config/Stubbing/Binding" xmlns:Port_0="http://system-availability-config/Stubbing" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://system-availability-config/Stubbing/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="Stubbing.wsdl" namespace="http://system-availability-config/Stubbing"/>
  <wsdl:binding name="SystemAvailabilityConfigWSEXP_StubbingHttpBinding" type="Port_0:Stubbing">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="enableStubs">
      <soap:operation soapAction=""/>
      <wsdl:input name="enableStubsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="enableStubsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="enableStubsAllOperations">
      <soap:operation soapAction=""/>
      <wsdl:input name="enableStubsAllOperationsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="enableStubsAllOperationsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="enableRecordingAllOperations">
      <soap:operation soapAction=""/>
      <wsdl:input name="enableRecordingAllOperationsRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="enableRecordingAllOperationsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SystemAvailabilityConfigWSEXP_StubbingHttpService">
    <wsdl:port binding="this:SystemAvailabilityConfigWSEXP_StubbingHttpBinding" name="SystemAvailabilityConfigWSEXP_StubbingHttpPort">
      <soap:address location="http://localhost:9080/system-availability-configWeb/sca/SystemAvailabilityConfigWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>