<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ResponseTimeTestWSEXP_ResponseTimeTestHttp_Service" targetNamespace="http://nav-module-responsetime/no/nav/inf/ResponseTimeTest/Binding" xmlns:Port_0="http://nav-module-responsetime/no/nav/inf/ResponseTimeTest" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://nav-module-responsetime/no/nav/inf/ResponseTimeTest/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ResponseTimeTest.wsdl" namespace="http://nav-module-responsetime/no/nav/inf/ResponseTimeTest"/>
  <wsdl:binding name="ResponseTimeTestWSEXP_ResponseTimeTestHttpBinding" type="Port_0:ResponseTimeTest">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="measureResponseTimes">
      <soap:operation soapAction=""/>
      <wsdl:input name="measureResponseTimesRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="measureResponseTimesResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ResponseTimeTestWSEXP_ResponseTimeTestHttpService">
    <wsdl:port binding="this:ResponseTimeTestWSEXP_ResponseTimeTestHttpBinding" name="ResponseTimeTestWSEXP_ResponseTimeTestHttpPort">
      <soap:address location="http://localhost:9080/stelvio-module-responsetimeWeb/sca/ResponseTimeTestWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>