<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ResponseTimeWSEXP_ResponseTimeHttp_Service" targetNamespace="http://nav-lib-responsetime/no/nav/inf/ResponseTime/Binding" xmlns:Port_0="http://nav-lib-responsetime/no/nav/inf/ResponseTime" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://nav-lib-responsetime/no/nav/inf/ResponseTime/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ResponseTime.wsdl" namespace="http://nav-lib-responsetime/no/nav/inf/ResponseTime"/>
  <wsdl:binding name="ResponseTimeWSEXP_ResponseTimeHttpBinding" type="Port_0:ResponseTime">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="measureResponsetime">
      <soap:operation soapAction=""/>
      <wsdl:input name="measureResponsetimeRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="measureResponsetimeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="measureResponsetimeList">
      <soap:operation soapAction=""/>
      <wsdl:input name="measureResponsetimeListRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="measureResponsetimeListResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ResponseTimeWSEXP_ResponseTimeHttpService">
    <wsdl:port binding="this:ResponseTimeWSEXP_ResponseTimeHttpBinding" name="ResponseTimeWSEXP_ResponseTimeHttpPort">
      <soap:address location="http://localhost:9080/stelvio-module-responsetime-providerWeb/sca/ResponseTimeWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>