<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="OrderQueryWSEXP_OrderQueryHttp_Service" targetNamespace="http://www.stelvio.no/example/order/V1/OrderQuery/Binding" xmlns:Port_0="http://www.stelvio.no/example/order/V1/OrderQuery" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://www.stelvio.no/example/order/V1/OrderQuery/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="OrderQuery.wsdl" namespace="http://www.stelvio.no/example/order/V1/OrderQuery"/>
  <wsdl:binding name="OrderQueryWSEXP_OrderQueryHttpBinding" type="Port_0:OrderQuery">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getOrder">
      <soap:operation soapAction=""/>
      <wsdl:input name="getOrderRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getOrderResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OrderQueryWSEXP_OrderQueryHttpService">
    <wsdl:port binding="this:OrderQueryWSEXP_OrderQueryHttpBinding" name="OrderQueryV1WSEXP_OrderQueryHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-order-serviceWeb/sca/OrderQueryV1WSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>