<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/XSLTransformation1_req_1.map" md5sum="5cf47287aa23814e6bb09a14935afeb9" version="7.0.302" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor V7.0.302
*
*   Mapping file:		XSLTransformation1_req_1.map
*   Map declaration(s):	XSLTransformation1_req_1
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstelvio-example-contexthandler-prosess%252Fno%252Fnav%252Finf%252FStartExampleProcess%257DstartExampleProcessWRRequestMsg/xpath%3D%252F/smo.xsd, ../../stelvio-commons-lib/no/stelvio/common/context/StelvioContext.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252Fstelvio-example-contexthandler-prosess%252Fno%252Fnav%252Finf%252FStartExampleProcess%257DstartExampleProcessWRRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://www.nav.no/StelvioContextPropagation"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io4="http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:io5="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io6="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:io8="wsdl.http://stelvio-example-contexthandler-prosess/no/nav/inf/StartExampleProcess"
    xmlns:io7="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://stelvio-example-contexthandler-java/xslt/XSLTransformation1_req_1"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="xalan str set in msl math map exsl date"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <dataObject>
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:XSLTransformation1_req_12">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </dataObject>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:XSLTransformation1_req_1"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:XSLTransformation1_req_1">
    <io2:smo>
      <context>
        <userContext>
          <entries>
            <!-- a structural mapping: "headers/SOAPHeader/value"(StelvioContext) to "value"(StelvioContext) -->
            <xsl:if test="headers/SOAPHeader/value">
              <xsl:copy-of select="headers/SOAPHeader/value"/>
            </xsl:if>
          </entries>
        </userContext>
      </context>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'io8:startExampleProcessWRRequestMsg'"/>
        </xsl:attribute>
        <io4:startExampleProcessWR>
          <!-- a simple data mapping: "body/io4:startExampleProcessWR/inputString"(string) to "inputString"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space(body/io4:startExampleProcessWR/inputString)">
              <inputString>
                <xsl:value-of select="body/io4:startExampleProcessWR/inputString"/>
              </inputString>
            </xsl:when>
            <xsl:otherwise>
              <inputString xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
        </io4:startExampleProcessWR>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:XSLTransformation1_req_12">
    <xsl:param name="smo"/>
    <context>
      <userContext>
        <entries>
          <!-- a structural mapping: "$smo/headers/SOAPHeader/value"(StelvioContext) to "value"(StelvioContext) -->
          <xsl:if test="$smo/headers/SOAPHeader/value">
            <xsl:copy-of select="$smo/headers/SOAPHeader/value"/>
          </xsl:if>
        </entries>
      </userContext>
    </context>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'io8:startExampleProcessWRRequestMsg'"/>
      </xsl:attribute>
      <io4:startExampleProcessWR>
        <!-- a simple data mapping: "$smo/body/io4:startExampleProcessWR/inputString"(string) to "inputString"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space($smo/body/io4:startExampleProcessWR/inputString)">
            <inputString>
              <xsl:value-of select="$smo/body/io4:startExampleProcessWR/inputString"/>
            </inputString>
          </xsl:when>
          <xsl:otherwise>
            <inputString xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
      </io4:startExampleProcessWR>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
