<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="PersonServiceWSEXP_PersonServiceHttp_Service" targetNamespace="http://www.stelvio.no/example/services/V1/PersonService/Binding" xmlns:Port_0="http://www.stelvio.no/example/services/V1/PersonService" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:this="http://www.stelvio.no/example/services/V1/PersonService/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="no/stelvio/example/services/V1/PersonService.wsdl" namespace="http://www.stelvio.no/example/services/V1/PersonService"/>
  <wsdl:binding name="PersonServiceWSEXP_PersonServiceHttpBinding" type="Port_0:PersonService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="PersonServiceWSEXP_PersonServiceHttpService">
    <wsdl:port binding="this:PersonServiceWSEXP_PersonServiceHttpBinding" name="PersonServiceWSEXP_PersonServiceHttpPort">
      <soap12:address location="http://localhost:9080/stelvio-example-person-proxyWeb/sca/PersonServiceWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>