<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="ContextHandlerVerifierProviderWSEXP_ContextHandlerVerifierProviderHttp_Service" targetNamespace="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier/Binding" xmlns:Port_0="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:this="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier/Binding" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import location="ContextHandlerVerifierProvider.wsdl" namespace="http://stelvio-example-contexthandler-provider-lib/no/nav/inf/ContextHandlerVerifier"/>
  <wsdl:binding name="ContextHandlerVerifierProviderWSEXP_ContextHandlerVerifierProviderHttpBinding" type="Port_0:ContextHandlerVerifierProvider">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="callNoWSChain">
      <soap:operation soapAction=""/>
      <wsdl:input name="callNoWSChainRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="callNoWSChainResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="callWSChain">
      <soap:operation soapAction=""/>
      <wsdl:input name="callWSChainRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="callWSChainResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ContextHandlerVerifierProviderWSEXP_ContextHandlerVerifierProviderHttpService">
    <wsdl:port binding="this:ContextHandlerVerifierProviderWSEXP_ContextHandlerVerifierProviderHttpBinding" name="ContextHandlerVerifierProviderWSEXP_ContextHandlerVerifierProviderHttpPort">
      <soap:address location="http://localhost:9080/stelvio-example-contexthandler-providerWeb/sca/ContextHandlerVerifierProviderWSEXP"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>